# RL-CrowdNav **V5** — An Ablation Study of Reward-Shaping Components in Deep Reinforcement Learning for Socially Aware Robot Navigation

*Complete $2^5$ factorial · exact Shapley attribution · interaction decomposition · mechanism controls · density generalisation — end to end in one Kaggle notebook.*

---

## 1 · What this notebook is for

The paper asks one question:

> **Of the five reward-shaping components we use for socially aware robot navigation, which ones actually carry the result, by how much, in what direction, and — crucially — *why* do they differ from one another?**

Everything below is built to answer that question in a way a reviewer cannot wave away.

## 2 · The five components

| ID | Component | Form | What it is *supposed* to do |
|----|-----------|------|------------------------------|
| **R1** | Goal reaching | sparse terminal $+w_{goal}$ when $\lVert p_r-g\rVert<r_{goal}$ | define the task |
| **R2** | Distance to goal | potential-based shaping, $w_{dist}(\gamma\Phi(s')-\Phi(s))$, $\Phi(s)=-\lVert p_r-g\rVert/L$ | densify the goal signal without changing the optimum |
| **R3** | Personal space | $-w_{space}\sum_i \max(0,\,r_{comfort}-d_i)^2$ | proxemic comfort — a *positional* safety signal |
| **R4** | Time to collision | $-w_{ttc}\sum_{i:\tau_i<\tau_{\min}}\big(\tfrac{1}{\tau_i+\epsilon}-\tfrac{1}{\tau_{\min}+\epsilon}\big)$ | anticipatory safety — a *velocity* signal |
| **R5** | Jerk / smoothness | $-w_{jerk}\lVert a_t-a_{t-1}\rVert^2$ | ride comfort / actuator friendliness |

Two terms are **deliberately not ablated** because they define the *task* rather than shape it: the collision penalty $r_{collision}=-1.25$ and the per-step time cost $r_{step}=-0.005$. Removing either would change what "success" means, and an ablation that changes the task is not an ablation.

---

## 3 · The methodological problem this version fixes

Every previous version of this study — and, as far as we can tell, essentially the whole crowd-navigation reward-design literature — reports **leave-one-out** numbers:

$$\mathrm{LOO}(i) \;=\; v(N) - v(N\setminus\{i\})$$

"What does component $i$ add on top of the other four?" That number is **context-dependent**, and our own earlier runs show exactly how badly it can mislead:

| | measured in V4 (6 seeds, 500 held-out scenarios) |
|---|---|
| `A5_no-jerk` (drop **R5** from the full set) | success $0.004$ — total collapse |
| `B2_goal+dist` (**R5** absent, but so are R3/R4) | success $0.000$ |
| `B3_goal+dist+jerk` (= B2 **plus R5**) | success $0.959$ |
| `A3_no-space` (drop **R3**) | $0.964$ — *no effect* |
| `A4_no-ttc` (drop **R4**) | $0.965$ — *no effect* |

Read literally, that table says a term weighted $0.02$ is worth $+0.95$ success while two safety terms are worth nothing. Both readings are artefacts of the single context they were measured in. In particular:

> **Leave-one-out is structurally blind to substitutes.** If R3 and R4 encode overlapping information, dropping *either alone* costs nothing because the other covers for it — and LOO dutifully reports $0.00$ twice. The unit test in §5 of this notebook demonstrates the failure on a synthetic game where LOO reports $0.00$ for two components whose true credit is $0.50$ each.

## 4 · What V5 does instead

**We run the complete $2^5 = 32$-cell factorial**, every subset of the five components, at six training seeds each — 192 training runs for the core design. From the complete lattice we compute, *exactly* and with no fitted model and no distributional assumption:

1. **Shapley value** $\phi_i$ of each component — its marginal contribution averaged over all $2^4=16$ contexts, with the weighting that uniquely satisfies efficiency ($\sum_i\phi_i = v(N)-v(\varnothing)$), symmetry, linearity and the null-player property.
2. **Möbius (Harsanyi) decomposition** — an explicit dividend for every pair, triple, … of components. A **negative pairwise term means substitutes** (each covers for the other — the exact pathology that breaks LOO); a **positive one means complements**.
3. **Leave-one-out and add-one-in as two special cases of the same object**, so the paper can show where the conventional number is trustworthy and where it is not.

Each quantity is computed independently *within* every training seed, and the seeds are then treated as the sample — the correct unit of analysis for a deep-RL study. Inference uses **exact sign-flip permutation tests** (all $2^6=64$ sign assignments enumerated) and **percentile bootstrap** intervals.

**Null results are tested as claims, not asserted from non-significance.** For any component we want to report as inert, we run **TOST equivalence tests** against a pre-declared margin of $\pm0.02$ success. "We failed to reject" and "we demonstrated equivalence" are different sentences and only one of them belongs in a paper.

## 5 · Four experiments that explain *why*, not just *how much*

| Stage | Question | Design |
|---|---|---|
| **A** | How much does each component contribute, over all contexts? | complete $2^5$ lattice × 6 seeds |
| **D** | Is it the component, or the *form* of the shaping? | policy-invariant PBRS vs. naive progress shaping, same component set |
| **C** | *Why* is a $0.02$-weighted smoothness term worth $+0.95$ success? | (i) `w_jerk` dose–response over three orders of magnitude; (ii) **causal mechanism control** — an env-side action low-pass filter that supplies temporal action coherence from the *dynamics* while leaving the reward untouched |
| **B** | Do the social terms only bind when the crowd binds? | the $\{R3,R4\}$ sub-factorial re-run at double pedestrian density |
| **E** | What is the best policy this reward design can produce? | the winning configuration retrained at an extended budget, exported to ONNX |

Stage **C(ii)** is the one that turns a correlation into a mechanism. Our hypothesis is that R5 is **not** a comfort term at all in this setting:

> In a goal-aligned velocity action frame, temporally uncorrelated actions *cancel* — an untrained policy random-walks in place and covers ~2 m of an 8 m journey, so the terminal goal reward is never reached and no arm can bootstrap from it. The jerk penalty is the only term that rewards temporal coherence, so it is secretly acting as an **exploration regulariser**, not as a preference the agent has to be paid to hold.

If that is right, then raising action autocorrelation *by any means* should rescue the no-jerk arms. The filter does exactly that without touching a single reward coefficient. It is a falsifiable prediction with a clean control, and it is what lets the paper write "because", not "we observe".

## 6 · Engineering that makes this fit in one session

Carried over from V4, all previously measured and verified:

- **Open-loop crowd pool.** With `robot_visible=False` the crowd is a closed autonomous system whose whole trajectory is a function of the reset seed, so ORCA is solved once per scenario and replayed. Asserted **bit-identical** to the live simulator before use.
- **`DummyVecEnv` + run-level parallelism.** `SubprocVecEnv` pickles a 40-float observation across a pipe and syncs on the slowest worker *every step*; run-level parallelism has one join per run.
- **Single-threaded everything**, with BLAS thread pools pinned *before* the first `numpy`/`torch` import.

New in V5:

- **A deadline-aware budget scheduler.** Every stage asks a `Budget` object how much time is actually left and sizes itself from *measured* throughput. Stages run in priority order and are skipped rather than truncated, so a session that runs short still produces a complete, analysable core result.
- **An architecture pre-flight.** The policy width is chosen by training the reference arm at two widths for *equal wall-clock time* and keeping whichever learns more per second — a measured decision, not a guess.
- **Linear learning-rate decay**, applied identically to every arm. The headline metric is evaluated with `deterministic=True`, which reads the mean of the action distribution; a policy still taking full-size steps at the end of training has a mean that is still wandering.

## 7 · Honest framing of the performance ceiling

This scenario is deliberately hard: the robot is **invisible** to the pedestrians, roughly half of whom are faster than it. Measured on held-out scenarios, a robot that stands perfectly still is struck in **26.7 %** of episodes, and ORCA driving the robot itself peaks at **0.827** success. A ceiling near 1.0 is neither reachable nor desirable — **an ablation needs headroom to discriminate, and the spread between arms is the result, not the mean.**

## 8 · How to run

Run top to bottom. Set `QUICK_TEST = True` in §3 for a ~12-minute smoke run that exercises every cell and produces every artefact, then set it back to `False`. Training is **resumable**: re-running any training cell skips runs whose `model.zip` already exists, so a session that hits the wall clock can be continued in a second session.

## 0 · Environment setup and dependency resolution

In [1]:
# Thread pools MUST be pinned before numpy / torch are imported for the first
# time: BLAS spawns its pool at import and th.set_num_threads() cannot reach it.
# Every training run is single-threaded by design; parallelism is at the RUN
# level, so any per-process thread pool is pure contention.
import os
for _v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS",
           "NUMEXPR_NUM_THREADS", "VECLIB_MAXIMUM_THREADS"):
    os.environ[_v] = "1"

import sys, json, time, math, glob, shutil, platform, subprocess, warnings, importlib
warnings.filterwarnings("ignore")

NOTEBOOK_T0 = time.time()          # the session clock every stage is sized against

WORK = "/kaggle/working" if os.path.isdir("/kaggle/working") else os.path.abspath("./crowdnav_ablation")
os.makedirs(WORK, exist_ok=True); os.chdir(WORK)
if WORK not in sys.path: sys.path.insert(0, WORK)
OUT = os.path.join(WORK, "results"); os.makedirs(OUT, exist_ok=True)
for sub in ("runs", "figures", "tables", "onnx", "stages"):
    os.makedirs(os.path.join(OUT, sub), exist_ok=True)

def sh(cmd):
    print(">", cmd)
    return subprocess.run(cmd, shell=True, capture_output=True, text=True)

def ensure_stable_baselines3():
    """Install SB3 WITHOUT touching the pre-installed CUDA build of PyTorch.

    SB3 pins `torch>=2.8`; a plain `pip install` on an image with an older torch
    triggers a multi-GB CUDA reinstall that frequently mismatches the driver.
    `--no-deps` avoids that entirely -- PPO/MlpPolicy works fine on torch>=2.0.
    """
    try:
        import stable_baselines3 as s; return s.__version__
    except Exception: pass
    for spec in ("stable-baselines3==2.9.0", "stable-baselines3==2.4.1"):
        sh(f"{sys.executable} -m pip install -q --no-deps {spec}")
        importlib.invalidate_caches()
        try:
            import stable_baselines3 as s; return s.__version__
        except Exception:
            for m in [k for k in sys.modules if k.startswith("stable_baselines3")]:
                sys.modules.pop(m, None)
    sh(f"{sys.executable} -m pip install -q stable-baselines3")
    importlib.invalidate_caches()
    import stable_baselines3 as s; return s.__version__

def ensure(pkg, pip_name=None):
    try:
        importlib.import_module(pkg); return True
    except Exception:
        sh(f"{sys.executable} -m pip install -q {pip_name or pkg}")
        importlib.invalidate_caches()
        try:
            importlib.import_module(pkg); return True
        except Exception:
            print(f"  !! could not install {pkg} (is notebook internet on?)"); return False

SB3_VERSION = ensure_stable_baselines3()
HAS_ONNX    = ensure("onnx") and ensure("onnxruntime")
ensure("tensorboard"); ensure("scipy")

import numpy as np, pandas as pd, torch as th, gymnasium as gym
import stable_baselines3

# A single narration helper, used after every analysis cell.  The point of this
# notebook is that somebody can read the EXECUTED output and understand the
# study without also reading the code, so every result prints its own
# interpretation next to it.
def narrate(title, lines, width=100):
    body = lines if isinstance(lines, (list, tuple)) else [lines]
    print("\n" + "=" * width)
    print(f"|| {title}")
    print("-" * width)
    for ln in body:
        for chunk in str(ln).split("\n"):
            while len(chunk) > width - 4:
                cut = chunk.rfind(" ", 0, width - 4)
                cut = cut if cut > 0 else width - 4
                print("   " + chunk[:cut]); chunk = chunk[cut:].lstrip()
            print("   " + chunk)
    print("=" * width)

print("\n" + "=" * 68)
print(f"python              {platform.python_version()}")
print(f"numpy               {np.__version__}")
print(f"pandas              {pd.__version__}")
print(f"torch               {th.__version__}")
print(f"gymnasium           {gym.__version__}")
print(f"stable-baselines3   {stable_baselines3.__version__}")
print(f"onnx available      {HAS_ONNX}")
print(f"cpu count           {os.cpu_count()}")
print(f"cuda available      {th.cuda.is_available()}  devices={th.cuda.device_count()}")
for i in range(th.cuda.device_count()):
    p = th.cuda.get_device_properties(i)
    print(f"  gpu[{i}]           {p.name}  {p.total_memory/1e9:.1f} GB")
print(f"working dir         {WORK}")
print("=" * 68)

> /usr/bin/python3 -m pip install -q --no-deps stable-baselines3==2.9.0

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

> /usr/bin/python3 -m pip install -q onnxruntime

====================================================================
python              3.12.13
numpy               2.0.2
pandas              2.3.3
torch               2.10.0+cu128
gymnasium           1.2.0
stable-baselines3   2.9.0
onnx available      True
cpu count           4
cuda available      True  devices=2
  gpu[0]           Tesla T4  15.6 GB
  gpu[1]           Tesla T4  15.6 GB
working dir         /kaggle/working
====================================================================

## 1 · The crowd simulator

### 1.1 ORCA (Optimal Reciprocal Collision Avoidance)

Pedestrians are driven by ORCA (van den Berg et al., 2011) — the same policy used for the humans in CrowdNav / CADRL / SARL. This is a faithful pure-Python port of the linear-programming core of the reference RVO2 C++ library, so the crowd behaviour is bit-for-bit reproducible on any machine and never depends on a Cython/CMake build succeeding. (`python-rvo2` breaks under Cython ≥ 3 and modern `setuptools`; §4.1 cross-validates our port against it numerically *when* it happens to build, and carries on unaffected when it does not.)

One addition over stock RVO2: a `responsibility` parameter. Stock ORCA assumes both agents share the avoidance effort equally (`0.5`). In the **invisible-robot** setting the humans cannot see the robot and will not yield, so a robot-side ORCA planner must take `responsibility=1.0`.

In [2]:
%%writefile orca.py
"""
Pure-Python ORCA (Optimal Reciprocal Collision Avoidance).

Faithful port of the linear-programming core of the reference RVO2 C++ library
(van den Berg, Guy, Lin & Manocha, 2011) -- the same algorithm that `python-rvo2`
wraps.  Kept dependency-free so that the crowd policy is bit-for-bit reproducible
on any machine and the notebook never depends on a Cython/CMake build succeeding.

Only agent-agent half-planes are used (no static obstacle lines), which matches
the circle-crossing benchmark used by CrowdNav / CADRL / SARL.
"""
import math

EPSILON = 1e-5


def _det(a, b):
    return a[0] * b[1] - a[1] * b[0]


def _abs_sq(v):
    return v[0] * v[0] + v[1] * v[1]


def _norm(v):
    n = math.sqrt(v[0] * v[0] + v[1] * v[1])
    if n < EPSILON:
        return (0.0, 0.0)
    return (v[0] / n, v[1] / n)


def _linear_program1(lines, line_no, radius, opt_velocity, direction_opt):
    """Optimise along the boundary of line `line_no`. Returns (ok, result)."""
    lp, ld = lines[line_no]
    dot_product = lp[0] * ld[0] + lp[1] * ld[1]
    discriminant = dot_product * dot_product + radius * radius - _abs_sq(lp)

    if discriminant < 0.0:
        return False, None

    sqrt_disc = math.sqrt(discriminant)
    t_left = -dot_product - sqrt_disc
    t_right = -dot_product + sqrt_disc

    for i in range(line_no):
        ip, idir = lines[i]
        denominator = _det(ld, idir)
        numerator = _det(idir, (lp[0] - ip[0], lp[1] - ip[1]))

        if abs(denominator) <= EPSILON:
            # Lines are (near) parallel.
            if numerator < 0.0:
                return False, None
            continue

        t = numerator / denominator
        if denominator >= 0.0:
            t_right = min(t_right, t)
        else:
            t_left = max(t_left, t)

        if t_left > t_right:
            return False, None

    if direction_opt:
        t = t_right if (opt_velocity[0] * ld[0] + opt_velocity[1] * ld[1]) > 0.0 else t_left
    else:
        t = ld[0] * (opt_velocity[0] - lp[0]) + ld[1] * (opt_velocity[1] - lp[1])
        if t < t_left:
            t = t_left
        elif t > t_right:
            t = t_right

    return True, (lp[0] + t * ld[0], lp[1] + t * ld[1])


def _linear_program2(lines, radius, opt_velocity, direction_opt):
    """Returns (index_of_first_failing_line, result)."""
    if direction_opt:
        result = (opt_velocity[0] * radius, opt_velocity[1] * radius)
    elif _abs_sq(opt_velocity) > radius * radius:
        u = _norm(opt_velocity)
        result = (u[0] * radius, u[1] * radius)
    else:
        result = (opt_velocity[0], opt_velocity[1])

    for i in range(len(lines)):
        ip, idir = lines[i]
        if _det(idir, (ip[0] - result[0], ip[1] - result[1])) > 0.0:
            ok, new_result = _linear_program1(lines, i, radius, opt_velocity, direction_opt)
            if not ok:
                return i, result
            result = new_result

    return len(lines), result


def _linear_program3(lines, begin_line, radius, result):
    """Relax the ORCA constraints uniformly when the LP is infeasible (dense crowds)."""
    distance = 0.0

    for i in range(begin_line, len(lines)):
        ip, idir = lines[i]
        if _det(idir, (ip[0] - result[0], ip[1] - result[1])) > distance:
            proj_lines = []
            for j in range(i):
                jp, jdir = lines[j]
                determinant = _det(idir, jdir)

                if abs(determinant) <= EPSILON:
                    if idir[0] * jdir[0] + idir[1] * jdir[1] > 0.0:
                        continue  # same direction
                    point = (0.5 * (ip[0] + jp[0]), 0.5 * (ip[1] + jp[1]))
                else:
                    s = _det(jdir, (ip[0] - jp[0], ip[1] - jp[1])) / determinant
                    point = (ip[0] + s * idir[0], ip[1] + s * idir[1])

                direction = _norm((jdir[0] - idir[0], jdir[1] - idir[1]))
                proj_lines.append((point, direction))

            temp_result = result
            n_fail, new_result = _linear_program2(
                proj_lines, radius, (-idir[1], idir[0]), True
            )
            if n_fail < len(proj_lines):
                result = temp_result
            else:
                result = new_result

            distance = _det(idir, (ip[0] - result[0], ip[1] - result[1]))

    return result


def orca_velocity(pos, vel, radius, pref_vel, max_speed,
                  neighbours, time_horizon=5.0, time_step=0.25,
                  neighbour_dist=10.0, max_neighbours=10, responsibility=0.5):
    """Compute one agent's new ORCA velocity.

    Parameters
    ----------
    pos, vel, pref_vel : (x, y) tuples for this agent
    radius, max_speed  : scalars for this agent
    neighbours         : list of (pos, vel, radius) tuples for other agents
    responsibility     : share of the avoidance effort this agent takes.  0.5 is
                         the reciprocal (mutual) case; use 1.0 when the other
                         agents cannot see this agent and will not cooperate.
    """
    inv_time_horizon = 1.0 / time_horizon
    inv_time_step = 1.0 / time_step

    # Keep the closest `max_neighbours` within `neighbour_dist` (as RVO2 does).
    cand = []
    nd_sq = neighbour_dist * neighbour_dist
    for (npos, nvel, nrad) in neighbours:
        d_sq = (npos[0] - pos[0]) ** 2 + (npos[1] - pos[1]) ** 2
        if d_sq < nd_sq:
            cand.append((d_sq, npos, nvel, nrad))
    cand.sort(key=lambda c: c[0])
    cand = cand[:max_neighbours]

    lines = []
    for (_, npos, nvel, nrad) in cand:
        rel_pos = (npos[0] - pos[0], npos[1] - pos[1])
        rel_vel = (vel[0] - nvel[0], vel[1] - nvel[1])
        dist_sq = _abs_sq(rel_pos)
        combined_radius = radius + nrad
        combined_radius_sq = combined_radius * combined_radius

        if dist_sq > combined_radius_sq:
            # No collision yet.
            w = (rel_vel[0] - inv_time_horizon * rel_pos[0],
                 rel_vel[1] - inv_time_horizon * rel_pos[1])
            w_len_sq = _abs_sq(w)
            dot1 = w[0] * rel_pos[0] + w[1] * rel_pos[1]

            if dot1 < 0.0 and dot1 * dot1 > combined_radius_sq * w_len_sq:
                # Project on cut-off circle.
                w_len = math.sqrt(w_len_sq)
                unit_w = (w[0] / w_len, w[1] / w_len)
                direction = (unit_w[1], -unit_w[0])
                u_mag = combined_radius * inv_time_horizon - w_len
                u = (u_mag * unit_w[0], u_mag * unit_w[1])
            else:
                # Project on legs.
                leg = math.sqrt(max(dist_sq - combined_radius_sq, 0.0))
                if _det(rel_pos, w) > 0.0:  # left leg
                    direction = ((rel_pos[0] * leg - rel_pos[1] * combined_radius) / dist_sq,
                                 (rel_pos[0] * combined_radius + rel_pos[1] * leg) / dist_sq)
                else:  # right leg
                    direction = (-(rel_pos[0] * leg + rel_pos[1] * combined_radius) / dist_sq,
                                 -(-rel_pos[0] * combined_radius + rel_pos[1] * leg) / dist_sq)
                dot2 = rel_vel[0] * direction[0] + rel_vel[1] * direction[1]
                u = (dot2 * direction[0] - rel_vel[0], dot2 * direction[1] - rel_vel[1])
        else:
            # Already colliding: use the time step instead of the horizon.
            w = (rel_vel[0] - inv_time_step * rel_pos[0],
                 rel_vel[1] - inv_time_step * rel_pos[1])
            w_len = math.sqrt(max(_abs_sq(w), EPSILON ** 2))
            unit_w = (w[0] / w_len, w[1] / w_len)
            direction = (unit_w[1], -unit_w[0])
            u_mag = combined_radius * inv_time_step - w_len
            u = (u_mag * unit_w[0], u_mag * unit_w[1])

        point = (vel[0] + responsibility * u[0], vel[1] + responsibility * u[1])
        lines.append((point, direction))

    line_fail, result = _linear_program2(lines, max_speed, pref_vel, False)
    if line_fail < len(lines):
        result = _linear_program3(lines, line_fail, max_speed, result)
    return result

Writing orca.py

### 1.2 Environment and the modular reward

**Scenario.** Circle crossing (Chen et al., ICRA 2019): $N$ humans spawn on a circle of radius 4 m with angular/radial jitter and cross to the antipodal point; when a human arrives, a new antipodal goal is drawn so the crowd stays live for the whole episode. The robot crosses the same circle from $(0,-4)$ to $(0,4)$. $\Delta t=0.25$ s, horizon 25 s (100 steps).

**Invisible robot.** The humans do *not* include the robot in their ORCA neighbourhood. This is the harder and more standard variant: it forbids the policy from offloading collision avoidance onto a cooperative crowd, which would otherwise let a reckless policy score well.

**Observation (40-D for $N=5$, robot-centric and goal-aligned).** The frame is rotated so the goal lies along $+x$ — the *rotate* transform of SARL. Humans are sorted nearest-first so the flattened vector is permutation-stable. All quantities are normalised in-env by fixed constants, so **no `VecNormalize` is needed** and the exported ONNX graph is self-contained.

- robot: $[\,d_g,\ v_{pref},\ r_{robot},\ v_x',\ v_y'\,]$ — 5 dims
- per human $i$: $[\,p_x',\ p_y',\ v_x',\ v_y',\ r_i,\ d_i,\ d_i-r_{robot}-r_i\,]$ — 7 dims

**Action (2-D, continuous, in the same goal-aligned frame).** $a\in[-1,1]^2$ maps to $(v_{\text{toward goal}},\,v_{\text{lateral}})\cdot v_{pref}$. Keeping the action in the *same* frame as the observation is essential — with a world-frame action a goal-aligned observation is not actionable. **This frame is also why the jerk finding exists at all:** in a goal-aligned velocity frame, temporally uncorrelated actions cancel, so an incoherent policy walks on the spot.

**Collision** is checked against the closest point of the *relative motion segment* over the whole timestep, so fast crossings cannot tunnel through one another.

### New in V5

1. **The complete $2^5$ lattice.** `ABLATION_CONFIGS` is generated programmatically — all 32 subsets — plus two non-lattice arms that swap the *form* of R2. Classical names (`A5_no-jerk`, …) survive as aliases and resolve to the same lattice cell.
2. **Behavioural instrumentation.** Every episode now additionally reports `action_autocorr` (lag-1 autocorrelation of the action, averaged over the two dimensions), `mean_speed`, `displacement_efficiency` (net displacement per metre walked — this is what separates *"went nowhere"* from *"took a long route"*) and `net_progress_per_step`. These are the quantities the mechanism analysis runs on and they cost one dot product per step.
3. **An env-side action low-pass filter**, `action_filter_alpha`: $a^{\text{eff}}_t=(1-\alpha)a_t+\alpha\,a^{\text{eff}}_{t-1}$. This is the **causal control** for the jerk finding — it supplies temporal coherence from the *dynamics* while leaving every reward coefficient untouched. `alpha = 0` is asserted bit-identical to the unfiltered environment in §4.

In [3]:
%%writefile crowd_env.py
"""
CrowdNavAblationEnv -- a Gymnasium environment for crowd-aware navigation with a
fully modular, config-driven reward function.

Scenario follows the standard `circle crossing` benchmark used by CADRL /
CrowdNav / SARL (Chen et al., ICRA 2019): N humans are placed on a circle and
must cross to the antipodal point; the robot must traverse the same circle.
Humans are driven by ORCA and (by default) cannot see the robot -- the
"invisible robot" setting, which is the harder and more standard variant because
it forbids the policy from offloading collision avoidance onto the crowd.

The five ablatable reward components are implemented as independent, additively
combined terms so that a configuration is fully described by a dict of booleans.
"""
from dataclasses import dataclass, field, asdict
import math
import os
from dataclasses import replace as _dc_replace
import numpy as np
import gymnasium as gym
from gymnasium import spaces

from orca import orca_velocity

# --------------------------------------------------------------------------- #
#  Configuration
# --------------------------------------------------------------------------- #

@dataclass
class EnvConfig:
    # --- scenario -----------------------------------------------------------
    n_humans: int = 5
    circle_radius: float = 4.0
    position_noise: float = 0.5      # jitter on the spawn circle
    robot_radius: float = 0.3
    human_radius_range: tuple = (0.3, 0.4)
    v_pref: float = 1.0              # robot preferred speed  (m/s)
    human_v_pref_range: tuple = (0.8, 1.2)
    kinematics: str = "holonomic"    # 'holonomic' | 'unicycle'
    action_frame: str = "goal_aligned"   # 'goal_aligned' | 'world' (holonomic only)
    omega_max: float = 1.5           # rad/s, unicycle only
    robot_visible: bool = False      # invisible-robot setting (harder, standard)

    # --- time ---------------------------------------------------------------
    time_step: float = 0.25          # s
    time_limit: float = 25.0         # s  -> 100 steps

    # --- ORCA (humans) ------------------------------------------------------
    orca_time_horizon: float = 5.0
    orca_neighbour_dist: float = 10.0
    human_goal_tolerance: float = 0.3

    # --- termination --------------------------------------------------------
    goal_tolerance: float = 0.3      # r_goal, distance at which success fires

    # --- reward weights (held CONSTANT across every ablation) ---------------
    w_goal: float = 1.0              # R1  terminal success bonus
    w_dist: float = 0.60             # R2  potential-based distance shaping
    w_space: float = 0.20            # R3  personal-space (proxemic) penalty
    w_ttc: float = 0.02              # R4  time-to-collision penalty
    w_jerk: float = 0.02             # R5  jerk / action-smoothness penalty
    # V4.0 shipped -0.75 and it was not enough.  PBRS sets Phi(terminal)=0 for
    # EVERY terminal state, so a terminating episode is refunded the whole
    # accumulated potential -- measured at +0.667 -- whether it ended at the goal
    # or inside a pedestrian.  A crash therefore cost 0.667-0.75 = -0.08 net.
    # Combined with r_step that made "dash and crash" (-0.442) tie with "stand
    # still" (-0.456), and crashing is the far easier basin to reach by gradient
    # descent, so the V4.0 quick run came back at collision = 1.00.
    # Measured over 80 held-out scenarios (competent / freeze / dash):
    #   -0.75, -0.010  ->  +0.406 / -0.464 / -0.474   dash ~ freeze  (the trap)
    #   -1.25, -0.005  ->  +0.467 / -0.226 / -0.880   clean ordering
    r_collision: float = -1.25       # task-level penalty, NOT ablated
    # Task-level per-step time cost.  NOT an ablatable component -- it is part
    # of the task definition, exactly like r_collision.  Its job is to remove
    # the freeze basin: with PBRS the shaping term F = gamma*Phi' - Phi expands
    # to gamma*progress/L + (1-gamma)*d/L, whose second half pays the agent
    # every step simply for standing far from the goal (+0.006/step in v3, i.e.
    # +0.6 over a 100-step timeout against a goal bonus of 1.0).  The v3 reward
    # landscape audit measured a FREEZE return of +0.406 under R1-5_full.
    # -0.01/step costs a full timeout -1.0 and drives that freeze return
    # strictly negative without touching the collision/shaping balance.
    # -0.005 rather than -0.010: with r_collision at -1.25 the freeze basin is
    # already gone (freeze = -0.226) and a smaller time cost leaves the competent
    # policy a healthy +0.467 instead of a thin +0.256.
    r_step: float = -0.005
    gamma: float = 0.99              # discount used inside the PBRS term

    dist_mode: str = "pbrs"          # 'pbrs' (policy-invariant) | 'progress' (naive)
    # Phi(s) = -||p_r - g|| / potential_scale.  The scale is NOT cosmetic.  With
    # an unnormalised potential the PBRS step reward contains a standing bonus
    #     F = [progress] + (1 - gamma) * |Phi(s')|
    # that pays the agent, every step, simply for being far from the goal.  At
    # scale=1, gamma=0.99, d=8 m and w_dist=0.15 that is +0.012/step -> +1.2 over
    # a 100-step timeout, exactly equal to the entire shaping budget earned by
    # reaching the goal.  Standing still therefore becomes reward-competitive
    # with navigating.  Dividing by the scenario diameter shrinks both that bonus
    # and the terminal shaping impulse to a fraction of the goal reward.
    potential_scale: float = 8.0     # = 2 * circle_radius
    r_comfort: float = 0.5           # personal-space radius (surface distance, m)
    ttc_threshold: float = 3.0       # tau_min (s)
    ttc_epsilon: float = 0.20        # eps guarding 1/tau

    # --- observation normalisation constants --------------------------------
    pos_scale: float = 6.0
    vel_scale: float = 1.5

    # --- open-loop crowd pool (throughput) ----------------------------------
    # In the invisible-robot setting the humans never see the robot, so the
    # whole crowd trajectory is a pure function of the reset seed.  Re-solving
    # ORCA inside the RL loop recomputes trajectories that are already known.
    # Pointing this at a pool file replays them instead: identical dynamics,
    # ~10x cheaper per step.  None => solve ORCA live (required if the robot
    # is visible).
    crowd_pool_path: str = None

    # --- mechanism control: env-side action low-pass filter -----------------
    # a_eff_t = (1 - alpha) * a_t + alpha * a_eff_{t-1}.  0.0 = off (default).
    # This supplies TEMPORAL ACTION COHERENCE from the DYNAMICS instead of from
    # the R5 reward term.  It is the causal control for the jerk finding: if
    # filtering rescues a no-jerk arm without changing its reward at all, then
    # R5's contribution is an optimisation/exploration effect, not a preference
    # the agent has to be paid to hold.
    action_filter_alpha: float = 0.0

    # --- instrumentation (off during training for throughput) ---------------
    emit_reward_parts: bool = False
    record_trajectory: bool = False

    # --- which reward components are ACTIVE --------------------------------
    use_goal: bool = True
    use_dist: bool = True
    use_space: bool = True
    use_ttc: bool = True
    use_jerk: bool = True


# --------------------------------------------------------------------------- #
#  Geometry helpers
# --------------------------------------------------------------------------- #

def point_to_segment_dist(x1, y1, x2, y2, px, py):
    """Shortest distance from (px, py) to segment (x1,y1)-(x2,y2)."""
    dx, dy = x2 - x1, y2 - y1
    denom = dx * dx + dy * dy
    if denom < 1e-12:
        return math.hypot(px - x1, py - y1)
    u = ((px - x1) * dx + (py - y1) * dy) / denom
    u = min(1.0, max(0.0, u))
    return math.hypot(px - (x1 + u * dx), py - (y1 + u * dy))


def _seg_dist_to_origin(a, b):
    """Vectorised point_to_segment_dist with p = origin. a, b: (n, 2)."""
    ab = b - a
    denom = np.einsum("ij,ij->i", ab, ab)
    u = np.where(denom < 1e-12, 0.0,
                 -np.einsum("ij,ij->i", a, ab) / np.where(denom < 1e-12, 1.0, denom))
    u = np.clip(u, 0.0, 1.0)
    return np.linalg.norm(a + u[:, None] * ab, axis=1)


def _ttc_vec(rel_pos, rel_vel, comb_r):
    """Vectorised time_to_collision. Returns inf where there is no impact."""
    a = np.einsum("ij,ij->i", rel_vel, rel_vel)
    b = 2.0 * np.einsum("ij,ij->i", rel_pos, rel_vel)
    cc = np.einsum("ij,ij->i", rel_pos, rel_pos) - comb_r ** 2
    out = np.full(a.shape, np.inf)
    ok = a >= 1e-9
    disc = b * b - 4.0 * a * cc
    hit = ok & (disc > 0.0)
    if np.any(hit):
        t = (-b[hit] - np.sqrt(disc[hit])) / (2.0 * a[hit])
        out[hit] = np.where(t > 0.0, t, np.inf)
    out[ok & (cc <= 0.0)] = 0.0                      # already overlapping
    return out


def time_to_collision(rel_pos, rel_vel, combined_radius):
    """Exact TTC for two discs on constant velocities. inf if never colliding."""
    a = rel_vel[0] ** 2 + rel_vel[1] ** 2
    if a < 1e-9:
        return math.inf
    b = 2.0 * (rel_pos[0] * rel_vel[0] + rel_pos[1] * rel_vel[1])
    c = rel_pos[0] ** 2 + rel_pos[1] ** 2 - combined_radius ** 2
    if c <= 0.0:
        return 0.0                      # already overlapping
    disc = b * b - 4.0 * a * c
    if disc <= 0.0:
        return math.inf
    t = (-b - math.sqrt(disc)) / (2.0 * a)
    return t if t > 0.0 else math.inf


# --------------------------------------------------------------------------- #
#  Open-loop crowd pool
# --------------------------------------------------------------------------- #
#  Only sound when cfg.robot_visible is False.  _orca_step() appends the robot
#  to a human's neighbour list ONLY under that flag, and _respawn_human_goals()
#  reads human positions alone, so with an invisible robot the crowd is a closed
#  autonomous system: its entire trajectory is fixed by the reset seed and can be
#  computed once and replayed for every arm, every seed, training and test.
_POOL_CACHE = {}


def load_crowd_pool(path):
    """Load a pool directory. `vel` is genuinely memory-mapped.

    NOTE: np.load(..., mmap_mode=...) is SILENTLY IGNORED for .npz archives --
    it returns an NpzFile and every key access materialises the whole array in
    that process.  With one 130 MB array per concurrent worker that is real
    memory and it does not scale with pool size, so the pool is stored as a
    directory of plain .npy files instead, where mmap_mode actually works and
    the OS page cache is shared between workers.
    """
    if path not in _POOL_CACHE:
        if os.path.isdir(path):
            vel = np.load(os.path.join(path, "vel.npy"), mmap_mode="r")
            pos0 = np.load(os.path.join(path, "pos0.npy"))
            radius = np.load(os.path.join(path, "radius.npy"))
            v_pref = np.load(os.path.join(path, "v_pref.npy"))
            seeds = np.load(os.path.join(path, "seeds.npy"))
        else:                                   # legacy single-file .npz
            z = np.load(path)
            vel, pos0 = z["vel"], z["pos0"]
            radius, v_pref, seeds = z["radius"], z["v_pref"], z["seeds"]
        _POOL_CACHE[path] = {
            "vel": vel, "pos0": pos0, "radius": radius, "v_pref": v_pref,
            "seeds": seeds, "n": int(seeds.shape[0]),
            "by_seed": {int(v): i for i, v in enumerate(seeds)},
        }
    return _POOL_CACHE[path]


def _simulate_crowd(cfg, seed):
    """One open-loop crowd rollout. Returns (pos0, radius, v_pref, vel[T,n,2])."""
    assert not cfg.robot_visible, "open-loop crowd pool requires an invisible robot"
    env = CrowdNavAblationEnv(_dc_replace(cfg, crowd_pool_path=None))
    env.reset(seed=int(seed))
    T, n, dt = env.max_steps, cfg.n_humans, cfg.time_step
    pos0 = env.human_pos.copy()
    vel = np.zeros((T, n, 2), dtype=np.float64)
    for t in range(T):
        v = env._orca_step()
        vel[t] = v
        env.human_pos = env.human_pos + v * dt
        env.human_vel = v
        env._respawn_human_goals()
    return pos0, env.human_radius.copy(), env.human_v_pref.copy(), vel


def _pool_worker(args):
    return _simulate_crowd(args[0], args[1])


def build_crowd_pool(cfg, seeds, path, n_workers=None, chunksize=16, verbose=True):
    """Precompute and save the crowd rollouts for `seeds`. One-time cost."""
    import multiprocessing as mp, time as _time
    seeds = [int(s) for s in seeds]
    cfg = _dc_replace(cfg, crowd_pool_path=None)
    n_workers = n_workers or (os.cpu_count() or 4)
    t0 = _time.time()
    if n_workers > 1:
        with mp.get_context("spawn").Pool(n_workers) as pool:
            out = pool.map(_pool_worker, [(cfg, s) for s in seeds], chunksize=chunksize)
    else:
        out = [_simulate_crowd(cfg, s) for s in seeds]
    pos0 = np.stack([o[0] for o in out]).astype(np.float64)
    radius = np.stack([o[1] for o in out]).astype(np.float64)
    v_pref = np.stack([o[2] for o in out]).astype(np.float64)
    vel = np.stack([o[3] for o in out]).astype(np.float64)
    os.makedirs(path, exist_ok=True)
    np.save(os.path.join(path, "seeds.npy"), np.asarray(seeds, dtype=np.int64))
    np.save(os.path.join(path, "pos0.npy"), pos0)
    np.save(os.path.join(path, "radius.npy"), radius)
    np.save(os.path.join(path, "v_pref.npy"), v_pref)
    np.save(os.path.join(path, "vel.npy"), vel)     # the big one; mmap-able
    if verbose:
        mb = sum(os.path.getsize(os.path.join(path, f))
                 for f in os.listdir(path)) / 1e6
        print(f"crowd pool: {len(seeds):,} scenarios, {vel.shape[1]} steps, "
              f"{mb:.0f} MB, built in {_time.time()-t0:.0f}s on {n_workers} workers "
              f"-> {path}")
    return path


# --------------------------------------------------------------------------- #
#  Environment
# --------------------------------------------------------------------------- #

class CrowdNavAblationEnv(gym.Env):
    metadata = {"render_modes": ["rgb_array"], "render_fps": 4}

    def __init__(self, cfg: EnvConfig = None, render_mode=None):
        super().__init__()
        self.cfg = cfg if cfg is not None else EnvConfig()
        self.render_mode = render_mode
        c = self.cfg

        self.max_steps = int(round(c.time_limit / c.time_step))
        self.obs_dim = 5 + 7 * c.n_humans
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(self.obs_dim,), dtype=np.float32
        )
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(2,), dtype=np.float32)

        self._rng = np.random.default_rng(0)
        self.trajectory = []
        # Defined before the first reset so _orca_step / _respawn_human_goals are
        # safe to call on a freshly constructed env (the pool builder does this).
        self._crowd_vel = None
        self._scenario_index = -1

    # ---------------------------------------------------------------- reset --
    def reset(self, *, seed=None, options=None):
        super().reset(seed=seed)
        if seed is not None:
            self._rng = np.random.default_rng(seed)
        c = self.cfg
        rng = self._rng

        R = c.circle_radius
        # Robot: bottom of the circle, goal antipodal.
        self.robot_pos = np.array([0.0, -R], dtype=np.float64)
        self.robot_goal = np.array([0.0, R], dtype=np.float64)
        self.robot_vel = np.zeros(2, dtype=np.float64)
        self.robot_theta = math.pi / 2.0
        self.robot_radius = c.robot_radius

        # Humans on the circle with angular + radial jitter.
        n = c.n_humans
        pool = load_crowd_pool(c.crowd_pool_path) if c.crowd_pool_path else None
        if pool is not None:
            # Replay a precomputed rollout.  A seeded reset is addressed by seed
            # (deterministic -- this is what evaluation and the paired design
            # need); an unseeded reset samples the pool, which is how training
            # draws its scenario distribution.
            idx = pool["by_seed"].get(int(seed)) if seed is not None else None
            if idx is None:
                idx = int(rng.integers(pool["n"]))
            self._scenario_index = idx
            self._crowd_vel = np.asarray(pool["vel"][idx], dtype=np.float64)
            self.human_pos = np.array(pool["pos0"][idx], dtype=np.float64)
            self.human_radius = np.array(pool["radius"][idx], dtype=np.float64)
            self.human_v_pref = np.array(pool["v_pref"][idx], dtype=np.float64)
            self.human_vel = np.zeros((n, 2))
            self.human_goal = -self.human_pos.copy()
        else:
            self._scenario_index = -1
            self._crowd_vel = None
            self._spawn_humans(rng, R, n)

        self.step_count = 0
        self.prev_action = np.zeros(2, dtype=np.float64)
        self._a_filt = np.zeros(2, dtype=np.float64)
        self.prev_dist_to_goal = float(np.linalg.norm(self.robot_pos - self.robot_goal))
        self.start_pos = self.robot_pos.copy()
        self.straight_line_dist = self.prev_dist_to_goal

        # episodic metric accumulators
        self._path_length = 0.0
        self._intrusion_steps = 0
        self._intrusion_count = 0
        self._sq_accel_sum = 0.0
        self._min_sep = math.inf
        self._prev_robot_vel = np.zeros(2)
        # behavioural instrumentation -- these are the quantities the mechanism
        # analysis needs and they cost one dot product per step.
        self._act_sum = np.zeros(2)        # sum a_t
        self._act_sq_sum = np.zeros(2)     # sum a_t^2
        self._act_lag_sum = np.zeros(2)    # sum a_t * a_{t-1}
        self._act_n_lag = 0
        self._speed_sum = 0.0
        self._progress_sum = 0.0           # sum of (d_t - d_{t+1}), signed
        self._abs_progress_sum = 0.0
        self._reward_breakdown = {k: 0.0 for k in
                                  ("goal", "dist", "space", "ttc", "jerk",
                                   "collision", "step")}
        self.trajectory = [self._snapshot()] if c.record_trajectory else []

        return self._observe(), {}


    def _spawn_humans(self, rng, R, n):
        """Rejection-sampled spawn on the circle (live path; also used to build
        the crowd pool)."""
        c = self.cfg
        base_angles = rng.uniform(0.0, 2.0 * math.pi, size=n)
        self.human_pos = np.zeros((n, 2))
        self.human_goal = np.zeros((n, 2))
        self.human_vel = np.zeros((n, 2))
        self.human_radius = rng.uniform(*c.human_radius_range, size=n)
        self.human_v_pref = rng.uniform(*c.human_v_pref_range, size=n)
        for i in range(n):
            for _ in range(100):                       # rejection-sample spawns
                ang = base_angles[i] + rng.uniform(-0.5, 0.5)
                px = R * math.cos(ang) + rng.uniform(-c.position_noise, c.position_noise)
                py = R * math.sin(ang) + rng.uniform(-c.position_noise, c.position_noise)
                ok = True
                for j in range(i):
                    min_d = self.human_radius[i] + self.human_radius[j] + 0.3
                    if math.hypot(px - self.human_pos[j, 0], py - self.human_pos[j, 1]) < min_d:
                        ok = False
                        break
                if ok:
                    d_rob = math.hypot(px - self.robot_pos[0], py - self.robot_pos[1])
                    if d_rob < self.human_radius[i] + self.robot_radius + 0.4:
                        ok = False
                if ok:
                    break
            self.human_pos[i] = (px, py)
            self.human_goal[i] = (-px, -py)

    # ----------------------------------------------------------------- step --
    def step(self, action):
        c = self.cfg
        action = np.clip(np.asarray(action, dtype=np.float64).reshape(2), -1.0, 1.0)

        # ---- 0. optional env-side action low-pass (mechanism control) --------
        # Applied BEFORE anything else, so the filtered action is what drives the
        # dynamics AND what the jerk term (if active) sees.  alpha = 0 is a
        # no-op and is asserted bit-identical to the unfiltered env in section 4.
        if c.action_filter_alpha > 0.0:
            self._a_filt = ((1.0 - c.action_filter_alpha) * action
                            + c.action_filter_alpha * self._a_filt)
            action = self._a_filt

        # ---- 1. humans act first (ORCA), robot optionally visible to them ----
        human_new_vel = self._orca_step()

        # ---- 2. robot action -> velocity -------------------------------------
        if c.kinematics == "holonomic":
            v = action * c.v_pref
            if c.action_frame == "goal_aligned":
                # Actions live in the SAME goal-aligned egocentric frame as the
                # observation: a = (forward-to-goal, left-of-goal-bearing).
                dgv = self.robot_goal - self.robot_pos
                ang = math.atan2(dgv[1], dgv[0])
                ca, sa = math.cos(ang), math.sin(ang)
                v = np.array([ca * v[0] - sa * v[1], sa * v[0] + ca * v[1]])
            speed = float(np.linalg.norm(v))
            if speed > c.v_pref:
                v = v / speed * c.v_pref
            new_theta = math.atan2(v[1], v[0]) if speed > 1e-6 else self.robot_theta
        else:  # unicycle
            lin = (action[0] + 1.0) * 0.5 * c.v_pref
            ang = action[1] * c.omega_max
            new_theta = self.robot_theta + ang * c.time_step
            v = np.array([lin * math.cos(new_theta), lin * math.sin(new_theta)])
        robot_new_vel = v

        # ---- 3. collision / separation over the whole timestep --------------
        dt = c.time_step
        rel_pos = self.human_pos - self.robot_pos                  # (n, 2)
        rel_vel = human_new_vel - robot_new_vel                    # (n, 2)
        comb_r = self.robot_radius + self.human_radius             # (n,)
        seps = _seg_dist_to_origin(rel_pos, rel_pos + rel_vel * dt) - comb_r
        collision = bool(np.any(seps < 0.0))
        min_sep_step = float(seps.min())
        self._min_sep = min(self._min_sep, min_sep_step)

        # ---- 3b. proxemic bookkeeping (ALWAYS measured, even when R3 is off) -
        d_surf_now = np.linalg.norm(rel_pos, axis=1) - comb_r      # (n,)
        n_intruding = int(np.count_nonzero(d_surf_now < c.r_comfort))
        if n_intruding > 0:
            self._intrusion_steps += 1
            self._intrusion_count += n_intruding

        # ---- 4. resolve TERMINATION BEFORE computing the reward -------------
        # The potential-based shaping term needs to know whether s' is terminal
        # (Ng et al. 1999 requires Phi(terminal) = 0), so the episode outcome
        # must be resolved first.  Note `truncated` is deliberately NOT terminal:
        # the time limit is not part of the MDP, and SB3 bootstraps the value
        # there, so zeroing the potential at a timeout would be wrong.
        next_pos = self.robot_pos + robot_new_vel * dt
        dist_next = float(np.linalg.norm(next_pos - self.robot_goal))
        success = bool(dist_next < c.goal_tolerance)
        terminated = bool(collision or success)
        truncated = bool((not terminated) and (self.step_count + 1) >= self.max_steps)

        # ---- 5. reward -------------------------------------------------------
        reward, parts = self._compute_reward(
            action, robot_new_vel, human_new_vel, collision, success,
            terminated, dist_next, rel_pos, rel_vel, comb_r, d_surf_now
        )

        # ---- 6. integrate ----------------------------------------------------
        self.robot_pos = next_pos
        self.robot_vel = robot_new_vel
        self.robot_theta = new_theta
        self.human_pos = self.human_pos + human_new_vel * dt
        self.human_vel = human_new_vel
        self._respawn_human_goals()

        self._path_length += float(np.linalg.norm(robot_new_vel)) * dt
        self._sq_accel_sum += float(
            np.sum(((robot_new_vel - self._prev_robot_vel) / dt) ** 2)
        )
        self._prev_robot_vel = robot_new_vel.copy()
        # behavioural instrumentation (cheap; used by the mechanism analysis)
        if self.step_count > 0:
            self._act_lag_sum += action * self.prev_action
            self._act_n_lag += 1
        self._act_sum += action
        self._act_sq_sum += action * action
        self._speed_sum += float(np.linalg.norm(robot_new_vel))
        self._progress_sum += (self.prev_dist_to_goal - dist_next)
        self._abs_progress_sum += abs(self.prev_dist_to_goal - dist_next)

        self.prev_action = action.copy()
        self.step_count += 1
        self.prev_dist_to_goal = dist_next

        info = {"reward_parts": parts} if c.emit_reward_parts else {}
        if terminated or truncated:
            info["episode_metrics"] = self._episode_metrics(success, collision, truncated)

        if c.record_trajectory:
            self.trajectory.append(self._snapshot())
        return self._observe(), float(reward), terminated, truncated, info

    # --------------------------------------------------------------- reward --
    def _compute_reward(self, action, robot_vel, human_vel, collision, success,
                        terminated, dist_next,
                        rel_pos=None, rel_vel=None, comb_r=None, d_surf=None):
        c = self.cfg
        parts = {"goal": 0.0, "dist": 0.0, "space": 0.0,
                 "ttc": 0.0, "jerk": 0.0, "collision": 0.0, "step": 0.0}

        # --- task-level time cost: every step, every arm, never ablated ------
        parts["step"] = c.r_step

        # --- R1: terminal goal bonus -----------------------------------------
        if success and c.use_goal:
            parts["goal"] = c.w_goal

        # --- collision penalty: part of the TASK, identical in every config ---
        if collision:
            parts["collision"] = c.r_collision

        # --- R2: distance shaping --------------------------------------------
        if c.use_dist:
            L = c.potential_scale
            phi_s = -self.prev_dist_to_goal / L
            if c.dist_mode == "pbrs":
                # Ng, Harada & Russell (1999): policy invariance holds ONLY if
                # Phi(s') = 0 for terminal s'.  Omitting this is not a harmless
                # approximation -- it silently converts the shaping term into an
                # ordinary (non-invariant) reward that leaks a pseudo goal bonus
                # and destabilises the value function at episode boundaries.
                phi_s_next = 0.0 if terminated else -dist_next / L
                parts["dist"] = c.w_dist * (c.gamma * phi_s_next - phi_s)
            else:
                # 'progress': the undiscounted per-step distance reduction used
                # by most crowd-navigation papers.  Equivalent to PBRS with a
                # shaping discount of 1.0, hence NOT policy-invariant: it really
                # does add goal-directedness rather than only accelerating it.
                parts["dist"] = c.w_dist * (self.prev_dist_to_goal - dist_next) / L

        # --- R3: personal-space (proxemic) penalty ---------------------------
        # --- R4: time-to-collision penalty -----------------------------------
        if c.use_space or c.use_ttc:
            if rel_pos is None:                       # stand-alone call (audit)
                rel_pos = self.human_pos - self.robot_pos
                rel_vel = human_vel - robot_vel
                comb_r = self.robot_radius + self.human_radius
                d_surf = np.linalg.norm(rel_pos, axis=1) - comb_r
            space_pen = 0.0
            ttc_pen = 0.0
            if c.use_space:
                near = d_surf < c.r_comfort
                if np.any(near):
                    space_pen = float(np.sum(
                        (c.r_comfort - np.clip(d_surf[near], 0.0, None)) ** 2))
            if c.use_ttc:
                taus = _ttc_vec(rel_pos, rel_vel, comb_r)
                hot = taus < c.ttc_threshold
                if np.any(hot):
                    ttc_pen = float(np.sum(
                        1.0 / (taus[hot] + c.ttc_epsilon)
                        - 1.0 / (c.ttc_threshold + c.ttc_epsilon)))
            if c.use_space:
                parts["space"] = -c.w_space * space_pen
            if c.use_ttc:
                parts["ttc"] = -c.w_ttc * ttc_pen

        # --- R5: jerk / action-smoothness penalty ----------------------------
        if c.use_jerk:
            parts["jerk"] = -c.w_jerk * float(np.sum((action - self.prev_action) ** 2))

        for k, v in parts.items():
            self._reward_breakdown[k] += v
        return sum(parts.values()), parts

    # ----------------------------------------------------------------- ORCA --
    def _orca_step(self):
        c = self.cfg
        n = c.n_humans
        if self._crowd_vel is not None:          # replay a precomputed rollout
            t = min(self.step_count, self._crowd_vel.shape[0] - 1)
            return self._crowd_vel[t]
        new_vel = np.zeros((n, 2))

        agents = [(tuple(self.human_pos[i]), tuple(self.human_vel[i]),
                   float(self.human_radius[i])) for i in range(n)]
        robot_agent = (tuple(self.robot_pos), tuple(self.robot_vel), self.robot_radius)

        for i in range(n):
            to_goal = self.human_goal[i] - self.human_pos[i]
            d = float(np.linalg.norm(to_goal))
            if d > 1e-6:
                pref = tuple(to_goal / d * min(self.human_v_pref[i], d / c.time_step))
            else:
                pref = (0.0, 0.0)

            neighbours = [agents[j] for j in range(n) if j != i]
            if c.robot_visible:
                neighbours.append(robot_agent)

            new_vel[i] = orca_velocity(
                pos=agents[i][0], vel=agents[i][1], radius=agents[i][2],
                pref_vel=pref, max_speed=float(self.human_v_pref[i]),
                neighbours=neighbours,
                time_horizon=c.orca_time_horizon, time_step=c.time_step,
                neighbour_dist=c.orca_neighbour_dist,
            )
        return new_vel

    def _respawn_human_goals(self):
        c = self.cfg
        if self._crowd_vel is not None:
            return                              # goals only feed ORCA
        for i in range(c.n_humans):
            if np.linalg.norm(self.human_pos[i] - self.human_goal[i]) < c.human_goal_tolerance:
                self.human_goal[i] = -self.human_pos[i]

    # ---------------------------------------------------------- observation --
    def _observe(self):
        """Robot-centric, goal-aligned observation (the 'rotate' transform of SARL)."""
        c = self.cfg
        dgv = self.robot_goal - self.robot_pos
        dg = float(np.linalg.norm(dgv))
        ang = math.atan2(dgv[1], dgv[0])
        ca, sa = math.cos(-ang), math.sin(-ang)
        rot = np.array([[ca, -sa], [sa, ca]])

        vr = rot @ self.robot_vel
        obs = [dg / c.pos_scale, c.v_pref / c.vel_scale, self.robot_radius,
               vr[0] / c.vel_scale, vr[1] / c.vel_scale]

        d = self.human_pos - self.robot_pos                        # (n, 2)
        da = np.linalg.norm(d, axis=1)                             # (n,)
        order = np.argsort(da, kind="stable")      # nearest first (permutation-stable)
        rel = d[order] @ rot.T
        hv = self.human_vel[order] @ rot.T
        da_s = da[order]
        hr = self.human_radius[order]
        block = np.empty((c.n_humans, 7))
        block[:, 0] = rel[:, 0] / c.pos_scale
        block[:, 1] = rel[:, 1] / c.pos_scale
        block[:, 2] = hv[:, 0] / c.vel_scale
        block[:, 3] = hv[:, 1] / c.vel_scale
        block[:, 4] = hr
        block[:, 5] = da_s / c.pos_scale
        block[:, 6] = (da_s - self.robot_radius - hr) / c.pos_scale
        return np.concatenate([np.asarray(obs), block.ravel()]).astype(np.float32)

    # ---------------------------------------------------------- bookkeeping --
    def _snapshot(self):
        return {
            "robot": self.robot_pos.copy(),
            "humans": self.human_pos.copy(),
            "hr": self.human_radius.copy(),
            "goal": self.robot_goal.copy(),
        }

    def _episode_metrics(self, success, collision, truncated):
        c = self.cfg
        T = max(self.step_count, 1)
        # lag-1 action autocorrelation, averaged over the two action dimensions.
        # This is the direct measurement of "temporal action coherence" -- the
        # quantity the jerk penalty is hypothesised to buy.
        if self._act_n_lag > 0:
            mu = self._act_sum / T
            var = self._act_sq_sum / T - mu * mu
            cov = self._act_lag_sum / self._act_n_lag - mu * mu
            with np.errstate(divide="ignore", invalid="ignore"):
                ac = np.where(var > 1e-9, cov / np.where(var > 1e-9, var, 1.0), 0.0)
            action_autocorr = float(np.mean(np.clip(ac, -1.0, 1.0)))
        else:
            action_autocorr = 0.0
        net_disp = float(np.linalg.norm(self.robot_pos - self.start_pos))
        return {
            "action_autocorr": action_autocorr,
            "mean_speed": self._speed_sum / T,
            # net displacement per metre of path walked: 1.0 = perfectly
            # directed, ~0 = walked a lot and went nowhere (the failure signature
            # of an incoherent policy).
            "displacement_efficiency": net_disp / max(self._path_length, 1e-6),
            "net_progress_per_step": self._progress_sum / T,
            "success": float(success),
            "collision": float(collision),
            "timeout": float(truncated),
            "nav_time": self.step_count * c.time_step,
            "path_length": self._path_length,
            "path_length_ratio": self._path_length / max(self.straight_line_dist, 1e-6),
            "intrusion_steps": float(self._intrusion_steps),
            "intrusion_count": float(self._intrusion_count),
            "intrusion_rate": self._intrusion_steps / T,
            "mean_sq_accel": self._sq_accel_sum / T,
            "min_separation": float(self._min_sep),
            "steps": T,
            **{f"rew_{k}": v for k, v in self._reward_breakdown.items()},
        }


# --------------------------------------------------------------------------- #
#  Ablation configuration table
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
#  Ablation configuration table -- the COMPLETE 2^5 factorial lattice
# --------------------------------------------------------------------------- #
#  Leave-one-out answers "what does component i add ON TOP OF the other four?".
#  That single number is context-dependent and, as v4 showed, can be wildly
#  misleading: R5's leave-one-out effect was -0.95 success while its add-one-in
#  effect was ~0.00.  Both are true; neither alone is "the effect of R5".
#
#  Enumerating all 2^5 = 32 subsets removes the choice of context entirely.  From
#  the full lattice we can compute, EXACTLY and without any modelling assumption:
#    * the Shapley value of each component (its average marginal contribution
#      over all 2^4 = 16 contexts, weighted so the values sum to v(full)-v(none)),
#    * the Moebius / Harsanyi decomposition, i.e. every pairwise, triple, ... 
#      interaction term, which is what tells substitutes from complements,
#    * leave-one-out and add-one-in as two special cases of the same object.
#
#  Component order is fixed: (goal R1, dist R2, space R3, ttc R4, jerk R5).

COMPONENT_IDS   = ("R1", "R2", "R3", "R4", "R5")
COMPONENT_KEYS  = ("goal", "dist", "space", "ttc", "jerk")
COMPONENT_NAMES = ("goal reaching", "distance shaping", "personal space",
                   "time-to-collision", "jerk / smoothness")


def lattice_name(bits):
    """(1,1,0,0,1) -> 'R125';  (0,0,0,0,0) -> 'R0_none'."""
    act = "".join(str(i + 1) for i, b in enumerate(bits) if b)
    return f"R{act}" if act else "R0_none"


def lattice_bits(name):
    """Inverse of lattice_name for pure lattice arms; None otherwise."""
    if name == "R0_none":
        return (False,) * 5
    if not (name.startswith("R") and name[1:].isdigit()):
        return None
    on = set(int(ch) for ch in name[1:])
    return tuple((i + 1) in on for i in range(5))


# The 32 lattice arms, ordered by descending component count then by index, so
# the reference sits first and the empty arm last.
LATTICE = [tuple(bool(k >> i & 1) for i in range(5)) for k in range(32)]
LATTICE.sort(key=lambda b: (-sum(b), [not x for x in b]))

ABLATION_CONFIGS = {lattice_name(b): b for b in LATTICE}

# Two extra arms that are NOT lattice members: they keep the same component set
# but swap the FORM of R2 from potential-based (policy-invariant) shaping to the
# naive per-step progress reward used by most crowd-navigation papers.  They are
# excluded from the Shapley computation by construction and analysed separately.
ABLATION_CONFIGS["P12345_progress"] = (True,  True, True, True, True)
ABLATION_CONFIGS["P2345_progress"]  = (False, True, True, True, True)

ARM_ENV_OVERRIDES = {
    "P12345_progress": {"dist_mode": "progress"},
    "P2345_progress":  {"dist_mode": "progress"},
}

# Human-readable aliases for the arms the classical leave-one-out table reports.
# These are LABELS ONLY -- `make_cfg` resolves them to the lattice arm.
ALIASES = {
    "R12345":     "R1-5_full",
    "R2345":      "A1_no-goal",
    "R1345":      "A2_no-distance",
    "R1245":      "A3_no-space",
    "R1235":      "A4_no-ttc",
    "R1234":      "A5_no-jerk",
    "R1":         "B1_goal-only",
    "R12":        "B2_goal+dist",
    "R125":       "B3_goal+dist+jerk",
    "R123":       "B4_goal+dist+space",
    "R124":       "B5_goal+dist+ttc",
    "R1245_":     "",                       # placeholder, unused
    "R2":         "B6_dist-only",
    "R25":        "B7_dist+jerk",
    "R0_none":    "Z_task-only",
    "R1245":      "A3_no-space",
    "R12345_":    "",
    "P12345_progress": "C1_progress-dist",
    "P2345_progress":  "C2_no-goal_progress",
}
ALIASES = {k: v for k, v in ALIASES.items() if v}

# Canonical leave-one-out family, in the order the main table reports them.
LOO_ARMS = ["R12345", "R2345", "R1345", "R1245", "R1235", "R1234"]
# Canonical add-one-in family (task-only plus a single component).
AOI_ARMS = ["R0_none", "R1", "R2", "R3", "R4", "R5"]


def display_name(name):
    """'R1234' -> 'A5_no-jerk (R1234)'.  Falls back to the raw lattice name."""
    a = ALIASES.get(name)
    return f"{a} [{name}]" if a else name


_ALIAS_TO_LATTICE = {v: k for k, v in ALIASES.items()}


def resolve_arm(name):
    """Accept a lattice name ('R1234'), an alias ('A5_no-jerk') or an alias with
    the lattice name attached ('A5_no-jerk [R1234]')."""
    if name in ABLATION_CONFIGS:
        return name
    if name in _ALIAS_TO_LATTICE:
        return _ALIAS_TO_LATTICE[name]
    if "[" in name and name.endswith("]"):
        inner = name[name.index("[") + 1:-1]
        if inner in ABLATION_CONFIGS:
            return inner
    raise KeyError(f"unknown ablation arm: {name!r}")


def make_cfg(name, **overrides):
    name = resolve_arm(name)
    g, d, s, t, j = ABLATION_CONFIGS[name]
    cfg = EnvConfig(use_goal=g, use_dist=d, use_space=s, use_ttc=t, use_jerk=j)
    for k, v in {**overrides, **ARM_ENV_OVERRIDES.get(name, {})}.items():
        setattr(cfg, k, v)
    return cfg


# --------------------------------------------------------------------------- #
#  Non-learning reference policies (reported as baselines alongside PPO)
# --------------------------------------------------------------------------- #

def _to_action(env, v_world):
    """World-frame velocity -> the env's normalised action."""
    c = env.cfg
    if c.kinematics == "holonomic" and c.action_frame == "goal_aligned":
        dgv = env.robot_goal - env.robot_pos
        ang = math.atan2(dgv[1], dgv[0])
        ca, sa = math.cos(-ang), math.sin(-ang)
        v_world = np.array([ca * v_world[0] - sa * v_world[1],
                            sa * v_world[0] + ca * v_world[1]])
    return np.clip(np.asarray(v_world) / c.v_pref, -1.0, 1.0)


def orca_robot_action(env, responsibility=1.0, safety_space=0.15):
    """ORCA planner driving the robot.

    `responsibility=1.0` because the humans cannot see the robot in the
    invisible-robot setting and will not yield.  `safety_space` inflates the
    robot radius: vanilla ORCA plans to graze at exactly zero separation, which
    discrete-time integration then turns into a collision (the same trick is
    used by the ORCA baseline in Chen et al.'s CrowdNav)."""
    c = env.cfg
    to_goal = env.robot_goal - env.robot_pos
    d = float(np.linalg.norm(to_goal))
    pref = tuple(to_goal / d * min(c.v_pref, d / c.time_step)) if d > 1e-6 else (0.0, 0.0)
    neigh = [(tuple(env.human_pos[i]), tuple(env.human_vel[i]), float(env.human_radius[i]))
             for i in range(c.n_humans)]
    v = orca_velocity(pos=tuple(env.robot_pos), vel=tuple(env.robot_vel),
                      radius=env.robot_radius + safety_space,
                      pref_vel=pref, max_speed=c.v_pref,
                      neighbours=neigh, time_horizon=c.orca_time_horizon,
                      time_step=c.time_step, neighbour_dist=c.orca_neighbour_dist,
                      responsibility=responsibility)
    return _to_action(env, np.asarray(v))


def straight_line_action(env):
    return _to_action(env, (env.robot_goal - env.robot_pos) /
                      max(float(np.linalg.norm(env.robot_goal - env.robot_pos)), 1e-6)
                      * env.cfg.v_pref)


def run_baseline(policy_fn, cfg, seeds):
    """Roll out a state-based (non-neural) policy over a fixed seed list."""
    import pandas as pd
    env = CrowdNavAblationEnv(cfg)
    recs = []
    for s in seeds:
        env.reset(seed=int(s))
        ret = 0.0
        while True:
            _, r, term, trunc, info = env.step(policy_fn(env))
            ret += r
            if term or trunc:
                rec = dict(info["episode_metrics"])
                rec["scenario_seed"] = int(s)
                rec["ep_return"] = ret
                recs.append(rec)
                break
    return pd.DataFrame(recs)

Writing crowd_env.py

## 2 · Training, evaluation, statistics and plotting modules

Written to files rather than left in notebook globals so that every object is importable by worker processes under any multiprocessing start method — the single most common cause of parallel-training failures in notebooks.

Three modules:

- **`rl_utils.py`** — PPO training, deterministic evaluation on a fixed shared test set, training-health diagnostics, ONNX export, run-level parallelism, and the new **`Budget`** scheduler that sizes every stage from measured throughput against a hard deadline.
- **`ablation_stats.py`** *(new)* — the cooperative-game analysis: Möbius transform, Shapley values, Shapley interaction indices, exact sign-flip permutation tests, hierarchical bootstrap, TOST equivalence tests, Cliff's $\delta$, Holm–Bonferroni.
- **`viz.py`** — publication figures, including the new attribution, interaction-heatmap, lattice-landscape, dose–response, density and mechanism plots.

In [4]:
%%writefile rl_utils.py
"""
Training / evaluation / statistics utilities for the crowd-navigation reward
ablation.  Kept in a module (rather than notebook globals) so that every object
is importable by SubprocVecEnv worker processes under any multiprocessing
start method.
"""
import os, json, time, random, math
from collections import deque

import numpy as np
import pandas as pd
import gymnasium as gym

import torch as th
import torch.nn as nn
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import BaseCallback
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv

from crowd_env import (CrowdNavAblationEnv, make_cfg, ABLATION_CONFIGS,
                       orca_robot_action, resolve_arm, display_name)

METRIC_KEYS = [
    "success", "collision", "timeout", "nav_time", "path_length_ratio",
    "intrusion_steps", "intrusion_count", "intrusion_rate",
    "mean_sq_accel", "min_separation",
    # behavioural instrumentation -- these are what the mechanism analysis in
    # section 13 runs on.  action_autocorr is the direct measurement of the
    # temporal action coherence that R5 is hypothesised to supply;
    # displacement_efficiency separates "went nowhere" from "took a long route".
    "action_autocorr", "mean_speed", "displacement_efficiency",
    "net_progress_per_step",
]


# --------------------------------------------------------------------------- #
#  Reproducibility
# --------------------------------------------------------------------------- #
def set_global_seeds(seed: int, deterministic_torch: bool = True):
    random.seed(seed)
    np.random.seed(seed)
    th.manual_seed(seed)
    if th.cuda.is_available():
        th.cuda.manual_seed_all(seed)
    if deterministic_torch:
        th.backends.cudnn.deterministic = True
        th.backends.cudnn.benchmark = False
    os.environ["PYTHONHASHSEED"] = str(seed)


# --------------------------------------------------------------------------- #
#  Callback: harvest per-episode metrics from the vectorised envs
# --------------------------------------------------------------------------- #
class EpisodeMetricsCallback(BaseCallback):
    def __init__(self, csv_path: str, rollout_csv_path: str = None,
                 window: int = 200, verbose: int = 0):
        super().__init__(verbose)
        self.csv_path = csv_path
        self.rollout_csv_path = rollout_csv_path
        self.rows = []
        self.rollout_rows = []
        self._buf = deque(maxlen=window)

    def _on_step(self) -> bool:
        for info in self.locals.get("infos", []):
            m = info.get("episode_metrics")
            if m is not None:
                self.rows.append({"timesteps": int(self.num_timesteps), **m})
                self._buf.append(m)
        return True

    def _on_rollout_end(self) -> None:
        # Policy standard deviation is the single most diagnostic scalar for the
        # exploration-collapse / exploration-runaway failure modes.  Logging it
        # per rollout makes those failures visible instead of inferable.
        try:
            std = float(th.exp(self.model.policy.log_std.detach()).mean().item())
        except Exception:
            std = float("nan")
        self.logger.record("crowdnav/policy_std", std)

        row = {"timesteps": int(self.num_timesteps), "policy_std": std,
               "n_episodes_in_window": len(self._buf)}
        for k in METRIC_KEYS:
            vals = [b[k] for b in self._buf if np.isfinite(b[k])]
            if vals:
                m = float(np.mean(vals))
                self.logger.record(f"crowdnav/{k}", m)
                row[k] = m
        self.rollout_rows.append(row)

    def _on_training_end(self) -> None:
        self.flush()

    def flush(self):
        if self.rows:
            os.makedirs(os.path.dirname(self.csv_path), exist_ok=True)
            pd.DataFrame(self.rows).to_csv(self.csv_path, index=False)
        if self.rollout_rows and self.rollout_csv_path:
            pd.DataFrame(self.rollout_rows).to_csv(self.rollout_csv_path, index=False)


# --------------------------------------------------------------------------- #
#  Training
# --------------------------------------------------------------------------- #
def pick_device(requested="auto"):
    """MlpPolicy inference on a 40-D observation is launch-latency bound: the
    CPU->GPU->CPU round trip per rollout step costs more than the matmul saves.
    SB3 warns about exactly this.  'auto' therefore means CPU here."""
    if requested != "auto":
        return requested
    return "cpu"


def linear_schedule(initial: float, final_frac: float = 0.05):
    """PPO learning-rate schedule: `progress_remaining` goes 1 -> 0.

    Decaying the step size is the single cheapest way to buy a sharper final
    deterministic policy out of a fixed step budget, and it is applied
    identically to every arm so it cannot bias the ablation.  It matters more
    here than usual because the headline metric is evaluated with
    `deterministic=True`, which reads the MEAN of the action distribution: a
    policy still taking 3e-4 steps at the end of training has a mean that is
    still wandering.
    """
    class _LinearSchedule:
        """A callable with a readable repr, so the run's meta.json records the
        actual schedule rather than a memory address."""

        def __init__(self, initial, final_frac):
            self.initial, self.final_frac = float(initial), float(final_frac)

        def __call__(self, progress_remaining: float) -> float:
            return self.initial * (self.final_frac +
                                   (1.0 - self.final_frac) * progress_remaining)

        def __repr__(self):
            return (f"linear_schedule(initial={self.initial:g}, "
                    f"final={self.initial*self.final_frac:g})")

    return _LinearSchedule(initial, final_frac)


def default_ppo_kwargs(n_envs: int, gamma: float = 0.99, lr: float = 3e-4,
                       decay_lr: bool = True, net_width: int = 128):
    """Identical for every ablation configuration -- only the reward changes."""
    return dict(
        policy="MlpPolicy",
        learning_rate=linear_schedule(lr) if decay_lr else lr,
        n_steps=max(128, 4096 // n_envs),      # 4096-step rollout regardless of n_envs
        batch_size=512,
        n_epochs=10,
        gamma=gamma,
        gae_lambda=0.95,
        clip_range=0.2,
        # ent_coef MUST be 0 here.  A positive entropy bonus pushes log_std up
        # with a constant gradient (+2*ent_coef for a 2-D Gaussian).  The jerk
        # penalty is the only reward term that opposes it everywhere in the state
        # space -- E[-w_jerk*||a_t - a_{t-1}||^2] = -4*w_jerk*sigma^2 for i.i.d.
        # actions -- so with ent_coef>0 the jerk arms equilibrate at
        # sigma = sqrt(ent_coef / (4*w_jerk)) while the no-jerk arms have NOTHING
        # opposing the bonus and their sigma runs away.  That turns "ablate R5"
        # into "ablate entropy regularisation", which is a different experiment.
        ent_coef=0.0,
        vf_coef=0.5,
        max_grad_norm=0.5,
        # --- exploration -----------------------------------------------------
        # v3 enabled gSDE to give the no-jerk arms temporal coherence from the
        # ALGORITHM rather than from R5.  It did not work: A5 and B1 still scored
        # exactly 0.000, while mean_sq_accel went 2.15 -> 28.3 (A5), 0.69 -> 8.11
        # (B1) and 1.15 -> 27.5 (B2), and B2 collapsed from 0.753 to 0.000.  A
        # failed intervention that costs 40% of navigation speed everywhere is
        # not worth carrying, so v4 reverts to i.i.d. Gaussian exploration and
        # instead breaks the exploration/smoothness confound experimentally, with
        # the B3 arm and the gSDE x jerk grid (see the notebook).
        use_sde=False,
        # Guards against the late-training policy collapse that PPO exhibits once
        # a run starts reliably terminating episodes and the advantage scale
        # shifts.  Applied identically to every arm.
        target_kl=0.03,
        policy_kwargs=dict(
            net_arch=dict(pi=[net_width, net_width],
                          vf=[net_width, net_width]),
            activation_fn=nn.ReLU,
            log_std_init=-0.5,
            ortho_init=True,
        ),
    )


def train_one(config_name, seed, total_timesteps, n_envs, out_root,
              device="auto", env_overrides=None, verbose=0, net_width=128,
              run_tag=None):
    """Train a single (reward-configuration, seed) run. Returns a summary dict."""
    config_name = resolve_arm(config_name)
    run_id = f"{run_tag or config_name}__seed{seed}"
    run_dir = os.path.join(out_root, "runs", run_id)
    os.makedirs(run_dir, exist_ok=True)

    set_global_seeds(seed)
    # One torch thread per process.  With SubprocVecEnv workers already
    # saturating the vCPUs, letting torch spawn its own OMP pool for a tiny MLP
    # causes heavy context-switching: it was the main reason measured throughput
    # (1.1k steps/s) came in 5x under the env-only projection.
    th.set_num_threads(1)
    # Torch's own pool is not the only one: numpy/BLAS spawn theirs at import
    # time, which set_num_threads cannot reach.  The notebook sets the OMP_*
    # environment variables before the first import for that reason.
    cfg = make_cfg(config_name, **(env_overrides or {}))

    # DummyVecEnv, always.  SubprocVecEnv pickles a 40-float observation across
    # a pipe and synchronises on the slowest worker EVERY step; measured in v3 at
    # 1,254 steps/s against 3,850 steps/s for a single un-vectorised env, i.e.
    # four workers delivering one third of one env.  Stepping four envs in-process
    # costs 4x the env work and zero IPC, and parallelism is recovered at the RUN
    # level instead (train_many), where the sync barrier is one join per run.
    vec_cls = DummyVecEnv
    env = make_vec_env(
        CrowdNavAblationEnv,
        n_envs=n_envs,
        seed=seed,
        env_kwargs=dict(cfg=cfg),
        monitor_dir=os.path.join(run_dir, "monitor"),
        vec_env_cls=vec_cls,
    )

    ppo_kwargs = default_ppo_kwargs(n_envs, gamma=cfg.gamma, net_width=net_width)
    # The PBRS invariance guarantee (Ng et al., 1999) only holds when the
    # discount used to build the shaping term equals the agent's discount.
    assert abs(ppo_kwargs["gamma"] - cfg.gamma) < 1e-12

    # TensorBoard logging is a convenience, never a dependency.  SB3 raises at
    # construction time if `tensorboard_log` is set and the package is missing,
    # which would otherwise turn "pip could not reach the internet" into "the
    # entire sweep failed".  Per-run metrics are written to CSV regardless.
    try:
        import tensorboard  # noqa: F401
        _tb_log = os.path.join(out_root, "tb")
    except Exception:
        _tb_log = None
    model = PPO(env=env, seed=seed, device=pick_device(device), verbose=verbose,
                tensorboard_log=_tb_log, **ppo_kwargs)

    cb = EpisodeMetricsCallback(os.path.join(run_dir, "train_episodes.csv"),
                                os.path.join(run_dir, "train_rollouts.csv"))
    t0 = time.time()
    model.learn(total_timesteps=total_timesteps, callback=cb,
                tb_log_name=run_id, progress_bar=False)
    wall = time.time() - t0

    model.save(os.path.join(run_dir, "model"))
    env.close()

    # ppo_kwargs holds objects json cannot represent -- `learning_rate` is a
    # schedule CALLABLE and `policy_kwargs` contains a torch activation class.
    # Serialise defensively: anything not JSON-native becomes its repr.  Getting
    # this wrong is expensive rather than obvious, because model.save() has
    # already succeeded by this point, so the run leaves a usable model.zip next
    # to a TRUNCATED meta.json -- and the resume path then reads that truncated
    # file on the next attempt.
    def _jsonable(v):
        if isinstance(v, (str, int, float, bool)) or v is None:
            return v
        if isinstance(v, (list, tuple)):
            return [_jsonable(x) for x in v]
        if isinstance(v, dict):
            return {str(k): _jsonable(x) for k, x in v.items()}
        return repr(v)

    meta = dict(run_id=run_id, config=config_name, seed=int(seed),
                net_width=int(net_width),
                total_timesteps=int(total_timesteps), n_envs=int(n_envs),
                wall_seconds=round(wall, 1),
                fps=round(total_timesteps / max(wall, 1e-6), 1),
                ppo_kwargs={k: _jsonable(v) for k, v in ppo_kwargs.items()})
    # Write atomically so an interrupted session can never leave a half-written
    # meta.json for the resume path to choke on.
    _mp = os.path.join(run_dir, "meta.json")
    with open(_mp + ".tmp", "w") as f:
        json.dump(meta, f, indent=2)
    os.replace(_mp + ".tmp", _mp)
    return meta


# --------------------------------------------------------------------------- #
#  Deterministic evaluation on a FIXED, shared set of test scenarios
# --------------------------------------------------------------------------- #
class SeededEvalEnv(gym.Wrapper):
    """Replays a fixed list of scenario seeds, one per reset, cycling forever."""

    def __init__(self, env, seeds):
        super().__init__(env)
        self.seeds = [int(s) for s in seeds]
        self.i = 0

    def reset(self, **kwargs):
        s = self.seeds[self.i % len(self.seeds)]
        self.i += 1
        return self.env.reset(seed=s)


def evaluate_fixed(model, config_name, test_seeds, n_workers=8,
                   env_overrides=None, deterministic=True, max_iters=100000):
    """Evaluate a policy on exactly `test_seeds` scenarios.

    Every configuration and seed sees the *same* scenarios, which removes
    scenario sampling noise from the between-config comparison.
    """
    test_seeds = list(test_seeds)
    n_workers = max(1, min(n_workers, len(test_seeds)))
    chunks = [test_seeds[i::n_workers] for i in range(n_workers)]

    def _mk(ch):
        def _f():
            return SeededEvalEnv(
                CrowdNavAblationEnv(make_cfg(config_name, **(env_overrides or {}))), ch)
        return _f

    vec = DummyVecEnv([_mk(ch) for ch in chunks])
    obs = vec.reset()

    targets = [len(c) for c in chunks]
    done_counts = [0] * n_workers
    running_return = np.zeros(n_workers)
    records = []

    it = 0
    while any(done_counts[i] < targets[i] for i in range(n_workers)):
        actions, _ = model.predict(obs, deterministic=deterministic)
        obs, rewards, dones, infos = vec.step(actions)
        running_return += np.asarray(rewards, dtype=np.float64)
        for i, info in enumerate(infos):
            m = info.get("episode_metrics")
            if m is None:
                continue
            if done_counts[i] < targets[i]:
                rec = dict(m)
                rec["scenario_seed"] = chunks[i][done_counts[i]]
                rec["ep_return"] = float(running_return[i])
                records.append(rec)
                done_counts[i] += 1
            running_return[i] = 0.0
        it += 1
        if it > max_iters:
            break
    vec.close()
    return pd.DataFrame(records)


# --------------------------------------------------------------------------- #
#  Statistics
# --------------------------------------------------------------------------- #
def summarise_run(df: pd.DataFrame) -> dict:
    """Collapse per-episode evaluation records into one row for a run."""
    out = {}
    for k in METRIC_KEYS:
        if k not in df.columns:
            continue
        v = df[k].replace([np.inf, -np.inf], np.nan).dropna()
        out[k] = float(v.mean()) if len(v) else np.nan
    # Conditioning some metrics on successful episodes only is standard in the
    # crowd-navigation literature (nav-time / path-ratio are undefined otherwise).
    succ = df[df["success"] > 0.5]
    out["nav_time_succ"] = float(succ["nav_time"].mean()) if len(succ) else np.nan
    out["path_length_ratio_succ"] = float(succ["path_length_ratio"].mean()) if len(succ) else np.nan
    out["mean_sq_accel_succ"] = float(succ["mean_sq_accel"].mean()) if len(succ) else np.nan
    out["ep_return"] = float(df["ep_return"].mean()) if "ep_return" in df else np.nan
    out["n_episodes"] = int(len(df))
    return out


def aggregate_across_seeds(per_run: pd.DataFrame, metrics, alpha=0.05):
    """mean, sd and Student-t (1-alpha) CI half-width across training seeds."""
    from scipy import stats
    rows = []
    for cfg, g in per_run.groupby("config"):
        row = {"config": cfg, "n_seeds": len(g)}
        for m in metrics:
            v = g[m].replace([np.inf, -np.inf], np.nan).dropna().values
            n = len(v)
            mu = float(np.mean(v)) if n else np.nan
            sd = float(np.std(v, ddof=1)) if n > 1 else 0.0
            hw = (stats.t.ppf(1 - alpha / 2, n - 1) * sd / math.sqrt(n)) if n > 1 else np.nan
            row[f"{m}_mean"] = mu
            row[f"{m}_sd"] = sd
            row[f"{m}_ci95"] = hw
        rows.append(row)
    return pd.DataFrame(rows).sort_values("config").reset_index(drop=True)


def paired_tests(per_episode: pd.DataFrame, reference: str, metrics):
    """Compare each ablation against the reference config on the shared test set.

    Episodes are paired by scenario seed and pooled across training seeds, so a
    Wilcoxon signed-rank test on the per-scenario means is appropriate.
    """
    from scipy import stats
    ref = (per_episode[per_episode.config == reference]
           .groupby("scenario_seed")[metrics].mean())
    rows = []
    for cfg, g in per_episode.groupby("config"):
        if cfg == reference:
            continue
        cur = g.groupby("scenario_seed")[metrics].mean()
        idx = ref.index.intersection(cur.index)
        row = {"config": cfg, "reference": reference, "n_paired": len(idx)}
        for m in metrics:
            a = ref.loc[idx, m].values
            b = cur.loc[idx, m].values
            d = b - a
            row[f"{m}_delta"] = float(np.mean(d))
            if np.allclose(d, 0):
                row[f"{m}_p"] = 1.0
            else:
                try:
                    row[f"{m}_p"] = float(stats.wilcoxon(a, b, zero_method="zsplit").pvalue)
                except Exception:
                    row[f"{m}_p"] = np.nan
        rows.append(row)
    return pd.DataFrame(rows)


def holm_bonferroni(pvals):
    """Holm-Bonferroni step-down adjusted p-values."""
    p = np.asarray(pvals, dtype=float)
    n = len(p)
    order = np.argsort(p)
    adj = np.empty(n)
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, (n - rank) * p[idx])
        adj[idx] = min(1.0, running)
    return adj


# --------------------------------------------------------------------------- #
#  ONNX export (PPO / ActorCriticPolicy -- note: PPO has NO `.actor` attribute)
# --------------------------------------------------------------------------- #
class OnnxDeterministicPolicy(nn.Module):
    """Deterministic actor forward pass, stripped of value head and sampling."""

    def __init__(self, policy):
        super().__init__()
        self.policy = policy

    def forward(self, observation: th.Tensor) -> th.Tensor:
        features = self.policy.extract_features(observation)
        if isinstance(features, tuple):
            features = features[0]
        latent_pi = self.policy.mlp_extractor.forward_actor(features)
        mean_actions = self.policy.action_net(latent_pi)
        return th.clamp(mean_actions, -1.0, 1.0)


def export_onnx(model, path, obs_dim, opset=17):
    """Export the deterministic actor. Tries the TorchScript exporter first and
    falls back to the dynamo exporter on newer PyTorch builds."""
    model.policy.set_training_mode(False)
    wrapper = OnnxDeterministicPolicy(model.policy).to("cpu").eval()
    dummy = th.zeros(1, obs_dim, dtype=th.float32)
    kw = dict(opset_version=opset, input_names=["obs"], output_names=["action"],
              dynamic_axes={"obs": {0: "batch"}, "action": {0: "batch"}})
    try:
        th.onnx.export(wrapper, dummy, path, dynamo=False, **kw)
    except TypeError:
        th.onnx.export(wrapper, dummy, path, **kw)          # older PyTorch
    except Exception:
        th.onnx.export(wrapper, dummy, path, dynamo=True, **kw)
    return path


def verify_onnx(model, onnx_path, obs_dim, n=512, tol=1e-4, seed=0):
    """Numerical parity check: ONNX graph vs. SB3 `predict(deterministic=True)`."""
    import onnxruntime as ort
    rng = np.random.default_rng(seed)
    obs = rng.normal(0, 0.6, size=(n, obs_dim)).astype(np.float32)
    sb3_act, _ = model.predict(obs, deterministic=True)
    sess = ort.InferenceSession(onnx_path, providers=["CPUExecutionProvider"])
    onnx_act = sess.run(["action"], {"obs": obs})[0]
    err = float(np.max(np.abs(sb3_act - onnx_act)))
    return err, bool(err < tol)


def crossvalidate_orca(n_trials=200, n_agents=6, tol=2e-4, seed=0):
    """Compare the bundled pure-Python ORCA against the reference `python-rvo2`
    Cython bindings on random scenes.  Returns (max_abs_error, n_compared) or
    None when python-rvo2 is not installed."""
    try:
        import rvo2
    except Exception:
        return None
    from orca import orca_velocity
    rng = np.random.default_rng(seed)
    dt, horizon, ndist, maxn = 0.25, 5.0, 10.0, 10
    worst, count = 0.0, 0
    for _ in range(n_trials):
        pos = rng.uniform(-5, 5, size=(n_agents, 2))
        vel = rng.uniform(-1, 1, size=(n_agents, 2))
        rad = rng.uniform(0.3, 0.5, size=n_agents)
        pref = rng.uniform(-1, 1, size=(n_agents, 2))
        sim = rvo2.PyRVOSimulator(dt, ndist, maxn, horizon, horizon, 0.3, 1.0)
        ids = []
        for i in range(n_agents):
            a = sim.addAgent(tuple(pos[i]), ndist, maxn, horizon, horizon,
                             float(rad[i]), 1.0, tuple(vel[i]))
            sim.setAgentPrefVelocity(a, tuple(pref[i]))
            ids.append(a)
        sim.doStep()
        for i in range(n_agents):
            ref = np.asarray(sim.getAgentVelocity(ids[i]))
            neigh = [(tuple(pos[j]), tuple(vel[j]), float(rad[j]))
                     for j in range(n_agents) if j != i]
            mine = np.asarray(orca_velocity(
                tuple(pos[i]), tuple(vel[i]), float(rad[i]), tuple(pref[i]), 1.0,
                neigh, time_horizon=horizon, time_step=dt,
                neighbour_dist=ndist, max_neighbours=maxn, responsibility=0.5))
            worst = max(worst, float(np.max(np.abs(ref - mine))))
            count += 1
    return worst, count


# --------------------------------------------------------------------------- #
#  Training-health diagnostics
# --------------------------------------------------------------------------- #
def training_health(runs_root, configs, seeds, metric="success", tail_frac=0.15):
    """Detect late-training collapse and exploration runaway from the rollout logs.

    `peak` is the best windowed value reached at any point; `final` is the mean
    over the last `tail_frac` of training.  A large peak-to-final drop is the
    signature of PPO collapse -- it looks nothing like "never learned", which
    shows up as a flat low curve with peak ~ final.
    """
    rows = []
    for cfg in configs:
        for sd in seeds:
            f = os.path.join(runs_root, f"{cfg}__seed{sd}", "train_rollouts.csv")
            if not os.path.exists(f):
                continue
            df = pd.read_csv(f)
            if metric not in df or df.empty:
                continue
            v = df[metric].rolling(5, min_periods=1).mean().values
            k = max(1, int(len(v) * tail_frac))
            peak, final = float(np.nanmax(v)), float(np.nanmean(v[-k:]))
            std0 = float(df["policy_std"].iloc[0]) if "policy_std" in df else np.nan
            std1 = float(df["policy_std"].iloc[-1]) if "policy_std" in df else np.nan
            rows.append({
                "config": cfg, "seed": sd,
                f"{metric}_peak": peak, f"{metric}_final": final,
                "drop": peak - final,
                "collapsed": bool(peak > 0.25 and (peak - final) > 0.3 * peak),
                "policy_std_start": std0, "policy_std_end": std1,
                "std_ratio": (std1 / std0) if std0 and np.isfinite(std0) else np.nan,
                "runaway_exploration": bool(np.isfinite(std1) and np.isfinite(std0)
                                            and std1 > 1.5 * std0),
            })
    cols = ["config", "seed", f"{metric}_peak", f"{metric}_final", "drop", "collapsed",
            "policy_std_start", "policy_std_end", "std_ratio", "runaway_exploration"]
    return pd.DataFrame(rows) if rows else pd.DataFrame(columns=cols)


# --------------------------------------------------------------------------- #
#  Run-level parallelism
# --------------------------------------------------------------------------- #
def _train_worker(kw):
    """Module-level so it is picklable by the spawn start method."""
    import os as _os
    for v in ("OMP_NUM_THREADS", "MKL_NUM_THREADS", "OPENBLAS_NUM_THREADS"):
        _os.environ[v] = "1"
    return train_one(**kw)


def train_many(plan, total_timesteps, n_envs, out_root, device="auto",
               env_overrides=None, n_parallel=None, verbose=True,
               net_width=128, run_tag=None):
    """Train `plan` = [(config_name, seed), ...] with run-level parallelism.

    Each worker owns one PPO run and one in-process DummyVecEnv, so the only
    synchronisation in the whole sweep is a join per finished run.  Runs whose
    model.zip already exists are skipped, which is what makes the sweep
    resumable across Kaggle sessions.
    """
    import multiprocessing as mp, time as _time
    from concurrent.futures import ProcessPoolExecutor, as_completed

    n_parallel = n_parallel or max(1, (os.cpu_count() or 4))
    todo, meta = [], []
    for cfg_name, seed in plan:
        tag = run_tag or resolve_arm(cfg_name)
        run_dir = os.path.join(out_root, "runs", f"{tag}__seed{seed}")
        mpath = os.path.join(run_dir, "meta.json")
        if os.path.exists(os.path.join(run_dir, "model.zip")) and os.path.exists(mpath):
            try:
                meta.append(json.load(open(mpath)))
                if verbose:
                    print(f"SKIP (already trained) {cfg_name} seed={seed}")
                continue
            except Exception:
                # A corrupt meta.json means the previous attempt died between
                # saving the model and writing its metadata.  The model itself is
                # fine, so record what we know and keep the run rather than
                # retraining it or killing the sweep.
                meta.append({"run_id": f"{tag}__seed{seed}", "config": resolve_arm(cfg_name),
                             "seed": int(seed), "total_timesteps": int(total_timesteps),
                             "n_envs": int(n_envs), "net_width": int(net_width),
                             "wall_seconds": float("nan"), "fps": float("nan"),
                             "recovered_from_corrupt_meta": True})
                if verbose:
                    print(f"SKIP (already trained, meta recovered) {cfg_name} seed={seed}")
                continue
        todo.append(dict(config_name=cfg_name, seed=seed,
                         total_timesteps=total_timesteps, n_envs=n_envs,
                         out_root=out_root, device=device,
                         env_overrides=env_overrides, verbose=0,
                         net_width=net_width, run_tag=tag))
    if not todo:
        return meta

    t0 = _time.time()
    ctx = mp.get_context("spawn")
    with ProcessPoolExecutor(max_workers=n_parallel, mp_context=ctx) as ex:
        futs = {ex.submit(_train_worker, kw): kw for kw in todo}
        for i, fut in enumerate(as_completed(futs), 1):
            kw = futs[fut]
            try:
                m = fut.result()
                meta.append(m)
                if verbose:
                    el = _time.time() - t0
                    eta = el / i * (len(todo) - i) / 60
                    print(f"[{i:2d}/{len(todo)}] {m['config']:20s} seed={m['seed']}  "
                          f"{m['wall_seconds']/60:5.1f} min  {m['fps']:6.0f} fps   "
                          f"ETA {eta:5.1f} min")
            except Exception as e:                       # one bad run must not
                print(f"!! run failed: {kw['config_name']} "  # kill the sweep
                      f"seed={kw['seed']}: {type(e).__name__}: {e}")
    if verbose:
        print(f"\ntrained {len(todo)} runs in {(_time.time()-t0)/60:.1f} min "
              f"on {n_parallel} workers")
    return meta


# --------------------------------------------------------------------------- #
#  Reward-landscape audit  (no training required -- run this BEFORE training)
# --------------------------------------------------------------------------- #
def reward_landscape_audit(configs, seeds, env_overrides=None,
                           safety_space=0.45, n_episodes=120):
    """Compare the episode return of a COMPETENT reference policy against
    STANDING STILL, under each arm's own reward.

    A negative margin means the arm's global optimum is to freeze -- no amount
    of training or tuning will produce a navigating policy, because navigating
    is genuinely worse under that reward.  Finding this out in 30 seconds beats
    finding it out after a six-hour sweep.
    """
    competent = lambda e: orca_robot_action(e, 1.0, safety_space)
    freeze = lambda e: np.zeros(2)
    ep_seeds = list(seeds)[:n_episodes]
    rows = []
    for arm in configs:
        cfg = make_cfg(arm, **(env_overrides or {}))
        out = {}
        for label, pol in (("competent", competent), ("freeze", freeze)):
            rets, succ = [], []
            env = CrowdNavAblationEnv(cfg)
            for s in ep_seeds:
                env.reset(seed=int(s)); R = 0.0
                while True:
                    _, r, te, tu, info = env.step(pol(env))
                    R += r
                    if te or tu: break
                rets.append(R); succ.append(info["episode_metrics"]["success"])
            out[label] = float(np.mean(rets))
            out[label + "_success"] = float(np.mean(succ))
        rows.append({"config": arm, **out,
                     "margin": out["competent"] - out["freeze"],
                     "freeze_is_optimal": bool(out["competent"] <= out["freeze"])})
    return pd.DataFrame(rows)


def exploration_reachability(env_overrides=None, n_episodes=200, sigma=0.6):
    """How often does an UNTRAINED policy reach the goal region, as a function
    of the temporal correlation of its exploration noise?  This is what decides
    whether sparse-reward arms can bootstrap at all."""
    cfg = make_cfg("R1-5_full", **(env_overrides or {}))
    rows = []
    for label, tau in (("i.i.d. (tau=1)", 1), ("correlated tau=8", 8),
                       ("correlated tau=16", 16), ("correlated tau=50", 50)):
        rng = np.random.default_rng(1)
        env = CrowdNavAblationEnv(cfg)
        hit, disp, near = 0.0, [], []
        rho = math.exp(-1.0 / tau)
        for s in range(9000, 9000 + n_episodes):
            env.reset(seed=s); p0 = env.robot_pos.copy()
            a = np.zeros(2); md = np.inf
            while True:
                a = rho * a + math.sqrt(1 - rho ** 2) * rng.normal(0, sigma, 2)
                _, _, te, tu, info = env.step(np.clip(a, -1, 1))
                md = min(md, float(np.linalg.norm(env.robot_pos - env.robot_goal)))
                if te or tu: break
            hit += info["episode_metrics"]["success"]
            disp.append(float(np.linalg.norm(env.robot_pos - p0))); near.append(md)
        rows.append({"exploration": label, "goal_reach_rate": hit / n_episodes,
                     "net_displacement_m": float(np.mean(disp)),
                     "closest_approach_m": float(np.mean(near)),
                     "frac_within_2m": float(np.mean(np.array(near) < 2.0))})
    return pd.DataFrame(rows)


# --------------------------------------------------------------------------- #
#  Pre-flight: short training run on the arms most likely to fail
# --------------------------------------------------------------------------- #
def preflight(configs, out_root, timesteps=150_000, n_envs=4, seed=0,
              env_overrides=None, device="auto", net_width=128):
    """Train the riskiest arms briefly and report whether they get off zero.

    Returns (DataFrame, measured_fps).  The measured fps is the ONLY honest
    input to the time budget: extrapolating single-env throughput by the worker
    count ignores IPC and scheduler contention and overestimated by 5x.
    """
    rows, total_steps, t0 = [], 0, time.time()
    for arm in configs:
        run_dir = os.path.join(out_root, "preflight", arm)
        os.makedirs(run_dir, exist_ok=True)
        set_global_seeds(seed); th.set_num_threads(1)
        cfg = make_cfg(arm, **(env_overrides or {}))
        vec_cls = DummyVecEnv          # see train_one
        env = make_vec_env(CrowdNavAblationEnv, n_envs=n_envs, seed=seed,
                           env_kwargs=dict(cfg=cfg), vec_env_cls=vec_cls)
        model = PPO(env=env, seed=seed, device=pick_device(device), verbose=0,
                    **default_ppo_kwargs(n_envs, gamma=cfg.gamma, net_width=net_width))
        cb = EpisodeMetricsCallback(os.path.join(run_dir, "train_episodes.csv"),
                                    os.path.join(run_dir, "train_rollouts.csv"))
        model.learn(total_timesteps=timesteps, callback=cb, progress_bar=False)
        cb.flush(); env.close()
        total_steps += timesteps

        df = pd.DataFrame(cb.rollout_rows)
        peak = float(df["success"].max()) if "success" in df and len(df) else 0.0
        last = float(df["success"].iloc[-3:].mean()) if "success" in df and len(df) else 0.0
        rows.append({"config": arm, "steps": timesteps, "peak_success": peak,
                     "final_success": last,
                     "policy_std_end": float(df["policy_std"].iloc[-1]) if len(df) else np.nan,
                     "learning": bool(peak > 0.02)})
        del model
    fps = total_steps / max(time.time() - t0, 1e-6)
    return pd.DataFrame(rows), fps


# --------------------------------------------------------------------------- #
#  Bimodal-safe statistics
# --------------------------------------------------------------------------- #
def bootstrap_ci(values, n_boot=10000, alpha=0.05, seed=0):
    v = np.asarray([x for x in values if np.isfinite(x)], dtype=float)
    if len(v) == 0: return np.nan, np.nan, np.nan
    if len(v) == 1: return float(v[0]), float(v[0]), float(v[0])
    rng = np.random.default_rng(seed)
    bs = rng.choice(v, size=(n_boot, len(v)), replace=True).mean(axis=1)
    return float(v.mean()), float(np.quantile(bs, alpha / 2)), float(np.quantile(bs, 1 - alpha / 2))


def aggregate_robust(per_run: pd.DataFrame, metrics, solved_threshold=0.5, alpha=0.05):
    """Across-seed aggregation that survives bimodal outcomes.

    Student-t CIs assume unimodality.  When an arm gives 0.94/0.92/0.00/0.91/0.98
    the t-interval is both enormous and meaningless.  We report the bootstrap
    percentile interval, the median with IQR, and -- most informative of all --
    the fraction of seeds that solved the task at all.
    """
    rows = []
    if per_run is None or len(per_run) == 0 or "config" not in per_run.columns:
        cols = ["config", "n_seeds", "seeds_solved"]
        for m in metrics:
            cols += [f"{m}_{k}" for k in ("mean", "lo", "hi", "ci95", "median", "iqr")]
        return pd.DataFrame(columns=cols)
    for cfg, g in per_run.groupby("config"):
        row = {"config": cfg, "n_seeds": len(g)}
        if "success" in g:
            row["seeds_solved"] = float((g["success"] > solved_threshold).mean())
        for m in metrics:
            v = pd.to_numeric(g[m], errors="coerce").replace([np.inf, -np.inf], np.nan).dropna().values
            mu, lo, hi = bootstrap_ci(v, alpha=alpha)
            row[f"{m}_mean"] = mu
            row[f"{m}_lo"] = lo
            row[f"{m}_hi"] = hi
            row[f"{m}_ci95"] = (hi - lo) / 2 if np.isfinite(hi) else np.nan
            row[f"{m}_median"] = float(np.median(v)) if len(v) else np.nan
            row[f"{m}_iqr"] = float(np.subtract(*np.percentile(v, [75, 25]))) if len(v) > 1 else 0.0
        rows.append(row)
    return pd.DataFrame(rows)

# --------------------------------------------------------------------------- #
#  Deadline-aware budget scheduler
# --------------------------------------------------------------------------- #
#  A Kaggle session dies at a hard wall-clock limit.  A sweep that is 80% done
#  when that happens has produced nothing analysable, so the budget cannot be a
#  comment in the config cell -- it has to be an object that every stage asks
#  before it starts and that sizes the stage from the time that is ACTUALLY left.
class Budget:
    """Tracks wall clock against a hard deadline and sizes each stage from it."""

    def __init__(self, total_hours, reserve_hours=0.0, label="session"):
        self.t0 = time.time()
        self.total = float(total_hours) * 3600.0
        self.reserve = float(reserve_hours) * 3600.0
        self.label = label
        self.log = []

    # -- clock ---------------------------------------------------------------
    @property
    def elapsed(self):
        return time.time() - self.t0

    @property
    def remaining(self):
        """Seconds left before the deadline, minus the post-training reserve."""
        return self.total - self.reserve - self.elapsed

    def hours_left(self):
        return self.remaining / 3600.0

    def set_reserve(self, hours):
        self.reserve = float(hours) * 3600.0

    # -- sizing --------------------------------------------------------------
    def steps_for(self, n_runs, fps, share=1.0, target=None,
                  lo=100_000, hi=1_000_000, quantum=10_000):
        """Largest per-run step count that fits `share` of the remaining budget.

        `fps` is the MEASURED aggregate throughput (steps/s across all workers),
        never an extrapolation from single-env speed -- v2 of this study
        overestimated by 5x doing exactly that and had to be re-run.
        """
        if n_runs <= 0 or fps <= 0:
            return 0
        affordable = int(self.remaining * share * fps / n_runs)
        s = affordable if target is None else min(target, affordable)
        s = int(s // quantum * quantum)
        return int(max(lo, min(hi, s))) if s >= lo else 0

    def can_afford(self, n_runs, steps, fps, safety=1.15):
        """Would this stage fit, with a safety factor on the estimate?"""
        if fps <= 0:
            return False
        return (n_runs * steps / fps) * safety <= self.remaining

    def eta_hours(self, n_runs, steps, fps):
        return (n_runs * steps / fps) / 3600.0 if fps > 0 else float("inf")

    # -- reporting -----------------------------------------------------------
    def stage(self, name, n_runs, steps, fps):
        eta = self.eta_hours(n_runs, steps, fps)
        ok = self.can_afford(n_runs, steps, fps)
        print(f"  [budget] {name:26s} {n_runs:4d} runs x {steps:>8,} steps "
              f"-> {eta:5.2f} h   left {self.hours_left():5.2f} h   "
              f"{'GO' if ok else 'SKIP (would overrun)'}")
        return ok

    def mark(self, name):
        self.log.append({"stage": name, "elapsed_h": round(self.elapsed / 3600, 3),
                         "remaining_h": round(self.hours_left(), 3)})
        print(f"  [budget] {name:26s} done at {self.elapsed/3600:5.2f} h "
              f"| {self.hours_left():5.2f} h left")

    def frame(self):
        return pd.DataFrame(self.log)


# --------------------------------------------------------------------------- #
#  Evaluating a whole stage
# --------------------------------------------------------------------------- #
def evaluate_stage(arms, seeds, out_root, test_seeds, env_overrides,
                   n_workers=10, verbose=True, label=""):
    """Load every trained model in a stage and evaluate it on the shared test set.

    Returns (per_run DataFrame, per_episode DataFrame).  Missing models are
    skipped rather than raising, so a stage that was cut short by the budget
    guard still produces an analysable table for the runs that did finish.
    """
    from stable_baselines3 import PPO
    rows, eps = [], []
    t0 = time.time()
    for arm in arms:
        for sd in seeds:
            mp = os.path.join(out_root, "runs", f"{resolve_arm(arm)}__seed{sd}",
                              "model.zip")
            if not os.path.exists(mp):
                continue
            model = PPO.load(mp, device="cpu")
            df = evaluate_fixed(model, arm, test_seeds, n_workers=n_workers,
                                env_overrides=env_overrides, deterministic=True)
            df["config"] = resolve_arm(arm)
            df["train_seed"] = sd
            eps.append(df)
            s = summarise_run(df)
            rows.append({"config": resolve_arm(arm), "seed": sd, **s})
            del model
    per_run = (pd.DataFrame(rows) if rows else
               pd.DataFrame(columns=["config", "seed"] + METRIC_KEYS))
    per_ep = pd.concat(eps, ignore_index=True) if eps else pd.DataFrame()
    if verbose:
        print(f"  evaluated {len(per_run)} runs x {len(test_seeds)} scenarios "
              f"({len(per_ep):,} episodes) in {(time.time()-t0)/60:.1f} min  {label}")
    return per_run, per_ep


def solved_fraction(per_run, arm, threshold=0.5):
    g = per_run[per_run.config == arm]
    return float((g["success"] > threshold).mean()) if len(g) else float("nan")


# --------------------------------------------------------------------------- #
#  Architecture pre-flight: equal WALL-CLOCK comparison, not equal step count
# --------------------------------------------------------------------------- #
class _WallClockStop(BaseCallback):
    """Stops learning after `seconds`, so two configurations can be compared on
    equal wall time rather than equal step count."""

    def __init__(self, seconds):
        super().__init__(0)
        self.seconds = float(seconds)
        self.t0 = None

    def _on_training_start(self):
        self.t0 = time.time()

    def _on_step(self):
        return (time.time() - self.t0) < self.seconds


def arch_preflight(arm, out_root, widths=(128, 256), seconds=180, n_envs=4,
                   seed=0, env_overrides=None, device="auto"):
    """Choose the policy width by MEASUREMENT instead of by taste.

    Both widths train the same arm for the same number of seconds.  The wider
    net does more work per environment step, so at equal wall clock it reaches
    fewer steps; whether that trade is worth it is an empirical question about
    this particular observation space, and it takes six minutes to answer.
    The winner is whichever reaches the higher peak windowed success -- i.e.
    more learning per second of the session's budget.
    """
    rows = []
    for w in widths:
        set_global_seeds(seed); th.set_num_threads(1)
        cfg = make_cfg(arm, **(env_overrides or {}))
        env = make_vec_env(CrowdNavAblationEnv, n_envs=n_envs, seed=seed,
                           env_kwargs=dict(cfg=cfg), vec_env_cls=DummyVecEnv)
        model = PPO(env=env, seed=seed, device=pick_device(device), verbose=0,
                    **default_ppo_kwargs(n_envs, gamma=cfg.gamma, net_width=w))
        run_dir = os.path.join(out_root, "preflight", f"arch{w}")
        os.makedirs(run_dir, exist_ok=True)
        cb = EpisodeMetricsCallback(os.path.join(run_dir, "train_episodes.csv"),
                                    os.path.join(run_dir, "train_rollouts.csv"))
        t0 = time.time()
        model.learn(total_timesteps=10 ** 9, progress_bar=False,
                    callback=[cb, _WallClockStop(seconds)])
        wall = time.time() - t0
        cb.flush(); env.close()
        df = pd.DataFrame(cb.rollout_rows)
        peak = float(df["success"].rolling(3, min_periods=1).mean().max()) \
            if "success" in df and len(df) else 0.0
        final = float(df["success"].iloc[-3:].mean()) if "success" in df and len(df) else 0.0
        rows.append({"net_width": w, "seconds": round(wall, 1),
                     "steps_reached": int(model.num_timesteps),
                     "fps": round(model.num_timesteps / max(wall, 1e-6), 1),
                     "peak_success": peak, "final_success": final})
        del model
    df = pd.DataFrame(rows)
    best = int(df.sort_values(["peak_success", "fps"], ascending=False).iloc[0]["net_width"])
    return df, best

Writing rl_utils.py

In [5]:
%%writefile ablation_stats.py
"""
Cooperative-game analysis of a complete 2^N reward-component ablation, plus the
significance machinery that goes with it.

Why this module exists
----------------------
A leave-one-out ablation reports, for component i, the single number

    LOO(i) = v(N) - v(N \\ {i})

which answers "what does i add on top of everything else?".  Its mirror image,

    AOI(i) = v({i}) - v(empty)

answers "what does i achieve on its own?".  These two numbers routinely disagree
by an order of magnitude, and when they do, neither deserves to be called "the
effect of component i".  With the complete lattice available we can stop
choosing a context and average over all of them, which is exactly the Shapley
value:

    phi_i = sum_{S subset N\\{i}} |S|! (n-|S|-1)! / n! * [v(S + i) - v(S)]

It satisfies efficiency (sum_i phi_i = v(N) - v(empty)), symmetry, linearity and
the null-player property, and it is the unique value that does.  The Moebius
(Harsanyi dividend) transform of the same table,

    m(S) = sum_{T subset S} (-1)^{|S \\ T|} v(T),

decomposes the ablation into a main effect per component plus an explicit
interaction term for every pair, triple, ... .  A negative pairwise dividend
means the two components are SUBSTITUTES (each covers for the other, which is
precisely why leave-one-out finds nothing when you drop either alone); a
positive one means they are COMPLEMENTS.

Everything here is exact arithmetic on the lattice -- no model is fitted, no
distributional assumption is made.  Uncertainty comes from re-doing the exact
computation independently within each training seed and then treating the seeds
as the sample, which is the correct unit of analysis for a deep-RL study.
"""
from itertools import combinations
from math import factorial

import numpy as np

__all__ = [
    "subsets", "mobius_transform", "shapley_values", "interaction_index",
    "loo_effects", "aoi_effects", "lattice_table", "component_analysis",
    "sign_flip_test", "bootstrap_ci", "tost_equivalence", "cliffs_delta",
    "holm_bonferroni", "hierarchical_bootstrap_ci",
]


# --------------------------------------------------------------------------- #
#  Lattice helpers
# --------------------------------------------------------------------------- #
def subsets(n):
    """All 2^n index tuples, ordered by (size, lexicographic)."""
    out = []
    for k in range(n + 1):
        out.extend(combinations(range(n), k))
    return out


def _mask(idx, n):
    m = [False] * n
    for i in idx:
        m[i] = True
    return tuple(m)


# --------------------------------------------------------------------------- #
#  Exact cooperative-game quantities
# --------------------------------------------------------------------------- #
def mobius_transform(v, n):
    """Harsanyi dividends.  `v` maps an index tuple -> value.  Returns dict."""
    m = {}
    for S in subsets(n):
        s = 0.0
        for k in range(len(S) + 1):
            for T in combinations(S, k):
                s += ((-1.0) ** (len(S) - len(T))) * v[T]
        m[S] = s
    return m


def shapley_values(v, n):
    """Exact Shapley value of every component.

    Computed from the definition rather than from the Moebius transform so that
    the two can be cross-checked against each other (see the unit tests).
    """
    phi = np.zeros(n)
    for i in range(n):
        others = [j for j in range(n) if j != i]
        for k in range(n):
            for S in combinations(others, k):
                w = factorial(len(S)) * factorial(n - len(S) - 1) / factorial(n)
                phi[i] += w * (v[tuple(sorted(S + (i,)))] - v[tuple(sorted(S))])
    return phi


def interaction_index(v, n, order=2):
    """Shapley interaction index for every subset of size `order`.

    I(S) = sum_{T superset S} m(T) / (|T| - |S| + 1),  the natural extension of
    the Shapley value to coalitions (Grabisch & Roubens, 1999).  For |S| = 1 it
    reduces to the Shapley value, which the tests verify.
    """
    m = mobius_transform(v, n)
    out = {}
    for S in combinations(range(n), order):
        acc = 0.0
        sS = set(S)
        for T, mt in m.items():
            if sS.issubset(T):
                acc += mt / (len(T) - order + 1)
        out[S] = acc
    return out


def loo_effects(v, n):
    """v(N) - v(N \\ {i}) -- the classical leave-one-out ablation number."""
    N = tuple(range(n))
    return np.array([v[N] - v[tuple(j for j in N if j != i)] for i in range(n)])


def aoi_effects(v, n):
    """v({i}) - v(empty) -- the add-one-in (solo) number."""
    return np.array([v[(i,)] - v[()] for i in range(n)])


# --------------------------------------------------------------------------- #
#  Building the value function from experimental results
# --------------------------------------------------------------------------- #
def lattice_table(per_run, metric, name_fn, n=5, seed_col="seed",
                  config_col="config"):
    """Build {seed: {index_tuple: value}} from a per-(arm, seed) results frame.

    `name_fn(index_tuple)` must return the arm name used in `per_run`.  A seed is
    dropped (with its name recorded) if any lattice cell is missing for it, since
    the Shapley computation needs the complete table and silently imputing a
    hole would fabricate an effect.
    """
    all_S = subsets(n)
    tables, dropped = {}, []
    for sd, g in per_run.groupby(seed_col):
        lut = dict(zip(g[config_col], g[metric]))
        tab, ok = {}, True
        for S in all_S:
            arm = name_fn(S)
            if arm not in lut or not np.isfinite(lut[arm]):
                ok = False
                break
            tab[S] = float(lut[arm])
        if ok:
            tables[int(sd)] = tab
        else:
            dropped.append(int(sd))
    return tables, dropped


def component_analysis(tables, n=5, n_boot=20000, rng_seed=0):
    """Per-seed exact analysis, then seed-level inference.

    Returns a dict with, for every component: the Shapley value, the leave-one-out
    effect and the add-one-in effect -- each as a mean over seeds with a
    percentile bootstrap CI and an exact sign-flip permutation p-value -- plus the
    pairwise interaction indices and the Moebius dividends.
    """
    seeds = sorted(tables)
    if not seeds:
        raise ValueError("no complete lattice for any seed")
    phi = np.vstack([shapley_values(tables[s], n) for s in seeds])
    loo = np.vstack([loo_effects(tables[s], n) for s in seeds])
    aoi = np.vstack([aoi_effects(tables[s], n) for s in seeds])

    pairs = list(combinations(range(n), 2))
    inter = np.vstack([[interaction_index(tables[s], n, 2)[p] for p in pairs]
                       for s in seeds])

    all_S = subsets(n)
    mob = np.vstack([[mobius_transform(tables[s], n)[S] for S in all_S]
                     for s in seeds])

    total = np.array([tables[s][tuple(range(n))] - tables[s][()] for s in seeds])

    def summarise(mat):
        out = []
        for c in range(mat.shape[1]):
            v = mat[:, c]
            mu, lo, hi = bootstrap_ci(v, n_boot=n_boot, seed=rng_seed)
            out.append({"mean": mu, "lo": lo, "hi": hi,
                        "median": float(np.median(v)),
                        "sd": float(np.std(v, ddof=1)) if len(v) > 1 else 0.0,
                        "p": sign_flip_test(v)})
        return out

    return {
        "seeds": seeds,
        "n_seeds": len(seeds),
        "shapley": summarise(phi),
        "loo": summarise(loo),
        "aoi": summarise(aoi),
        "interaction": summarise(inter),
        "interaction_pairs": pairs,
        "mobius": summarise(mob),
        "mobius_sets": all_S,
        "shapley_raw": phi,
        "loo_raw": loo,
        "aoi_raw": aoi,
        "interaction_raw": inter,
        "total_mean": float(np.mean(total)),
        "total_raw": total,
        "efficiency_residual": float(np.max(np.abs(phi.sum(axis=1) - total))),
    }


# --------------------------------------------------------------------------- #
#  Seed-level inference
# --------------------------------------------------------------------------- #
def sign_flip_test(values, n_perm=100000, seed=0):
    """Exact (or Monte-Carlo) two-sided sign-flip permutation test of H0: mean=0.

    The right test for "is this component's effect distinguishable from zero?"
    when the sample is a handful of training seeds: it assumes only that the
    per-seed effects are symmetric about their centre under H0, and unlike the
    Wilcoxon signed-rank test it does not throw away magnitude information.
    With n <= 20 seeds every one of the 2^n sign assignments is enumerated, so
    the p-value is exact.
    """
    v = np.asarray([x for x in values if np.isfinite(x)], dtype=float)
    n = len(v)
    if n == 0:
        return np.nan
    if np.allclose(v, 0.0):
        return 1.0
    obs = abs(float(np.mean(v)))
    if n <= 20:                                    # exact enumeration
        signs = (((np.arange(2 ** n)[:, None] >> np.arange(n)) & 1) * 2 - 1)
        means = np.abs(signs @ v) / n
        return float((means >= obs - 1e-15).mean())
    rng = np.random.default_rng(seed)
    signs = rng.choice([-1.0, 1.0], size=(n_perm, n))
    means = np.abs(signs @ v) / n
    return float((means >= obs - 1e-15).mean())


def bootstrap_ci(values, n_boot=20000, alpha=0.05, seed=0):
    v = np.asarray([x for x in values if np.isfinite(x)], dtype=float)
    if len(v) == 0:
        return np.nan, np.nan, np.nan
    if len(v) == 1:
        return float(v[0]), float(v[0]), float(v[0])
    rng = np.random.default_rng(seed)
    bs = rng.choice(v, size=(n_boot, len(v)), replace=True).mean(axis=1)
    return (float(v.mean()), float(np.quantile(bs, alpha / 2)),
            float(np.quantile(bs, 1 - alpha / 2)))


def hierarchical_bootstrap_ci(per_episode, metric, seed_col="train_seed",
                              n_boot=4000, alpha=0.05, seed=0):
    """Resample seeds, then episodes within seed.

    Deep-RL papers routinely bootstrap episodes while holding the seed mixture
    fixed, which prices only scenario noise and treats the seeds as if they were
    the population.  Resampling at both levels prices the question a reader
    actually cares about: "if I retrained this, what would I get?"
    """
    rng = np.random.default_rng(seed)
    groups = [g[metric].to_numpy(float) for _, g in per_episode.groupby(seed_col)]
    groups = [g[np.isfinite(g)] for g in groups]
    groups = [g for g in groups if len(g)]
    if not groups:
        return np.nan, np.nan, np.nan
    point = float(np.mean([g.mean() for g in groups]))
    draws = np.empty(n_boot)
    k = len(groups)
    for b in range(n_boot):
        pick = rng.integers(0, k, size=k)
        draws[b] = np.mean([rng.choice(groups[i], size=len(groups[i]),
                                       replace=True).mean() for i in pick])
    return point, float(np.quantile(draws, alpha / 2)), float(np.quantile(draws, 1 - alpha / 2))


def tost_equivalence(values, margin, n_perm=100000, seed=0):
    """Two one-sided tests for H1: |mean| < margin  (i.e. PRACTICAL EQUIVALENCE).

    A non-significant difference test is not evidence of no effect -- it is the
    absence of evidence.  If the claim in the paper is "removing R4 does not
    change success", that claim has to be tested directly, and TOST is the
    standard way: we reject the null of a difference at least as large as
    `margin` in either direction.  Returns (p_equivalence, lo90, hi90); the
    equivalence claim holds at alpha when the 90% CI lies inside +/-margin.
    """
    v = np.asarray([x for x in values if np.isfinite(x)], dtype=float)
    n = len(v)
    if n < 2:
        return np.nan, np.nan, np.nan
    mu = float(v.mean())
    se = float(np.std(v, ddof=1) / np.sqrt(n))
    from scipy import stats
    if se <= 0:
        p = 0.0 if abs(mu) < margin else 1.0
        return p, mu, mu
    t_lo = (mu + margin) / se           # H0: mu <= -margin
    t_hi = (mu - margin) / se           # H0: mu >= +margin
    p = max(float(stats.t.sf(t_lo, n - 1)), float(stats.t.cdf(t_hi, n - 1)))
    half = float(stats.t.ppf(0.95, n - 1)) * se          # 90% CI == TOST at 5%
    return p, mu - half, mu + half


def cliffs_delta(a, b):
    """Non-parametric effect size in [-1, 1]; 0 means complete overlap."""
    a = np.asarray(a, dtype=float); b = np.asarray(b, dtype=float)
    a = a[np.isfinite(a)]; b = b[np.isfinite(b)]
    if len(a) == 0 or len(b) == 0:
        return np.nan
    gt = (a[:, None] > b[None, :]).sum()
    lt = (a[:, None] < b[None, :]).sum()
    return float((gt - lt) / (len(a) * len(b)))


def holm_bonferroni(pvals):
    p = np.asarray(pvals, dtype=float)
    n = len(p)
    if n == 0:
        return p
    order = np.argsort(p)
    adj = np.empty(n)
    running = 0.0
    for rank, idx in enumerate(order):
        running = max(running, (n - rank) * p[idx])
        adj[idx] = min(1.0, running)
    return adj

Writing ablation_stats.py

In [6]:
%%writefile viz.py
"""Publication-quality figures for the reward-ablation study."""
import os
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Circle

plt.rcParams.update({
    "figure.dpi": 130, "savefig.dpi": 300, "font.size": 9,
    "axes.grid": True, "grid.alpha": 0.25, "axes.spines.top": False,
    "axes.spines.right": False, "legend.frameon": False,
})

PALETTE = ["#1b6ca8", "#d1495b", "#2a9d8f", "#e9c46a", "#8e7dbe",
           "#f4845f", "#5c8001", "#7d7d7d", "#00798c", "#b26e63"]


# --------------------------------------------------------------------------- #
def plot_trajectory(env, ax=None, title="", stride=4):
    """Draw one recorded episode (env.cfg.record_trajectory must be True)."""
    traj = env.trajectory
    assert traj, "No trajectory recorded -- set record_trajectory=True in EnvConfig."
    if ax is None:
        _, ax = plt.subplots(figsize=(4.2, 4.2))

    rob = np.array([t["robot"] for t in traj])
    hum = np.array([t["humans"] for t in traj])       # (T, N, 2)
    hr = traj[0]["hr"]
    goal = traj[0]["goal"]
    T = len(traj)

    for i in range(hum.shape[1]):
        ax.plot(hum[:, i, 0], hum[:, i, 1], color="0.72", lw=0.9, zorder=1)
    ax.plot(rob[:, 0], rob[:, 1], color=PALETTE[1], lw=2.0, zorder=3)

    for k in range(0, T, stride):
        a = 0.12 + 0.6 * k / max(T - 1, 1)
        for i in range(hum.shape[1]):
            ax.add_patch(Circle(hum[k, i], hr[i], fc="0.55", ec="none",
                                alpha=a * 0.5, zorder=2))
        ax.add_patch(Circle(rob[k], env.robot_radius, fc=PALETTE[1], ec="none",
                            alpha=a, zorder=4))

    ax.add_patch(Circle(goal, env.cfg.goal_tolerance, fc="none",
                        ec=PALETTE[2], lw=1.8, ls="--", zorder=5))
    ax.plot(*rob[0], marker="s", ms=5, color=PALETTE[1], zorder=6)
    lim = env.cfg.circle_radius + 1.4
    ax.set_xlim(-lim, lim); ax.set_ylim(-lim, lim)
    ax.set_aspect("equal"); ax.set_title(title, fontsize=9)
    ax.set_xlabel("x [m]"); ax.set_ylabel("y [m]")
    return ax


# --------------------------------------------------------------------------- #
def _load_curve(run_dir, metric):
    """Prefer the per-rollout log (already windowed, small); fall back to episodes."""
    f = os.path.join(run_dir, "train_rollouts.csv")
    if os.path.exists(f):
        df = pd.read_csv(f)
        if metric in df and not df.empty:
            return df["timesteps"].values, df[metric].values
    f = os.path.join(run_dir, "train_episodes.csv")
    if os.path.exists(f):
        df = pd.read_csv(f)
        if metric in df and not df.empty:
            return df["timesteps"].values, df[metric].rolling(200, min_periods=1).mean().values
    return None, None


def plot_learning_curves(runs_root, configs, metric="success",
                         bins=50, ax=None, title=None):
    """Mean +/- s.e.m. across seeds of a training metric vs. environment steps."""
    if ax is None:
        _, ax = plt.subplots(figsize=(6.0, 3.4))
    for ci, cfg in enumerate(configs):
        curves, grid = [], None
        for d in sorted(os.listdir(runs_root)):
            if not d.startswith(cfg + "__seed"):
                continue
            x, y = _load_curve(os.path.join(runs_root, d), metric)
            if x is None or len(x) < 2:
                continue
            grid = np.linspace(0, float(np.max(x)), bins)
            curves.append(np.interp(grid, x, y))
        if not curves:
            continue
        c = np.vstack(curves)
        mu = c.mean(0)
        se = c.std(0, ddof=1) / np.sqrt(len(c)) if len(c) > 1 else np.zeros_like(mu)
        col = PALETTE[ci % len(PALETTE)]
        ax.plot(grid, mu, color=col, lw=1.6, label=cfg)
        ax.fill_between(grid, mu - se, mu + se, color=col, alpha=0.18)
    ax.set_xlabel("environment steps")
    ax.set_ylabel(metric.replace("_", " "))
    ax.set_title(title or f"Training {metric.replace('_',' ')}")
    ax.legend(fontsize=7, ncol=2)
    return ax


def plot_seed_traces(runs_root, configs, seeds, metric="success", ncols=4):
    """One panel per arm, one thin line per seed, plus the policy std on a twin
    axis.  This is the figure that distinguishes 'never learned' (flat line)
    from 'learned then collapsed' (rises then falls) from 'exploration runaway'
    (std climbing monotonically)."""
    n = len(configs)
    nrows = int(np.ceil(n / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(3.7 * ncols, 2.9 * nrows),
                             squeeze=False)
    axes = axes.ravel()
    for k, cfg in enumerate(configs):
        ax = axes[k]
        ax2 = ax.twinx(); ax2.grid(False)
        for si, sd in enumerate(seeds):
            rd = os.path.join(runs_root, f"{cfg}__seed{sd}")
            x, y = _load_curve(rd, metric)
            if x is None:
                continue
            ax.plot(x, y, lw=1.0, alpha=0.85, color=PALETTE[si % len(PALETTE)])
            xs, ys = _load_curve(rd, "policy_std")
            if xs is not None:
                ax2.plot(xs, ys, lw=0.9, ls=":", color="0.35", alpha=0.7)
        ax.set_ylim(-0.03, 1.03)
        ax.set_title(cfg, fontsize=8.5)
        ax.set_xlabel("steps", fontsize=7.5)
        ax.set_ylabel(metric, fontsize=7.5)
        ax2.set_ylabel("policy std (dotted)", fontsize=7, color="0.35")
        ax2.tick_params(labelsize=6.5, colors="0.35")
        ax.tick_params(labelsize=6.5)
    for k in range(n, len(axes)):
        axes[k].axis("off")
    fig.tight_layout()
    return fig


# --------------------------------------------------------------------------- #
def plot_ablation_bars(agg, metrics, titles=None, reference=None, ncols=3):
    """Grouped bar chart with 95% CI whiskers, one panel per metric."""
    n = len(metrics)
    nrows = int(np.ceil(n / ncols))
    fig, axes = plt.subplots(nrows, ncols, figsize=(4.0 * ncols, 3.0 * nrows))
    axes = np.atleast_1d(axes).ravel()
    order = list(agg["config"])
    for k, m in enumerate(metrics):
        ax = axes[k]
        mu = agg[f"{m}_mean"].values
        ci = agg[f"{m}_ci95"].fillna(0).values
        cols = [PALETTE[0] if c != reference else PALETTE[1] for c in order]
        ax.bar(range(len(order)), mu, yerr=ci, capsize=3,
               color=cols, edgecolor="white", linewidth=0.6)
        ax.set_xticks(range(len(order)))
        ax.set_xticklabels(order, rotation=55, ha="right", fontsize=7)
        ax.set_title((titles or {}).get(m, m.replace("_", " ")), fontsize=9)
    for k in range(n, len(axes)):
        axes[k].axis("off")
    fig.tight_layout()
    return fig


# --------------------------------------------------------------------------- #
def plot_pareto(agg, x="nav_time_succ", y="collision", label_col="config",
                ax=None, annotate=True):
    """Safety / efficiency trade-off scatter."""
    if ax is None:
        _, ax = plt.subplots(figsize=(4.8, 3.8))
    for i, r in agg.iterrows():
        ax.errorbar(r[f"{x}_mean"], r[f"{y}_mean"],
                    xerr=r.get(f"{x}_ci95", 0), yerr=r.get(f"{y}_ci95", 0),
                    fmt="o", ms=7, color=PALETTE[i % len(PALETTE)],
                    ecolor="0.6", elinewidth=0.9, capsize=2)
        if annotate:
            ax.annotate(r[label_col], (r[f"{x}_mean"], r[f"{y}_mean"]),
                        textcoords="offset points", xytext=(6, 4), fontsize=6.5)
    ax.set_xlabel(x.replace("_", " ") + " [s]")
    ax.set_ylabel(y.replace("_", " "))
    ax.set_title("Safety / efficiency trade-off")
    return ax


# --------------------------------------------------------------------------- #
def to_latex(agg, metrics, fmt="{:.3f}", caption="", label="tab:ablation"):
    hdr = " & ".join(["Configuration"] + [m.replace("_", " ") for m in metrics])
    lines = [r"\begin{table}[t]", r"\centering", r"\small",
             r"\begin{tabular}{l" + "c" * len(metrics) + "}", r"\toprule",
             hdr + r" \\", r"\midrule"]
    for _, r in agg.iterrows():
        cells = [str(r["config"]).replace("_", r"\_")]
        for m in metrics:
            mu, ci = r[f"{m}_mean"], r[f"{m}_ci95"]
            cells.append(f"${fmt.format(mu)}\\pm{fmt.format(0 if pd.isna(ci) else ci)}$")
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}",
              rf"\caption{{{caption}}}", rf"\label{{{label}}}", r"\end{table}"]
    return "\n".join(lines)

# --------------------------------------------------------------------------- #
#  Cooperative-game figures (new in V5)
# --------------------------------------------------------------------------- #
def plot_attribution(analysis, comp_labels, metric_label="success rate",
                     ax=None, title=None):
    """Shapley value vs leave-one-out vs add-one-in, side by side per component.

    The whole point of the figure is the DISAGREEMENT between the three bars.
    Where they agree, the component's effect is context-free and leave-one-out
    was telling the truth.  Where the Shapley bar sits far from the LOO bar, the
    single-context ablation that the literature reports is an artefact of the
    context it was measured in.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(7.4, 3.6))
    n = len(comp_labels)
    x = np.arange(n)
    w = 0.27
    series = [("Shapley  $\\phi_i$", analysis["shapley"], PALETTE[0]),
              ("leave-one-out", analysis["loo"], PALETTE[1]),
              ("add-one-in", analysis["aoi"], PALETTE[2])]
    for k, (lbl, rows, col) in enumerate(series):
        mu = np.array([r["mean"] for r in rows])
        lo = np.array([r["lo"] for r in rows])
        hi = np.array([r["hi"] for r in rows])
        ax.bar(x + (k - 1) * w, mu, width=w, color=col, label=lbl,
               edgecolor="white", linewidth=0.6)
        ax.errorbar(x + (k - 1) * w, mu, yerr=[mu - lo, hi - mu], fmt="none",
                    ecolor="0.25", elinewidth=0.9, capsize=2.5)
    ax.axhline(0, color="0.3", lw=0.9)
    ax.set_xticks(x)
    ax.set_xticklabels(comp_labels, fontsize=8)
    ax.set_ylabel(f"$\\Delta$ {metric_label}")
    ax.set_title(title or "Component attribution: averaged over all contexts "
                          "vs. measured in one")
    ax.legend(fontsize=7.5, ncol=3)
    return ax


def plot_interaction_heatmap(analysis, comp_labels, ax=None, title=None,
                             annotate=True):
    """Pairwise Shapley interaction indices.

    Negative (blue) = SUBSTITUTES: the pair covers the same ground, so dropping
    either one alone costs nothing and leave-one-out reports a false null.
    Positive (red) = COMPLEMENTS: the pair is worth more together than the sum
    of its parts.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(4.6, 4.0))
    n = len(comp_labels)
    M = np.full((n, n), np.nan)
    for (i, j), row in zip(analysis["interaction_pairs"], analysis["interaction"]):
        M[i, j] = M[j, i] = row["mean"]
    vmax = np.nanmax(np.abs(M)) if np.isfinite(M).any() else 1.0
    vmax = max(vmax, 1e-9)
    im = ax.imshow(M, cmap="RdBu_r", vmin=-vmax, vmax=vmax)
    ax.set_xticks(range(n)); ax.set_xticklabels(comp_labels, rotation=45,
                                                ha="right", fontsize=7.5)
    ax.set_yticks(range(n)); ax.set_yticklabels(comp_labels, fontsize=7.5)
    ax.grid(False)
    if annotate:
        for i in range(n):
            for j in range(n):
                if i == j:
                    ax.text(j, i, "—", ha="center", va="center",
                            fontsize=9, color="0.5")
                elif np.isfinite(M[i, j]):
                    ax.text(j, i, f"{M[i, j]:+.3f}", ha="center", va="center",
                            fontsize=7,
                            color="white" if abs(M[i, j]) > 0.55 * vmax else "0.15")
    ax.set_title(title or "Pairwise interaction  $I(i,j)$\n"
                          "blue = substitutes, red = complements", fontsize=9)
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    return ax


def plot_lattice_landscape(tables, name_fn, metric_label="success rate",
                           ax=None, comp_labels=None):
    """Every cell of the 2^5 lattice, arranged by the number of active
    components.  It shows at a glance whether performance is a function of HOW
    MANY terms are on (it is not) or of WHICH ones (it is)."""
    from itertools import combinations
    if ax is None:
        _, ax = plt.subplots(figsize=(7.6, 3.8))
    seeds = sorted(tables)
    all_S = sorted(tables[seeds[0]].keys(), key=lambda S: (len(S), S))
    xs, ys, lbls = [], [], []
    for S in all_S:
        vals = [tables[s][S] for s in seeds]
        xs.append(len(S)); ys.append(np.mean(vals)); lbls.append(S)
        ax.scatter([len(S)] * len(vals), vals, s=9, color="0.75", zorder=1)
    ax.scatter(xs, ys, s=52, color=PALETTE[1], zorder=3, edgecolor="white",
               linewidth=0.7)
    for x, y, S in zip(xs, ys, lbls):
        tag = "".join(str(i + 1) for i in S) or "none"
        ax.annotate(tag, (x, y), textcoords="offset points", xytext=(7, -2),
                    fontsize=6.0, color="0.25")
    ax.set_xlabel("number of active reward components")
    ax.set_ylabel(metric_label)
    ax.set_xticks(range(0, 6))
    ax.set_title("The whole $2^5$ lattice: which terms are on beats how many")
    return ax


def plot_dose_response(df, x="w_jerk", y="success", ax=None, title=None,
                       logx=True, ylabel=None):
    """Mean +/- s.e.m. across seeds against a swept weight, on a log axis."""
    if ax is None:
        _, ax = plt.subplots(figsize=(5.0, 3.4))
    g = df.groupby(x)[y].agg(["mean", "std", "count"]).reset_index()
    se = g["std"].fillna(0) / np.sqrt(g["count"].clip(lower=1))
    xv = g[x].values.astype(float)
    if logx:
        xv = np.where(xv <= 0, np.nanmin(xv[xv > 0]) / 3.0 if (xv > 0).any() else 1e-4, xv)
        ax.set_xscale("log")
    ax.errorbar(xv, g["mean"], yerr=se, marker="o", ms=5, lw=1.6,
                color=PALETTE[0], ecolor="0.5", capsize=3)
    if logx and (g[x].values <= 0).any():
        ax.axvline(xv[g[x].values <= 0][0], color=PALETTE[1], ls=":", lw=1.2)
        ax.annotate("w = 0", (xv[g[x].values <= 0][0], ax.get_ylim()[0]),
                    fontsize=7, color=PALETTE[1], rotation=90,
                    textcoords="offset points", xytext=(4, 6))
    ax.set_xlabel(x.replace("_", " "))
    ax.set_ylabel(ylabel or y.replace("_", " "))
    ax.set_title(title or f"Dose–response: {y.replace('_',' ')} vs {x}")
    return ax


def plot_density_effects(df, arms, metric="success", ax=None, title=None):
    """Same contrast measured at two crowd densities, with seed scatter."""
    if ax is None:
        _, ax = plt.subplots(figsize=(6.2, 3.6))
    dens = sorted(df["n_humans"].unique())
    x = np.arange(len(arms))
    w = 0.8 / max(len(dens), 1)
    for k, d in enumerate(dens):
        mu, se = [], []
        for a in arms:
            v = df[(df.n_humans == d) & (df.config == a)][metric].values
            mu.append(np.mean(v) if len(v) else np.nan)
            se.append(np.std(v, ddof=1) / np.sqrt(len(v)) if len(v) > 1 else 0.0)
        ax.bar(x + (k - (len(dens) - 1) / 2) * w, mu, width=w, yerr=se, capsize=3,
               color=PALETTE[k], edgecolor="white", linewidth=0.6,
               label=f"{d} pedestrians")
    ax.set_xticks(x)
    ax.set_xticklabels(arms, rotation=25, ha="right", fontsize=7.5)
    ax.set_ylabel(metric.replace("_", " "))
    ax.set_title(title or "Do the social terms bind only when the crowd binds?")
    ax.legend(fontsize=7.5)
    return ax


def plot_mechanism(df, ax=None, title=None):
    """Action autocorrelation against success, one point per run.

    The jerk hypothesis in one scatter: if R5's contribution runs through
    temporal action coherence, then every run that fails should sit at low
    autocorrelation regardless of which reward produced it, and any intervention
    that raises autocorrelation should move a run to the right AND up.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(5.4, 3.8))
    for k, (lbl, g) in enumerate(df.groupby("group")):
        ax.scatter(g["action_autocorr"], g["success"], s=46, alpha=0.85,
                   color=PALETTE[k % len(PALETTE)], label=lbl,
                   edgecolor="white", linewidth=0.6)
    ax.set_xlabel("lag-1 action autocorrelation (evaluation)")
    ax.set_ylabel("success rate")
    ax.set_title(title or "Mechanism: temporal action coherence vs. task success")
    ax.legend(fontsize=7, loc="best")
    return ax


def plot_metric_profile(agg, arms, metrics, titles=None, ax=None,
                        reference=None):
    """z-scored deltas vs the reference, arms x metrics, as a heatmap.

    Lets a reader see in one glance that (say) R3 and R4 move the SOCIAL metrics
    without moving success, which a success-rate-only table hides completely.
    """
    if ax is None:
        _, ax = plt.subplots(figsize=(1.05 * len(metrics) + 3.2,
                                      0.34 * len(arms) + 1.8))
    idx = agg.set_index(agg["config"].astype(str))
    M = np.full((len(arms), len(metrics)), np.nan)
    for i, a in enumerate(arms):
        for j, m in enumerate(metrics):
            col = f"{m}_mean"
            if a in idx.index and col in idx.columns:
                M[i, j] = idx.loc[a, col]
    if reference is not None and reference in idx.index:
        ref = np.array([idx.loc[reference, f"{m}_mean"] if f"{m}_mean" in idx.columns
                        else np.nan for m in metrics])
        with np.errstate(invalid="ignore"):
            sd = np.nanstd(M, axis=0)
            sd = np.where(sd > 1e-12, sd, 1.0)
            M = (M - ref[None, :]) / sd[None, :]
    vmax = np.nanmax(np.abs(M)) if np.isfinite(M).any() else 1.0
    im = ax.imshow(M, cmap="RdBu_r", vmin=-vmax, vmax=vmax, aspect="auto")
    ax.set_xticks(range(len(metrics)))
    ax.set_xticklabels([(titles or {}).get(m, m.replace("_", " ")) for m in metrics],
                       rotation=40, ha="right", fontsize=7.5)
    ax.set_yticks(range(len(arms)))
    ax.set_yticklabels(arms, fontsize=7.5)
    ax.grid(False)
    for i in range(len(arms)):
        for j in range(len(metrics)):
            if np.isfinite(M[i, j]):
                ax.text(j, i, f"{M[i,j]:+.1f}", ha="center", va="center", fontsize=6,
                        color="white" if abs(M[i, j]) > 0.6 * vmax else "0.15")
    ax.set_title("Behavioural profile (s.d. units vs. the full-reward reference)",
                 fontsize=9)
    plt.colorbar(im, ax=ax, fraction=0.03, pad=0.02)
    return ax

Writing viz.py

## 3 · Experiment configuration — every knob in one place

### Budget philosophy

A Kaggle session dies at a hard wall-clock limit. A sweep that is 80 % finished when that happens has produced **nothing analysable**. So the budget is not a comment in this cell — it is a `Budget` object that every stage interrogates before it starts, sized from *measured* PPO throughput (V2 of this study extrapolated single-environment speed by worker count, projected 6,007 steps/s, and got 1,140).

Stages run in strict priority order and are **skipped rather than truncated**:

| order | stage | runs | why this priority |
|---|---|---|---|
| 1 | **A** — complete $2^5$ lattice | 32 arms × 6 seeds = 192 | the core result; everything else is commentary on it |
| 2 | **D** — shaping-form contrast | 2 × 6 = 12 | needed for the PBRS-vs-progress claim |
| 3 | **C1** — `w_jerk` dose–response | 7 × 3 = 21 (half budget) | turns the study's most surprising binary into a curve |
| 4 | **C2** — action-filter mechanism control | 3 × 3 = 9 | converts the jerk correlation into a mechanism |
| 5 | **B** — density generalisation | 4 × 3 = 12 | tests whether the social-term nulls are density artefacts |
| 6 | **E** — best recipe, extended budget | 6 | headline policy + ONNX export |

All stages share one `steps_per_run`, chosen by the scheduler, so **every arm is compared at an identical training budget** — the equal-budget control that makes an ablation an ablation. Stage E deliberately breaks this and says so: it is the "what is the best this design can do" number, not an ablation cell.

In [7]:
importlib.invalidate_caches()
for m in [k for k in list(sys.modules)
          if k in ("orca", "crowd_env", "rl_utils", "viz", "ablation_stats")]:
    sys.modules.pop(m, None)

import numpy as np, pandas as pd
from crowd_env import (CrowdNavAblationEnv, EnvConfig, make_cfg, ABLATION_CONFIGS,
                       run_baseline, orca_robot_action, straight_line_action,
                       build_crowd_pool, load_crowd_pool,
                       LATTICE, lattice_name, lattice_bits, resolve_arm,
                       display_name, ALIASES, LOO_ARMS, AOI_ARMS,
                       COMPONENT_IDS, COMPONENT_KEYS, COMPONENT_NAMES)
import rl_utils, viz, ablation_stats as AS
from rl_utils import (train_one, train_many, evaluate_fixed, evaluate_stage,
                      summarise_run, aggregate_robust, paired_tests,
                      set_global_seeds, export_onnx, verify_onnx,
                      crossvalidate_orca, METRIC_KEYS, Budget)

# --------------------------------------------------------------------------- #
QUICK_TEST = False        # <-- True: ~12 min end-to-end smoke run of every cell
# --------------------------------------------------------------------------- #

# ---- scenario: IDENTICAL for every arm, every seed, training and test --------
EXPERIMENT = dict(
    n_humans        = 5,
    circle_radius   = 4.0,
    robot_visible   = False,        # invisible-robot setting (harder, standard)
    kinematics      = "holonomic",
    action_frame    = "goal_aligned",
    time_step       = 0.25,
    time_limit      = 25.0,
)

REFERENCE   = "R12345"              # all five components on
NONE_ARM    = "R0_none"             # task reward only (collision + time cost)
LATTICE_ARMS = [lattice_name(b) for b in LATTICE]          # 32 cells
PROGRESS_ARMS = ["P12345_progress", "P2345_progress"]      # stage D
SEEDS       = [0, 1, 2, 3, 4, 5]    # 6 seeds: the smallest n for which an exact
                                    # two-sided sign-flip test can reach p<0.05
                                    # (2/2^6 = 0.031).  With 5 seeds the floor is
                                    # 0.0625 and NO result can ever be significant.

# ---- budget ----------------------------------------------------------------
WALL_BUDGET_HOURS = 10.5            # Kaggle T4x2 allows 12 h; keep 1.5 h of slack
TARGET_STEPS      = 500_000         # aimed for; the scheduler lowers it if needed
MIN_STEPS, MAX_STEPS_PER_RUN = 200_000, 600_000
STAGE_E_MULTIPLIER = 1.5            # extended budget for the headline policy

N_EVAL_EPISODES   = 500             # shared held-out scenarios, every policy
TEST_SEED_BASE    = 10_000_000      # disjoint from every training seed stream

# ---- parallelism -----------------------------------------------------------
N_ENVS      = 4                                 # envs inside one run, in-process
N_PARALLEL  = max(1, (os.cpu_count() or 4))     # concurrent RUNS
DEVICE      = "auto"                            # resolves to CPU: a small MLP on a
                                                # 40-D obs is launch-latency bound

# ---- open-loop crowd pool --------------------------------------------------
USE_CROWD_POOL   = True
TRAIN_POOL_SIZE  = 16_384
TRAIN_POOL_BASE  = 1_000_000
TRAIN_POOL_PATH  = os.path.join(WORK, "crowd_pool_train")
TEST_POOL_PATH   = os.path.join(WORK, "crowd_pool_test")

# ---- stage B: density generalisation ---------------------------------------
DENSITY_N_HUMANS   = 10
DENSITY_ARMS       = ["R12345", "R1245", "R1235", "R125"]   # full, -R3, -R4, -R3-R4
DENSITY_SEEDS      = SEEDS[:3]
DENSITY_POOL_SIZE  = 6_144
DENSITY_POOL_BASE  = 3_000_000
DENSITY_POOL_PATH  = os.path.join(WORK, "crowd_pool_train_d")
DENSITY_TEST_PATH  = os.path.join(WORK, "crowd_pool_test_d")

# ---- stage C: jerk dose-response and mechanism control ----------------------
JERK_WEIGHTS = [0.0, 0.002, 0.005, 0.01, 0.02, 0.05, 0.10, 0.20]
JERK_SEEDS   = SEEDS[:3]
MECHANISM_SPECS = [                 # (label, arm, extra env overrides)
    ("nojerk",          "R1234", {}),
    ("nojerk+filter.5", "R1234", {"action_filter_alpha": 0.5}),
    ("nojerk+filter.8", "R1234", {"action_filter_alpha": 0.8}),
    ("full+filter.5",   "R12345", {"action_filter_alpha": 0.5}),
]
MECHANISM_SEEDS = SEEDS[:3]

# ---- statistics ------------------------------------------------------------
EQUIV_MARGIN = 0.02     # pre-declared TOST margin on success rate.  Justification:
                        # it is roughly the seed-to-seed s.d. of a healthy arm, i.e.
                        # a difference smaller than the noise you would get by
                        # retraining.  Declared BEFORE looking at the results.
N_BOOT = 20_000

if QUICK_TEST:
    LATTICE_ARMS      = ["R12345", "R2345", "R1345", "R1245", "R1235", "R1234",
                         "R125", "R12", "R1", "R0_none"]
    SEEDS             = [0, 1]
    TARGET_STEPS      = 30_000
    MIN_STEPS         = 20_000
    MAX_STEPS_PER_RUN = 30_000
    N_EVAL_EPISODES   = 60
    WALL_BUDGET_HOURS = 0.7
    TRAIN_POOL_SIZE   = 512
    DENSITY_POOL_SIZE = 256
    DENSITY_SEEDS     = [0]
    JERK_WEIGHTS      = [0.0, 0.02, 0.10]
    JERK_SEEDS        = [0]
    MECHANISM_SEEDS   = [0]
    N_BOOT            = 2_000

TEST_SEEDS = list(range(TEST_SEED_BASE, TEST_SEED_BASE + N_EVAL_EPISODES))

_probe    = make_cfg(REFERENCE, **EXPERIMENT)
OBS_DIM   = 5 + 7 * _probe.n_humans
MAX_STEPS = int(round(_probe.time_limit / _probe.time_step))

# The session clock.  `reserve` is set properly in section 7 once the number of
# runs (and therefore the evaluation cost) is known.
BUDGET = Budget(WALL_BUDGET_HOURS, reserve_hours=1.2, label="kaggle-session")
BUDGET.t0 = NOTEBOOK_T0

print(f"lattice arms      : {len(LATTICE_ARMS)}  (complete 2^5 factorial)"
      if len(LATTICE_ARMS) == 32 else f"lattice arms      : {len(LATTICE_ARMS)} (QUICK_TEST subset)")
print(f"seeds             : {SEEDS}")
print(f"stage A runs      : {len(LATTICE_ARMS)*len(SEEDS)}")
print(f"target steps/run  : {TARGET_STEPS:,}  (scheduler may lower to {MIN_STEPS:,})")
print(f"test episodes     : {N_EVAL_EPISODES} shared held-out scenarios per policy")
print(f"obs dim           : {OBS_DIM}   max steps/episode: {MAX_STEPS}")
print(f"wall budget       : {WALL_BUDGET_HOURS} h   elapsed so far: {BUDGET.elapsed/60:.1f} min")
print("\nlattice cells (ordered by component count):")
for i in range(0, len(LATTICE_ARMS), 8):
    print("   " + "  ".join(f"{a:9s}" for a in LATTICE_ARMS[i:i+8]))
print("\nreward weights -- CONSTANT across every arm (only on/off changes):")
for k in ("w_goal", "w_dist", "w_space", "w_ttc", "w_jerk", "r_collision", "r_step",
          "potential_scale", "r_comfort", "ttc_threshold", "ttc_epsilon", "gamma",
          "goal_tolerance"):
    print(f"  {k:17s} {getattr(_probe, k)}")

lattice arms      : 32  (complete 2^5 factorial)
seeds             : [0, 1, 2, 3, 4, 5]
stage A runs      : 192
target steps/run  : 500,000  (scheduler may lower to 200,000)
test episodes     : 500 shared held-out scenarios per policy
obs dim           : 40   max steps/episode: 100
wall budget       : 10.5 h   elapsed so far: 0.5 min

lattice cells (ordered by component count):
   R12345     R1234      R1235      R1245      R1345      R2345      R123       R124
   R125       R134       R135       R145       R234       R235       R245       R345
   R12        R13        R14        R15        R23        R24        R25        R34
   R35        R45        R1         R2         R3         R4         R5         R0_none

reward weights -- CONSTANT across every arm (only on/off changes):
  w_goal            1.0
  w_dist            0.6
  w_space           0.2
  w_ttc             0.02
  w_jerk            0.02
  r_collision       -1.25
  r_step            -0.005
  potential_scale   8.0
  r_comfort         0.5
  ttc_threshold     3.0
  ttc_epsilon       0.2
  gamma             0.99
  goal_tolerance    0.3

## 3.1 · Open-loop crowd pool

The humans are driven by ORCA and cannot see the robot, so the crowd is a **closed autonomous system**: its entire trajectory is a deterministic function of the reset seed. Earlier versions re-solved those same linear programs inside every RL step of every run. Here they are solved once and replayed.

Two properties must hold and are **asserted**, not assumed:

1. A pooled environment is **numerically identical** to a live one for the same seed (checked to bit equality on observations and $<10^{-12}$ on rewards).
2. The pool is only valid while `robot_visible = False` (the environment asserts this internally).

The training pool is a finite scenario distribution disjoint from the test seeds. That is a real methodological choice and belongs in the paper's methods section — state the pool size and the seed ranges, both of which are recorded in `MANIFEST.json`.

In [8]:
t0 = time.time()
if USE_CROWD_POOL:
    if not os.path.isdir(TRAIN_POOL_PATH):
        build_crowd_pool(make_cfg(REFERENCE, **EXPERIMENT),
                         range(TRAIN_POOL_BASE, TRAIN_POOL_BASE + TRAIN_POOL_SIZE),
                         TRAIN_POOL_PATH, n_workers=N_PARALLEL)
    if not os.path.isdir(TEST_POOL_PATH):
        build_crowd_pool(make_cfg(REFERENCE, **EXPERIMENT), TEST_SEEDS,
                         TEST_POOL_PATH, n_workers=N_PARALLEL)

    TRAIN_ENV = {**EXPERIMENT, "crowd_pool_path": TRAIN_POOL_PATH}
    TEST_ENV  = {**EXPERIMENT, "crowd_pool_path": TEST_POOL_PATH}

    # --- equivalence gate: pooled env == live env, bit for bit ---------------
    _rng = np.random.default_rng(3)
    _acts = _rng.uniform(-1, 1, size=(MAX_STEPS + 5, 2))
    _wo = _wr = 0.0
    for _arm in [REFERENCE, "R1235", "R125"]:
        for _s in TEST_SEEDS[:5]:
            _a = CrowdNavAblationEnv(make_cfg(_arm, **EXPERIMENT))
            _b = CrowdNavAblationEnv(make_cfg(_arm, **TEST_ENV))
            _oa, _ = _a.reset(seed=_s); _ob, _ = _b.reset(seed=_s)
            _wo = max(_wo, float(np.abs(_oa - _ob).max()))
            for _act in _acts:
                _oa, _ra, _ta, _ua, _ = _a.step(_act)
                _ob, _rb, _tb, _ub, _ = _b.step(_act)
                _wo = max(_wo, float(np.abs(_oa - _ob).max()))
                _wr = max(_wr, abs(_ra - _rb))
                assert _ta == _tb and _ua == _ub, f"{_arm} seed {_s}: outcome differs"
                if _ta or _ua:
                    break
    assert _wo == 0.0 and _wr < 1e-12, f"pool mismatch: obs {_wo:.2e}, reward {_wr:.2e}"
    print(f"pool equivalence PASS  (max |obs| {_wo:.1e}, max |reward| {_wr:.1e})")
else:
    TRAIN_ENV = TEST_ENV = dict(EXPERIMENT)
    print("crowd pool DISABLED -- ORCA will be solved live inside the RL loop")

def _env_fps(overrides, n=4000):
    e = CrowdNavAblationEnv(make_cfg(REFERENCE, **overrides)); e.reset(seed=0)
    r = np.random.default_rng(0)
    for _ in range(300):
        _, _, te, tu, _ = e.step(r.uniform(-1, 1, 2))
        if te or tu: e.reset()
    t = time.time()
    for _ in range(n):
        _, _, te, tu, _ = e.step(r.uniform(-1, 1, 2))
        if te or tu: e.reset()
    return n / (time.time() - t)

_live = _env_fps(EXPERIMENT)
_pooled = _env_fps(TRAIN_ENV) if USE_CROWD_POOL else _live
print(f"env-only throughput: live {_live:,.0f} steps/s | pooled {_pooled:,.0f} steps/s "
      f"({_pooled/_live:.1f}x)")
BUDGET.mark("crowd pool")

crowd pool: 16,384 scenarios, 100 steps, 134 MB, built in 193s on 4 workers -> /kaggle/working/crowd_pool_train
crowd pool: 500 scenarios, 100 steps, 4 MB, built in 6s on 4 workers -> /kaggle/working/crowd_pool_test
pool equivalence PASS  (max |obs| 0.0e+00, max |reward| 0.0e+00)
env-only throughput: live 1,838 steps/s | pooled 3,733 steps/s (2.0x)
  [budget] crowd pool                 done at  0.06 h |  9.24 h left

## 4 · Validation suite

Nothing below is decorative. Each check catches a specific class of silent failure that would invalidate the study.

| # | Check | The failure it catches |
|---|---|---|
| 1 | Gymnasium API conformance | malformed spaces / step returns |
| 2 | Determinism | same `(seed, actions)` → identical trajectory; different seeds → different. Without this the ablation compares noise. |
| 3 | ORCA correctness | humans left alone must not overlap |
| 4 | **Reward isolation across all 34 arms** | every arm emits *exactly* the terms it declares and no others — the single most important check in the notebook |
| 5 | Task well-posedness | the task is neither trivially solvable nor impossible |
| 6 | PBRS policy invariance | $\sum_t\gamma^tF_t=-\Phi(s_0)$ must hold **exactly** for terminal trajectories. Ng et al. (1999) guarantee invariance *only* if $\Phi(s_{\text{terminal}})=0$; omitting that silently converts R2 into an ordinary non-invariant reward that leaks a pseudo goal bonus. The `progress` form is asserted to *violate* the same identity, by construction. |
| 7 | `ent_coef = 0` | a positive entropy bonus is opposed by the jerk penalty but by **nothing** in the no-jerk arms, so their policy $\sigma$ runs away and "ablate R5" silently becomes "ablate entropy regularisation" |
| 8 | Exploration reachability | quantifies *why* the jerk term matters: how far does an untrained policy travel as a function of the temporal correlation of its noise? |
| 9 | **Action filter is a no-op at $\alpha=0$ and raises autocorrelation at $\alpha>0$** | the mechanism control must be inert when disabled and must actually do what it claims when enabled |
| 10 | **Shapley / Möbius implementation** | verified against closed-form synthetic games, including the substitutes game where leave-one-out provably reports a false null |

In [9]:
from gymnasium.utils.env_checker import check_env
from itertools import combinations

print("1. Gymnasium API ...", end=" ")
check_env(CrowdNavAblationEnv(make_cfg(REFERENCE, **EXPERIMENT)), skip_render_check=True)
print("PASS")

print("2. Determinism ...", end=" ")
def _rollout(seed, acts, **ov):
    e = CrowdNavAblationEnv(make_cfg(REFERENCE, **{**EXPERIMENT, **ov}))
    o, _ = e.reset(seed=seed); tr, rs = [o.copy()], []
    for a in acts:
        o, r, te, tu, _ = e.step(a); tr.append(o.copy()); rs.append(r)
        if te or tu: break
    return np.concatenate(tr), np.array(rs)
_rng = np.random.default_rng(0); _acts = _rng.uniform(-1, 1, size=(100, 2))
t1, r1 = _rollout(42, _acts); t2, r2 = _rollout(42, _acts); t3, _ = _rollout(43, _acts)
assert np.allclose(t1, t2) and np.allclose(r1, r2), "environment is NOT deterministic"
assert not np.allclose(t1[:len(t3)], t3[:len(t1)]), "seeds are not distinguishable"
print("PASS")

print("3. ORCA no-overlap ...", end=" ")
_e = CrowdNavAblationEnv(make_cfg(REFERENCE, **{**EXPERIMENT, "n_humans": 8}))
_worst = np.inf
for s in range(20):
    _e.reset(seed=1000 + s)
    for _ in range(MAX_STEPS):
        _e.step(np.zeros(2))
        P, R = _e.human_pos, _e.human_radius
        for i in range(len(P)):
            for j in range(i + 1, len(P)):
                _worst = min(_worst, float(np.linalg.norm(P[i]-P[j])) - R[i] - R[j])
assert _worst > -0.05, f"ORCA produced human-human overlap ({_worst:.3f} m)"
print(f"PASS (worst surface separation {_worst:+.4f} m)")

print("4. Reward-component isolation across ALL arms ...", end=" ")
_viol = []
for name, bits in ABLATION_CONFIGS.items():
    e = CrowdNavAblationEnv(make_cfg(name, emit_reward_parts=True, **EXPERIMENT))
    e.reset(seed=7); seen = set()
    for a in _rng.uniform(-1, 1, size=(80, 2)):
        _, _, te, tu, info = e.step(a)
        seen |= {k for k, v in info["reward_parts"].items() if abs(v) > 1e-12}
        if te or tu: break
    seen -= {"collision", "step"}              # task-level, present in every arm
    expect = set(k for k, on in zip(COMPONENT_KEYS, bits) if on)
    if seen - expect:
        _viol.append((name, sorted(seen - expect)))
assert not _viol, f"arms emitted disabled terms: {_viol}"
print(f"PASS ({len(ABLATION_CONFIGS)} arms, 0 violations)")

print("5. Task well-posedness ...", end=" ")
_bl = run_baseline(straight_line_action, make_cfg(REFERENCE, **EXPERIMENT), range(9000, 9080))
assert 0.0 < _bl.success.mean() < 0.30, "task is trivial or impossible for a straight-line policy"
print(f"PASS (straight-line success = {_bl.success.mean():.3f}; must be >0 and well below 1)")

print("6. Potential-based shaping is policy-invariant ...")
def _telescope(mode, n=120):
    worst, checked = 0.0, 0
    for s_ in range(n):
        cfg = make_cfg("R12", emit_reward_parts=True, dist_mode=mode, **EXPERIMENT)
        e = CrowdNavAblationEnv(cfg); e.reset(seed=5000 + s_)
        d0 = float(np.linalg.norm(e.robot_pos - e.robot_goal)) / cfg.potential_scale
        acc, t = 0.0, 0
        while True:
            _, _, te, tu, info = e.step(_rng.uniform(-1, 1, 2))
            acc += (cfg.gamma ** t) * info["reward_parts"]["dist"]; t += 1
            if te or tu: break
        if te:
            worst = max(worst, abs(acc - cfg.w_dist * d0)); checked += 1
    return worst, checked
_w, _n = _telescope("pbrs")
assert _w < 1e-9, (f"PBRS telescoping identity violated by {_w:.3e} -- Phi is not "
                   "zeroed at terminal states, R2 is NOT policy-invariant")
print(f"   pbrs     : max |sum gamma^t F + Phi(s0)| = {_w:.2e} over {_n} terminal episodes  PASS")
_w2, _n2 = _telescope("progress")
assert _w2 > 1e-3, "progress mode should NOT be policy-invariant -- check dist_mode wiring"
print(f"   progress : same quantity = {_w2:.3e}  (non-invariant BY CONSTRUCTION, as intended)")

print("7. Entropy bonus does not confound the jerk ablation ...", end=" ")
_ppo = rl_utils.default_ppo_kwargs(N_ENVS, gamma=_probe.gamma)
assert _ppo["ent_coef"] == 0.0, (
    "ent_coef must be 0: a positive entropy bonus is opposed by the jerk penalty "
    "but by NOTHING in the no-jerk arms, so their sigma runs away and the R5 "
    "ablation silently becomes an entropy-regularisation ablation")
print(f"PASS (ent_coef={_ppo['ent_coef']}, target_kl={_ppo['target_kl']}, use_sde={_ppo['use_sde']})")

print("8. Exploration reachability vs. noise correlation ...")
_reach = rl_utils.exploration_reachability(env_overrides=EXPERIMENT, n_episodes=150)
display(_reach.round(3))
_iid = float(_reach.iloc[0]["net_displacement_m"]); _cor = float(_reach.iloc[-1]["net_displacement_m"])
assert _cor > 2.0 * _iid, "correlated exploration should cover far more ground"
print(f"   PASS -- i.i.d. noise covers {_iid:.1f} m of an 8 m journey; correlated covers {_cor:.1f} m.")

print("9. Action filter: inert at alpha=0, effective at alpha>0 ...")
_a0, _r0 = _rollout(11, _acts, action_filter_alpha=0.0)
_a0b, _r0b = _rollout(11, _acts)
assert np.array_equal(_a0, _a0b) and np.array_equal(_r0, _r0b), \
    "action_filter_alpha=0 is NOT a bit-exact no-op -- the mechanism control would be confounded"
def _mean_ac(alpha, n=40):
    vals = []
    for s in range(n):
        e = CrowdNavAblationEnv(make_cfg(REFERENCE, action_filter_alpha=alpha, **EXPERIMENT))
        e.reset(seed=6000 + s)
        while True:
            _, _, te, tu, info = e.step(_rng.uniform(-1, 1, 2))
            if te or tu: break
        vals.append(info["episode_metrics"]["action_autocorr"])
    return float(np.mean(vals))
_ac0, _ac5, _ac8 = _mean_ac(0.0), _mean_ac(0.5), _mean_ac(0.8)
assert _ac8 > _ac5 > _ac0 + 0.2, "the filter does not raise action autocorrelation"
print(f"   PASS -- lag-1 action autocorrelation under random actions: "
      f"alpha=0 -> {_ac0:+.3f}, alpha=0.5 -> {_ac5:+.3f}, alpha=0.8 -> {_ac8:+.3f}")

print("10. Shapley / Moebius implementation, against closed-form games ...")
_n = 5
_rg = np.random.default_rng(1)
for _ in range(20):                         # Shapley from definition == from Moebius
    _v = {S: float(_rg.normal()) for S in AS.subsets(_n)}
    _phi = AS.shapley_values(_v, _n)
    _m = AS.mobius_transform(_v, _n)
    _phim = np.array([sum(_m[S] / len(S) for S in _m if i in S and len(S)) for i in range(_n)])
    assert np.allclose(_phi, _phim, atol=1e-10)
    assert abs(_phi.sum() - (_v[tuple(range(_n))] - _v[()])) < 1e-10      # efficiency
    for S in AS.subsets(_n):                                             # inversion
        assert abs(sum(_m[T] for T in AS.subsets(_n) if set(T).issubset(S)) - _v[S]) < 1e-9
_w5 = _rg.normal(size=_n)                   # additive game: phi == LOO == AOI == w
_va = {S: float(sum(_w5[i] for i in S)) for S in AS.subsets(_n)}
assert np.allclose(AS.shapley_values(_va, _n), _w5, atol=1e-10)
assert np.allclose(AS.loo_effects(_va, _n), _w5, atol=1e-10)
assert max(abs(x) for x in AS.interaction_index(_va, _n, 2).values()) < 1e-10
_i, _j = 2, 3                               # pure substitutes: the LOO failure mode
_vs = {S: 1.0 if (_i in S or _j in S) else 0.0 for S in AS.subsets(_n)}
_loo_s, _phi_s = AS.loo_effects(_vs, _n), AS.shapley_values(_vs, _n)
_I_s = AS.interaction_index(_vs, _n, 2)[(_i, _j)]
assert _loo_s[_i] == 0.0 and _loo_s[_j] == 0.0 and _phi_s[_i] > 0.49 and _I_s < -0.9
_vc = {S: 1.0 if (_i in S and _j in S) else 0.0 for S in AS.subsets(_n)}   # complements
assert AS.interaction_index(_vc, _n, 2)[(_i, _j)] > 0.9
assert abs(AS.sign_flip_test([0.1] * 6) - 2 / 64) < 1e-12                  # exactness
assert AS.tost_equivalence([0.001, -0.002, 0.003, 0.0, 0.002, -0.001], 0.02)[0] < 0.05
assert AS.tost_equivalence([0.30, 0.28, 0.35, 0.31, 0.29, 0.33], 0.02)[0] > 0.5
print("   PASS -- efficiency, Moebius inversion, additive/substitute/complement games,")
print(f"   exact sign-flip p (n=6 unanimous) = {AS.sign_flip_test([0.1]*6):.4f}, TOST both directions.")
print(f"   On the SUBSTITUTES game, leave-one-out reports {_loo_s[_i]:.2f} for BOTH components")
print(f"   while the Shapley value correctly reports {_phi_s[_i]:.2f} each "
      f"(interaction {_I_s:+.2f} = substitutes).")
print("   ^ this is precisely the failure mode the complete lattice exists to fix.")

narrate("VALIDATION COMPLETE", [
    "All ten checks passed.  The environment is deterministic and reproducible, every",
    "one of the 34 reward configurations emits exactly the terms it declares, the",
    "potential-based form of R2 is provably policy-invariant while the progress form",
    "provably is not, the mechanism control is inert when disabled and effective when",
    "enabled, and the cooperative-game code reproduces closed-form answers on games",
    "whose Shapley values are known analytically.",
    "",
    "Check 8 is worth reading as a RESULT rather than a test: under i.i.d. exploration",
    f"an untrained policy covers only {_iid:.1f} m of an 8 m journey.  The terminal goal",
    "reward is therefore effectively unreachable by random exploration, which is the",
    "root cause of everything the jerk analysis in section 13 goes on to measure.",
])

1. Gymnasium API ... PASS
2. Determinism ... PASS
3. ORCA no-overlap ... PASS (worst surface separation -0.0039 m)
4. Reward-component isolation across ALL arms ... PASS (34 arms, 0 violations)
5. Task well-posedness ... PASS (straight-line success = 0.050; must be >0 and well below 1)
6. Potential-based shaping is policy-invariant ...
   pbrs     : max |sum gamma^t F + Phi(s0)| = 4.44e-16 over 48 terminal episodes  PASS
   progress : same quantity = 6.459e-01  (non-invariant BY CONSTRUCTION, as intended)
7. Entropy bonus does not confound the jerk ablation ... PASS (ent_coef=0.0, target_kl=0.03, use_sde=False)
8. Exploration reachability vs. noise correlation ...

,exploration,goal_reach_rate,net_displacement_m,closest_approach_m,frac_within_2m
0,i.i.d. (tau=1),0.000,2.020,7.056,0.000
1,correlated tau=8,0.013,5.067,6.293,0.033
2,correlated tau=16,0.033,6.464,6.022,0.073
3,correlated tau=50,0.047,7.754,5.949,0.100

   PASS -- i.i.d. noise covers 2.0 m of an 8 m journey; correlated covers 7.8 m.
9. Action filter: inert at alpha=0, effective at alpha>0 ...
   PASS -- lag-1 action autocorrelation under random actions: alpha=0 -> -0.042, alpha=0.5 -> +0.464, alpha=0.8 -> +0.751
10. Shapley / Moebius implementation, against closed-form games ...
   PASS -- efficiency, Moebius inversion, additive/substitute/complement games,
   exact sign-flip p (n=6 unanimous) = 0.0312, TOST both directions.
   On the SUBSTITUTES game, leave-one-out reports 0.00 for BOTH components
   while the Shapley value correctly reports 0.50 each (interaction -1.00 = substitutes).
   ^ this is precisely the failure mode the complete lattice exists to fix.

====================================================================================================
|| VALIDATION COMPLETE
----------------------------------------------------------------------------------------------------
   All ten checks passed.  The environment is deterministic and reproducible, every
   one of the 34 reward configurations emits exactly the terms it declares, the
   potential-based form of R2 is provably policy-invariant while the progress form
   provably is not, the mechanism control is inert when disabled and effective when
   enabled, and the cooperative-game code reproduces closed-form answers on games
   whose Shapley values are known analytically.

   Check 8 is worth reading as a RESULT rather than a test: under i.i.d. exploration
   an untrained policy covers only 2.0 m of an 8 m journey.  The terminal goal
   reward is therefore effectively unreachable by random exploration, which is the
   root cause of everything the jerk analysis in section 13 goes on to measure.
====================================================================================================

### 4.1 Optional: numerical cross-validation against `python-rvo2`

A provenance check for the write-up — it verifies our ORCA port reproduces the reference Cython implementation to floating-point tolerance. It is **not** on the critical path: if the build fails, the notebook carries on unaffected.

In [10]:
RVO2_XVAL = None
try:
    sh(f'{sys.executable} -m pip install -q "cython<3"')
    if not os.path.isdir("Python-RVO2"):
        sh("git clone -q https://github.com/sybrenstuvel/Python-RVO2.git")
    sh(f"cd Python-RVO2 && {sys.executable} setup.py -q build_ext --inplace && "
       f"{sys.executable} -m pip install -q . --no-build-isolation --no-deps")
    importlib.invalidate_caches()
    RVO2_XVAL = crossvalidate_orca(n_trials=150, n_agents=6)
except Exception as ex:
    print("python-rvo2 unavailable:", type(ex).__name__, ex)

if RVO2_XVAL is None:
    print("\npython-rvo2 not installed -> cross-validation skipped (bundled ORCA still used).")
else:
    err, n = RVO2_XVAL
    print(f"\nORCA cross-validation vs python-rvo2: max |dv| = {err:.3e} over {n} agent-steps")
    print("MATCH" if err < 2e-4 else "MISMATCH -- investigate before publishing")
json.dump({"rvo2_crossvalidation": (None if RVO2_XVAL is None else
           {"max_abs_velocity_error": RVO2_XVAL[0], "n_agent_steps": RVO2_XVAL[1]})},
          open(f"{OUT}/tables/orca_crossvalidation.json", "w"), indent=2)

> /usr/bin/python3 -m pip install -q "cython<3"
> git clone -q https://github.com/sybrenstuvel/Python-RVO2.git
> cd Python-RVO2 && /usr/bin/python3 setup.py -q build_ext --inplace && /usr/bin/python3 -m pip install -q . --no-build-isolation --no-deps

ORCA cross-validation vs python-rvo2: max |dv| = 1.342e-06 over 900 agent-steps
MATCH

## 5 · Reward-landscape audit — run this *before* training, not after

Every one of the 34 arms defines a different optimisation problem. Before spending hours on gradient descent it is worth asking a question that needs no gradients at all:

> **Under this arm's reward, does a competent navigator actually earn more than a robot that stands perfectly still — or than one that charges straight at the goal and crashes?**

We roll out three fixed policies — a tuned ORCA planner, a do-nothing policy and a straight-line dash — and compare episode returns *under each arm's own reward*. A negative margin means that arm's optimum **is** the degenerate behaviour, and no amount of training will produce a navigating policy, because navigating is genuinely worse under that reward.

This check is why V4 works at all. V3 shipped a reward whose **freeze** return was $+0.406$ — standing still was profitable — and only found out after a six-hour sweep. V4.0 then fixed freezing and shipped a reward where *crashing* paid the same as waiting, because potential-based shaping refunds the whole accumulated potential on **any** termination, goal or collision alike. Gating on one degenerate basin just moves the policy into the other, so we gate on both and require

$$\text{competent} \;>\; \text{freeze} \;>\; \text{dash}.$$

**Gate policy.** The gate is a hard failure only for the reference arm and the leave-one-out family — the cells the headline table depends on. For the remaining lattice cells a violation is *reported loudly and the sweep continues*, because with the complete lattice some cells are legitimately degenerate and that is a finding, not a bug. A notebook that refuses to run the night before a deadline is not a safety feature.

In [11]:
AUDIT_ARMS = list(ABLATION_CONFIGS.keys())
audit = rl_utils.reward_landscape_audit(AUDIT_ARMS, TEST_SEEDS, env_overrides=TEST_ENV,
                                        n_episodes=80 if not QUICK_TEST else 20)

# --- add the dash policy: freezing is not the only degenerate basin ----------
_dash = []
for _arm in AUDIT_ARMS:
    _e = CrowdNavAblationEnv(make_cfg(_arm, **TEST_ENV)); _r = []
    for _s in TEST_SEEDS[:60 if not QUICK_TEST else 15]:
        _e.reset(seed=int(_s)); _R = 0.0
        while True:
            _, _rw, _te, _tu, _ = _e.step(straight_line_action(_e)); _R += _rw
            if _te or _tu: break
        _r.append(_R)
    _dash.append({"config": _arm, "dash": float(np.mean(_r))})
audit = audit.merge(pd.DataFrame(_dash), on="config")
audit["dash_margin"] = audit["competent"] - audit["dash"]
audit["alias"] = audit["config"].map(lambda c: ALIASES.get(c, ""))
audit.to_csv(f"{OUT}/tables/reward_landscape_audit.csv", index=False)

_show = audit[["config", "alias", "competent", "freeze", "dash", "margin", "dash_margin",
               "freeze_is_optimal"]].copy()
display(_show.round(3))

CRITICAL = [REFERENCE] + [a for a in LOO_ARMS if a in AUDIT_ARMS]
_crit = audit[audit.config.isin(CRITICAL)]
_bad_freeze = _crit[_crit.freeze >= 0.0]
_bad_dash   = _crit[_crit.dash >= _crit.freeze - 0.05]

if len(_bad_freeze):
    print("\n!! FREEZE IS PROFITABLE on a CRITICAL arm -- do not launch the sweep:")
    print(_bad_freeze[["config", "competent", "freeze", "margin"]].round(3).to_string(index=False))
if len(_bad_dash):
    print("\n!! DASH-AND-CRASH pays as well as waiting on a CRITICAL arm:")
    print(_bad_dash[["config", "competent", "freeze", "dash"]].round(3).to_string(index=False))
_ref_ok = bool(audit[audit.config == REFERENCE].iloc[0].freeze < 0 and
               audit[audit.config == REFERENCE].iloc[0].dash <
               audit[audit.config == REFERENCE].iloc[0].freeze)
assert _ref_ok, ("the REFERENCE arm's reward is degenerate (freeze or dash is "
                 "competitive with navigating) -- fix r_step / r_collision before training")

_frozen = audit[audit.freeze_is_optimal]["config"].tolist()
_ref = audit[audit.config == REFERENCE].iloc[0]
narrate("REWARD-LANDSCAPE AUDIT", [
    f"Reference arm {REFERENCE}: competent {_ref.competent:+.3f} > freeze {_ref.freeze:+.3f} "
    f"> dash {_ref.dash:+.3f}.  Both degenerate basins are strictly worse than navigating, "
    f"with margins {_ref.margin:+.3f} (vs freeze) and {_ref.dash_margin:+.3f} (vs dash).",
    "",
    f"Worst freeze return over all {len(audit)} arms: {audit.freeze.max():+.3f}   "
    f"(V3 of this study shipped +0.406 here and lost a six-hour sweep to it).",
    f"Worst (dash - freeze) over all arms:           {(audit.dash - audit.freeze).max():+.3f}   "
    f"(must be clearly negative).",
    "",
    ("Arms whose global optimum is a degenerate policy: "
     + (", ".join(_frozen) if _frozen else "NONE -- every arm rewards navigating.")),
    "",
    "Any low success rate on a flagged arm is the REWARD talking, not the optimiser, and",
    "should be reported as a confirmed pre-training prediction rather than as a training",
    f"failure.  The PBRS standing-bonus leak is (1-gamma)*w_dist = "
    f"{(1-_probe.gamma)*_probe.w_dist:+.4f}/step and the time cost is r_step = "
    f"{_probe.r_step:+.4f}/step; the time cost must exceed the leak or freezing stays profitable.",
])
BUDGET.mark("reward audit")

,config,alias,competent,freeze,dash,margin,dash_margin,freeze_is_optimal
0,R12345,R1-5_full,0.606,-0.119,-0.913,0.725,1.519,False
1,R1234,A5_no-jerk,0.676,-0.119,-0.893,0.795,1.569,False
2,R1235,A4_no-ttc,0.744,-0.082,-0.723,0.826,1.467,False
3,R1245,A3_no-space,0.729,-0.090,-0.837,0.819,1.566,False
4,R1345,A2_no-distance,-0.142,-0.766,-1.578,0.624,1.436,False
5,R2345,A1_no-goal,-0.132,-0.119,-0.930,-0.013,0.798,True
6,R123,B4_goal+dist+space,0.814,-0.082,-0.703,0.896,1.517,False
7,R124,B5_goal+dist+ttc,0.799,-0.090,-0.817,0.889,1.616,False
8,R125,B3_goal+dist+jerk,0.867,-0.053,-0.646,0.920,1.513,False
9,R134,,-0.072,-0.766,-1.558,0.694,1.486,False
10,R135,,-0.004,-0.728,-1.387,0.725,1.383,False
11,R145,,-0.019,-0.737,-1.502,0.718,1.482,False
12,R234,,-0.062,-0.119,-0.910,0.058,0.848,False
13,R235,,0.007,-0.082,-0.739,0.088,0.746,False
14,R245,,-0.009,-0.090,-0.854,0.081,0.845,False
15,R345,,-0.880,-0.766,-1.595,-0.113,0.715,True
16,R12,B2_goal+dist,0.937,-0.053,-0.626,0.990,1.564,False
17,R13,,0.067,-0.728,-1.367,0.795,1.434,False
18,R14,,0.051,-0.737,-1.482,0.788,1.533,False
19,R15,,0.119,-0.700,-1.311,0.819,1.430,False
20,R23,,0.077,-0.082,-0.719,0.159,0.796,False
21,R24,,0.061,-0.090,-0.834,0.152,0.895,False
22,R25,B7_dist+jerk,0.130,-0.053,-0.663,0.182,0.793,False
23,R34,,-0.809,-0.766,-1.575,-0.043,0.765,True
24,R35,,-0.741,-0.728,-1.404,-0.013,0.663,True
25,R45,,-0.757,-0.737,-1.518,-0.019,0.762,True
26,R1,B1_goal-only,0.190,-0.700,-1.291,0.889,1.480,False
27,R2,B6_dist-only,0.200,-0.053,-0.643,0.252,0.843,False
28,R3,,-0.671,-0.728,-1.384,0.058,0.713,False
29,R4,,-0.686,-0.737,-1.498,0.051,0.812,False
30,R5,,-0.618,-0.700,-1.327,0.081,0.709,False
31,R0_none,Z_task-only,-0.548,-0.700,-1.307,0.152,0.759,False
32,P12345_progress,C1_progress-dist,0.368,-0.766,-1.285,1.134,1.653,False
33,P2345_progress,C2_no-goal_progress,-0.370,-0.766,-1.301,0.396,0.932,False

====================================================================================================
|| REWARD-LANDSCAPE AUDIT
----------------------------------------------------------------------------------------------------
   Reference arm R12345: competent +0.606 > freeze -0.119 > dash -0.913.  Both degenerate basins
   are strictly worse than navigating, with margins +0.725 (vs freeze) and +1.519 (vs dash).

   Worst freeze return over all 34 arms: -0.053   (V3 of this study shipped +0.406 here and lost a
   six-hour sweep to it).
   Worst (dash - freeze) over all arms:           -0.519   (must be clearly negative).

   Arms whose global optimum is a degenerate policy: R2345, R345, R34, R35, R45

   Any low success rate on a flagged arm is the REWARD talking, not the optimiser, and
   should be reported as a confirmed pre-training prediction rather than as a training
   failure.  The PBRS standing-bonus leak is (1-gamma)*w_dist = +0.0060/step and the time cost is
   r_step = -0.0050/step; the time cost must exceed the leak or freezing stays profitable.
====================================================================================================
  [budget] reward audit               done at  0.11 h |  9.19 h left

## 6 · Non-learning baselines

Reward-shaping numbers are only interpretable against a classical planner. We report:

- **Straight-line** — drive at the goal, ignore everyone. The aggressive/unsafe extreme, and the measurement that tells us the task is not trivially solvable.
- **ORCA($\sigma$)** — the robot itself runs ORCA with `responsibility=1.0` and a safety inflation $\sigma$ on its radius. Vanilla ORCA ($\sigma=0$) plans to graze at *exactly* zero separation, which discrete-time integration turns into a collision; sweeping $\sigma$ traces out the classical planner's own safety/efficiency frontier and gives the learned policies something meaningful to beat.
- **Freeze** — stand perfectly still. This is the number that calibrates the ceiling: whatever fraction of episodes hits a stationary robot is damage the crowd inflicts, not damage the policy caused.

All are evaluated on the **same held-out scenarios** as the learned policies.

In [12]:
baseline_rows, baseline_eps = [], []
_bcfg = make_cfg(REFERENCE, **TEST_ENV)

_specs = ([("Freeze", lambda e: np.zeros(2)),
           ("StraightLine", straight_line_action)] +
          [(f"ORCA(sigma={s:.2f})", (lambda e, s=s: orca_robot_action(e, 1.0, s)))
           for s in (0.00, 0.15, 0.30, 0.45)])

for name, fn in _specs:
    t0 = time.time()
    df = run_baseline(fn, _bcfg, TEST_SEEDS)
    df["config"] = name; df["train_seed"] = -1
    baseline_eps.append(df)
    baseline_rows.append({"config": name, "seed": -1, **summarise_run(df)})
    print(f"{name:20s} succ={df.success.mean():.3f} coll={df.collision.mean():.3f} "
          f"tout={df.timeout.mean():.3f}  ({time.time()-t0:.0f}s)")

baseline_runs = pd.DataFrame(baseline_rows)
baseline_episodes = pd.concat(baseline_eps, ignore_index=True)
baseline_runs.to_csv(f"{OUT}/tables/baselines_summary.csv", index=False)
display(baseline_runs[["config", "success", "collision", "timeout", "nav_time_succ",
                       "path_length_ratio_succ", "intrusion_rate", "mean_sq_accel",
                       "min_separation", "action_autocorr"]].round(3))

_frz = baseline_runs[baseline_runs.config == "Freeze"].iloc[0]
_best_orca = baseline_runs[baseline_runs.config.str.startswith("ORCA")].sort_values("success").iloc[-1]
narrate("WHAT THE CEILING ACTUALLY IS", [
    f"A robot that stands PERFECTLY STILL is struck in {_frz.collision:.1%} of the held-out "
    f"scenarios.  That is damage the crowd inflicts on a stationary obstacle; no policy can "
    f"avoid all of it, because the pedestrians cannot see the robot and roughly half of them "
    f"are faster than it.",
    "",
    f"The best classical planner, {_best_orca.config}, reaches {_best_orca.success:.3f} success "
    f"with {_best_orca.collision:.3f} collisions at {_best_orca.nav_time_succ:.1f} s.  A "
    f"straight-line dash reaches {baseline_runs[baseline_runs.config=='StraightLine'].iloc[0].success:.3f}.",
    "",
    "So the task is well-posed: not solvable by driving straight, not solved by standing still,",
    "and not saturated by the classical planner.  There is headroom for the ablation to",
    "discriminate, which is the property an ablation study actually needs -- the SPREAD between",
    "arms is the result, not the mean.",
])
BUDGET.mark("baselines")

Freeze               succ=0.000 coll=0.270 tout=0.730  (10s)
StraightLine         succ=0.034 coll=0.966 tout=0.000  (2s)
ORCA(sigma=0.00)     succ=0.206 coll=0.794 tout=0.000  (4s)
ORCA(sigma=0.15)     succ=0.540 coll=0.460 tout=0.000  (6s)
ORCA(sigma=0.30)     succ=0.670 coll=0.330 tout=0.000  (7s)
ORCA(sigma=0.45)     succ=0.714 coll=0.282 tout=0.004  (8s)

,config,success,collision,timeout,nav_time_succ,path_length_ratio_succ,intrusion_rate,mean_sq_accel,min_separation,action_autocorr
0,Freeze,0.000,0.270,0.730,NaN,NaN,0.048,0.000,0.472,0.000
1,StraightLine,0.034,0.966,0.000,7.750,0.969,0.356,1.103,-0.117,0.000
2,ORCA(sigma=0.00),0.206,0.794,0.000,8.842,1.046,0.382,1.138,-0.026,0.546
3,ORCA(sigma=0.15),0.540,0.460,0.000,10.019,1.142,0.438,1.145,0.046,0.651
4,ORCA(sigma=0.30),0.670,0.330,0.000,11.557,1.280,0.456,1.294,0.128,0.760
5,ORCA(sigma=0.45),0.714,0.282,0.004,12.678,1.371,0.380,1.306,0.222,0.805

====================================================================================================
|| WHAT THE CEILING ACTUALLY IS
----------------------------------------------------------------------------------------------------
   A robot that stands PERFECTLY STILL is struck in 27.0% of the held-out scenarios.  That is
   damage the crowd inflicts on a stationary obstacle; no policy can avoid all of it, because the
   pedestrians cannot see the robot and roughly half of them are faster than it.

   The best classical planner, ORCA(sigma=0.45), reaches 0.714 success with 0.282 collisions at
   12.7 s.  A straight-line dash reaches 0.034.

   So the task is well-posed: not solvable by driving straight, not solved by standing still,
   and not saturated by the classical planner.  There is headroom for the ablation to
   discriminate, which is the property an ablation study actually needs -- the SPREAD between
   arms is the result, not the mean.
====================================================================================================
  [budget] baselines                  done at  0.12 h |  9.18 h left

## 7 · Pre-flight, architecture selection and the budget scheduler

Three jobs, all learned the hard way from earlier versions.

**1. Measure throughput; never extrapolate it.** V2 measured single-environment speed and multiplied by the worker count: projected 6,007 steps/s, actual 1,140. Worker IPC and scheduler contention are not small corrections. Here we run *real PPO* — the thing whose speed we actually care about — and size the whole experiment from the number it returns.

**2. Choose the network width by measurement.** The policy update is a substantial fraction of wall-clock time for a 40-D observation, so a wider network buys capacity we may not need at the price of steps we certainly do. Rather than guess, we train the reference arm at two widths for *equal wall-clock time* and keep whichever learns more per second. This is a decision about the compute budget, applied identically to every arm, so it cannot bias the ablation.

**3. Find out in ten minutes whether the risky arms can learn.** Arms that dropped the jerk term produced 0 % on every seed in earlier versions, and that was only discovered after six hours. They are trained here on a short budget first.

The scheduler then sets one `steps_per_run` shared by every arm in every stage — the equal-budget control — and each stage checks the clock before it starts.

In [13]:
# ---------------- (a) architecture pre-flight, equal wall clock -------------
ARCH_SECONDS = 20 if QUICK_TEST else 200
arch_df, NET_WIDTH = rl_utils.arch_preflight(
    REFERENCE, OUT, widths=(128, 256), seconds=ARCH_SECONDS, n_envs=N_ENVS,
    seed=0, env_overrides=TRAIN_ENV, device=DEVICE)
arch_df.to_csv(f"{OUT}/tables/arch_preflight.csv", index=False)
display(arch_df.round(3))
_w0, _w1 = arch_df.iloc[0], arch_df.iloc[1]
print(f">> selected net_arch = pi[{NET_WIDTH},{NET_WIDTH}] / vf[{NET_WIDTH},{NET_WIDTH}]  "
      f"(more learning per second of session budget)")
print(f"   width {int(_w0.net_width)}: {_w0.steps_reached:>7,} steps in {_w0.seconds:.0f}s "
      f"({_w0.fps:,.0f} fps) -> peak success {_w0.peak_success:.3f}")
print(f"   width {int(_w1.net_width)}: {_w1.steps_reached:>7,} steps in {_w1.seconds:.0f}s "
      f"({_w1.fps:,.0f} fps) -> peak success {_w1.peak_success:.3f}")

# ---------------- (b) learning pre-flight on the risky arms ----------------
PREFLIGHT_ARMS  = [a for a in [REFERENCE, "R1234", "R125", "R2345"] if a in LATTICE_ARMS]
PREFLIGHT_STEPS = 20_000 if QUICK_TEST else 120_000
pf, measured_fps = rl_utils.preflight(PREFLIGHT_ARMS, OUT, timesteps=PREFLIGHT_STEPS,
                                      n_envs=N_ENVS, seed=0, env_overrides=TRAIN_ENV,
                                      device=DEVICE, net_width=NET_WIDTH)
pf["alias"] = pf["config"].map(lambda c: ALIASES.get(c, ""))
pf.to_csv(f"{OUT}/tables/preflight.csv", index=False)
display(pf.round(3))
print(f"measured single-run PPO throughput: {measured_fps:,.0f} steps/s "
      f"({N_ENVS} envs, device={rl_utils.pick_device(DEVICE)}, width={NET_WIDTH})")

_expected_dead = set(audit[audit.freeze_is_optimal]["config"])
_unexpected = [a for a in pf[~pf.learning]["config"].tolist() if a not in _expected_dead]
if _unexpected:
    print("\n   NOTE: no learning yet after the pre-flight budget on:", _unexpected)
    print("   Not necessarily a bug -- these arms are expected to be slow or degenerate;")
    print("   section 13 is the experiment that explains them.")

# ---------------- (c) size every stage from the measured rate --------------
# One run has the machine to itself while being measured; running N_PARALLEL of
# them never scales linearly (memory bandwidth, page cache, hyperthreading), so
# the aggregate rate is discounted rather than under-booking the budget and
# getting killed mid-sweep.
PARALLEL_EFFICIENCY = 0.78
AGG_FPS = measured_fps * N_PARALLEL * PARALLEL_EFFICIENCY

# Run-equivalents at the shared step size (stage C1 runs at half budget,
# stage E at STAGE_E_MULTIPLIER).
N_A = len(LATTICE_ARMS) * len(SEEDS)
N_D = len(PROGRESS_ARMS) * len(SEEDS)
N_C1 = len(JERK_WEIGHTS) * len(JERK_SEEDS)
N_C2 = len(MECHANISM_SPECS) * len(MECHANISM_SEEDS)
N_B = len(DENSITY_ARMS) * len(DENSITY_SEEDS)
N_E = len(SEEDS)
RUN_EQUIV = N_A + N_D + 0.5 * N_C1 + N_C2 + N_B + STAGE_E_MULTIPLIER * N_E
TOTAL_EVALS = N_A + N_D + N_C1 + N_C2 + N_B + N_E

# Reserve: evaluation dominates the post-training cost and scales with run count.
EVAL_SECONDS_PER_RUN = 0.030 * N_EVAL_EPISODES + 2.0
RESERVE_H = (TOTAL_EVALS * EVAL_SECONDS_PER_RUN) / 3600.0 + (0.10 if QUICK_TEST else 0.45)
BUDGET.set_reserve(RESERVE_H)

STEPS_PER_RUN = BUDGET.steps_for(RUN_EQUIV, AGG_FPS, share=1.0, target=TARGET_STEPS,
                                 lo=MIN_STEPS, hi=MAX_STEPS_PER_RUN)
if STEPS_PER_RUN == 0:
    STEPS_PER_RUN = MIN_STEPS
STAGE_E_STEPS = int(STEPS_PER_RUN * STAGE_E_MULTIPLIER // 10_000 * 10_000)

print("\n" + "=" * 100)
print("BUDGET PLAN")
print("=" * 100)
print(f"  aggregate throughput estimate : {AGG_FPS:,.0f} steps/s "
      f"({measured_fps:,.0f} x {N_PARALLEL} workers x {PARALLEL_EFFICIENCY:.2f})")
print(f"  wall budget / elapsed / left  : {WALL_BUDGET_HOURS:.2f} h / "
      f"{BUDGET.elapsed/3600:.2f} h / {BUDGET.hours_left():.2f} h (after {RESERVE_H:.2f} h reserve)")
print(f"  shared steps per run          : {STEPS_PER_RUN:,}   "
      f"(target {TARGET_STEPS:,}, floor {MIN_STEPS:,})")
print(f"  stage E steps per run         : {STAGE_E_STEPS:,}  (extended, NOT an ablation cell)")
print(f"  total env steps planned       : {RUN_EQUIV*STEPS_PER_RUN:,.0f}")
print(f"  total evaluations planned     : {TOTAL_EVALS} policies x {N_EVAL_EPISODES} scenarios "
      f"= {TOTAL_EVALS*N_EVAL_EPISODES:,} episodes")
print("-" * 100)
for _nm, _n, _s in (("A  2^5 lattice", N_A, STEPS_PER_RUN),
                    ("D  shaping form", N_D, STEPS_PER_RUN),
                    ("C1 jerk dose-response", N_C1, STEPS_PER_RUN // 2),
                    ("C2 mechanism control", N_C2, STEPS_PER_RUN),
                    ("B  density n=%d" % DENSITY_N_HUMANS, N_B, STEPS_PER_RUN),
                    ("E  best recipe", N_E, STAGE_E_STEPS)):
    print(f"  {_nm:26s} {_n:4d} runs x {_s:>8,} = {_n*_s/AGG_FPS/3600:5.2f} h")
print("=" * 100)

narrate("HOW THE BUDGET GUARD BEHAVES", [
    f"Every stage below asks the Budget object how much time is left before it starts and is "
    f"SKIPPED, not truncated, if it would overrun.  Stage A (the complete lattice) runs first "
    f"because every other result is commentary on it.",
    "",
    "All training is resumable: re-running any training cell skips (arm, seed) pairs whose",
    "model.zip already exists, so a session that hits the Kaggle wall clock can be continued",
    "in a second session and the analysis cells will pick up whatever finished.",
    "",
    f"Note that stages A-D all share steps_per_run = {STEPS_PER_RUN:,}.  That equal-budget "
    f"control is what makes this an ablation rather than a hyper-parameter search: no arm can "
    f"win by having been trained longer.",
])

   net_width  seconds  steps_reached     fps  peak_success  final_success
0        128    200.2         342332  1709.9         0.985          0.968
1        256    200.2         295736  1477.2         0.970          0.952

>> selected net_arch = pi[128,128] / vf[128,128]  (more learning per second of session budget)
   width 128: 342,332.0 steps in 200s (1,710 fps) -> peak success 0.985
   width 256: 295,736.0 steps in 200s (1,477 fps) -> peak success 0.970

,config,steps,peak_success,final_success,policy_std_end,learning,alias
0,R12345,120000,0.685,0.637,0.476,True,R1-5_full
1,R1234,120000,0.000,0.000,0.565,False,A5_no-jerk
2,R125,120000,0.810,0.770,0.482,True,B3_goal+dist+jerk
3,R2345,120000,0.520,0.505,0.472,True,A1_no-goal

measured single-run PPO throughput: 1,697 steps/s (4 envs, device=cpu, width=128)

   NOTE: no learning yet after the pre-flight budget on: ['R1234']
   Not necessarily a bug -- these arms are expected to be slow or degenerate;
   section 13 is the experiment that explains them.

====================================================================================================
BUDGET PLAN
====================================================================================================
  aggregate throughput estimate : 5,293 steps/s (1,697 x 4 workers x 0.78)
  wall budget / elapsed / left  : 10.50 h / 0.32 h / 8.52 h (after 1.67 h reserve)
  shared steps per run          : 500,000   (target 500,000, floor 200,000)
  stage E steps per run         : 750,000  (extended, NOT an ablation cell)
  total env steps planned       : 124,500,000
  total evaluations planned     : 258 policies x 500 scenarios = 129,000 episodes
----------------------------------------------------------------------------------------------------
  A  2^5 lattice              192 runs x  500,000 =  5.04 h
  D  shaping form              12 runs x  500,000 =  0.31 h
  C1 jerk dose-response        24 runs x  250,000 =  0.31 h
  C2 mechanism control         12 runs x  500,000 =  0.31 h
  B  density n=10              12 runs x  500,000 =  0.31 h
  E  best recipe                6 runs x  750,000 =  0.24 h
====================================================================================================

====================================================================================================
|| HOW THE BUDGET GUARD BEHAVES
----------------------------------------------------------------------------------------------------
   Every stage below asks the Budget object how much time is left before it starts and is SKIPPED,
   not truncated, if it would overrun.  Stage A (the complete lattice) runs first because every
   other result is commentary on it.

   All training is resumable: re-running any training cell skips (arm, seed) pairs whose
   model.zip already exists, so a session that hits the Kaggle wall clock can be continued
   in a second session and the analysis cells will pick up whatever finished.

   Note that stages A-D all share steps_per_run = 500,000.  That equal-budget control is what
   makes this an ablation rather than a hyper-parameter search: no arm can win by having been
   trained longer.
====================================================================================================

## 8 · Stage A — the complete $2^5$ factorial

192 training runs: every subset of $\{R1,R2,R3,R4,R5\}$ at six seeds. Every run receives the identical PPO configuration — learning rate $3\times10^{-4}$ with linear decay, 4096-step rollouts, batch 512, 10 epochs, $\gamma=0.99$, GAE $\lambda=0.95$, clip 0.2, `ent_coef = 0.0`, `target_kl = 0.03`, ReLU, and the width selected in §7. **The only difference between runs is which reward terms are switched on.**

`ent_coef` is zero deliberately, not by omission: a positive entropy bonus applies a constant upward gradient to $\log\sigma$, and the jerk penalty is the only reward term that opposes it everywhere in state space, since $\mathbb{E}[-w_{jerk}\lVert a_t-a_{t-1}\rVert^2]=-4w_{jerk}\sigma^2$ for i.i.d. actions. With `ent_coef > 0` the jerk arms equilibrate at $\sigma=\sqrt{\text{ent\_coef}/4w_{jerk}}$ while the no-jerk arms have *nothing* opposing the bonus and their $\sigma$ runs away — which turns "ablate R5" into "ablate entropy regularisation", a different experiment.

`gamma` is asserted equal to the discount used inside the shaping term: the policy-invariance guarantee holds *only* under that equality.

In [14]:
STAGE_A_ROOT = OUT
plan_A = [(c, s) for c in LATTICE_ARMS for s in SEEDS]

if not BUDGET.stage("A  2^5 lattice", len(plan_A), STEPS_PER_RUN, AGG_FPS):
    print("!! Stage A does not fit the remaining budget.  Reduce WALL_BUDGET_HOURS pressure,")
    print("   or re-run this notebook in a fresh session -- finished runs are skipped.")

t_start = time.time()
train_meta_A = train_many(plan_A, STEPS_PER_RUN, N_ENVS, STAGE_A_ROOT,
                          device=DEVICE, env_overrides=TRAIN_ENV,
                          n_parallel=N_PARALLEL, verbose=True, net_width=NET_WIDTH)
pd.DataFrame(train_meta_A).to_csv(f"{OUT}/tables/training_meta_A.csv", index=False)
_wall = (time.time() - t_start) / 60
_agg = sum(m["total_timesteps"] for m in train_meta_A) / max(_wall * 60, 1e-9)
print(f"\ncompleted {len(train_meta_A)}/{len(plan_A)} runs in {_wall:.1f} min "
      f"| aggregate {_agg:,.0f} steps/s across {N_PARALLEL} workers")
if len(train_meta_A) < len(plan_A):
    print("!! not every run finished -- re-run this cell in a fresh session; "
          "finished runs are skipped automatically")
# Refresh the throughput estimate from the real sweep, so later stages are sized
# from what the machine actually did rather than from a single-run pre-flight.
if _agg > 0:
    AGG_FPS = 0.5 * AGG_FPS + 0.5 * _agg
BUDGET.mark("stage A training")

  [budget] A  2^5 lattice              192 runs x  500,000 steps ->  5.04 h   left  8.52 h   GO

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[ 1/192] R12345               seed=2    8.7 min     962 fps   ETA 1695.1 min
[ 2/192] R12345               seed=1    8.7 min     961 fps   ETA 844.0 min
[ 3/192] R12345               seed=0    8.7 min     960 fps   ETA 560.3 min
[ 4/192] R12345               seed=3    8.7 min     954 fps   ETA 420.4 min
[ 5/192] R1234                seed=0    8.5 min     979 fps   ETA 651.1 min
[ 6/192] R12345               seed=4    8.5 min     976 fps   ETA 539.7 min
[ 7/192] R12345               seed=5    8.6 min     966 fps   ETA 462.7 min
[ 8/192] R1234                seed=1    8.6 min     973 fps   ETA 402.8 min
[ 9/192] R1234                seed=3    8.5 min     984 fps   ETA 526.3 min
[10/192] R1234                seed=2    8.6 min     972 fps   ETA 473.0 min
[11/192] R1234                seed=4    8.5 min     975 fps   ETA 428.7 min
[12/192] R1234                seed=5    8.6 min     969 fps   ETA 391.7 min
[13/192] R1235                seed=0    7.8 min    1074 fps   ETA 463.2 min
[14/192] R1235                seed=1    7.8 min    1067 fps   ETA 429.7 min
[15/192] R1235                seed=2    7.9 min    1060 fps   ETA 400.2 min
[16/192] R1235                seed=3    7.8 min    1067 fps   ETA 373.2 min
[17/192] R1235                seed=4    7.8 min    1072 fps   ETA 426.3 min
[18/192] R1235                seed=5    7.8 min    1063 fps   ETA 402.5 min
[19/192] R1245                seed=1    8.5 min     976 fps   ETA 386.6 min
[20/192] R1245                seed=0    8.6 min     974 fps   ETA 365.3 min
[21/192] R1245                seed=2    8.4 min     988 fps   ETA 405.9 min
[22/192] R1245                seed=3    8.5 min     982 fps   ETA 387.3 min
[23/192] R1245                seed=4    8.5 min     982 fps   ETA 374.4 min
[24/192] R1245                seed=5    8.5 min     976 fps   ETA 357.1 min
[25/192] R1345                seed=0    8.4 min     986 fps   ETA 389.4 min
[26/192] R1345                seed=1    8.5 min     975 fps   ETA 374.6 min
[27/192] R1345                seed=2    8.6 min     970 fps   ETA 363.8 min
[28/192] R1345                seed=3    8.6 min     971 fps   ETA 349.0 min
[29/192] R1345                seed=4    8.5 min     980 fps   ETA 375.5 min
[30/192] R1345                seed=5    8.6 min     967 fps   ETA 363.3 min
[31/192] R2345                seed=0    8.6 min     966 fps   ETA 354.0 min
[32/192] R2345                seed=1    8.6 min     968 fps   ETA 341.0 min
[33/192] R2345                seed=2    8.6 min     972 fps   ETA 363.2 min
[34/192] R2345                seed=3    8.6 min     967 fps   ETA 352.7 min
[35/192] R2345                seed=4    8.7 min     962 fps   ETA 344.6 min
[36/192] R2345                seed=5    8.6 min     964 fps   ETA 333.0 min
[37/192] R123                 seed=0    7.6 min    1095 fps   ETA 347.6 min
[38/192] R123                 seed=1    7.8 min    1071 fps   ETA 339.1 min
[39/192] R123                 seed=2    7.7 min    1076 fps   ETA 331.8 min
[40/192] R123                 seed=3    7.7 min    1078 fps   ETA 321.4 min
[41/192] R123                 seed=4    7.7 min    1089 fps   ETA 333.8 min
[42/192] R123                 seed=5    7.8 min    1074 fps   ETA 326.6 min
[43/192] R124                 seed=1    8.4 min     987 fps   ETA 322.3 min
[44/192] R124                 seed=0    8.5 min     986 fps   ETA 312.9 min
[45/192] R124                 seed=2    8.3 min    1002 fps   ETA 323.3 min
[46/192] R124                 seed=3    8.4 min     991 fps   ETA 316.9 min
[47/192] R124                 seed=4    8.4 min     990 fps   ETA 312.9 min
[48/192] R124                 seed=5    8.5 min     984 fps   ETA 304.5 min
[49/192] R125                 seed=0    7.6 min    1091 fps   ETA 311.1 min
[50/192] R125                 seed=1    7.7 min    1080 fps   ETA 305.5 min
[51/192] R125                 seed=2    7.7 min    1084 fps   ETA 301.7 min
[52/192] R125                 seed=3    7.8 min    1071 fps   ETA 294.2 min
[53/192] R125                 seed=4    7.7 min    1086 fps   ETA 299.7 min
[54/192] R125                 seed=5    7.8 min    1075 fps   ETA 294.7 min
[55/192] R134                 seed=0    8.6 min     970 fps   ETA 293.2 min
[56/192] R134                 seed=1    8.6 min     969 fps   ETA 286.3 min
[57/192] R134                 seed=2    8.5 min     984 fps   ETA 290.7 min
[58/192] R134                 seed=3    8.6 min     972 fps   ETA 286.2 min
[59/192] R134                 seed=4    8.6 min     964 fps   ETA 284.8 min
[60/192] R134                 seed=5    8.7 min     961 fps   ETA 278.4 min
[61/192] R135                 seed=0    7.8 min    1062 fps   ETA 280.4 min
[62/192] R135                 seed=1    7.9 min    1056 fps   ETA 276.3 min
[63/192] R135                 seed=2    7.8 min    1062 fps   ETA 274.8 min
[64/192] R135                 seed=3    7.9 min    1060 fps   ETA 268.8 min
[65/192] R135                 seed=4    7.7 min    1078 fps   ETA 270.3 min
[66/192] R135                 seed=5    7.9 min    1057 fps   ETA 266.6 min
[67/192] R145                 seed=0    8.6 min     972 fps   ETA 266.4 min
[68/192] R145                 seed=1    8.6 min     968 fps   ETA 260.8 min
[69/192] R145                 seed=2    8.5 min     986 fps   ETA 261.6 min
[70/192] R145                 seed=3    8.5 min     981 fps   ETA 258.2 min
[71/192] R145                 seed=4    8.5 min     979 fps   ETA 257.8 min
[72/192] R145                 seed=5    8.4 min     990 fps   ETA 252.4 min
[73/192] R234                 seed=0    8.4 min     989 fps   ETA 253.0 min
[74/192] R234                 seed=1    8.5 min     984 fps   ETA 249.8 min
[75/192] R234                 seed=2    8.6 min     970 fps   ETA 249.4 min
[76/192] R234                 seed=3    8.6 min     967 fps   ETA 244.3 min
[77/192] R234                 seed=4    8.5 min     979 fps   ETA 244.5 min
[78/192] R234                 seed=5    8.6 min     966 fps   ETA 241.5 min
[79/192] R235                 seed=0    7.9 min    1054 fps   ETA 240.0 min
[80/192] R235                 seed=1    7.9 min    1056 fps   ETA 235.1 min
[81/192] R235                 seed=2    7.8 min    1062 fps   ETA 235.1 min
[82/192] R235                 seed=3    7.9 min    1056 fps   ETA 232.3 min
[83/192] R235                 seed=4    8.0 min    1045 fps   ETA 230.8 min
[84/192] R235                 seed=5    7.9 min    1049 fps   ETA 226.1 min
[85/192] R245                 seed=0    8.6 min     973 fps   ETA 226.7 min
[86/192] R245                 seed=1    8.6 min     968 fps   ETA 224.0 min
[87/192] R245                 seed=2    8.7 min     962 fps   ETA 222.6 min
[88/192] R245                 seed=3    8.6 min     968 fps   ETA 218.1 min
[89/192] R245                 seed=4    8.5 min     978 fps   ETA 218.3 min
[90/192] R245                 seed=5    8.6 min     970 fps   ETA 215.7 min
[91/192] R345                 seed=0    8.6 min     965 fps   ETA 214.3 min
[92/192] R345                 seed=1    8.6 min     965 fps   ETA 209.9 min
[93/192] R345                 seed=2    8.6 min     972 fps   ETA 209.9 min
[94/192] R345                 seed=3    8.7 min     963 fps   ETA 207.5 min
[95/192] R345                 seed=4    8.7 min     958 fps   ETA 206.0 min
[96/192] R345                 seed=5    8.7 min     954 fps   ETA 201.9 min
[97/192] R12                  seed=0    7.5 min    1107 fps   ETA 200.5 min
[98/192] R12                  seed=1    7.6 min    1101 fps   ETA 198.1 min
[99/192] R12                  seed=2    7.6 min    1101 fps   ETA 196.6 min
[100/192] R12                  seed=3    7.6 min    1100 fps   ETA 192.7 min
[101/192] R12                  seed=4    7.5 min    1112 fps   ETA 191.2 min
[102/192] R12                  seed=5    7.6 min    1101 fps   ETA 188.9 min
[103/192] R13                  seed=0    7.7 min    1080 fps   ETA 187.5 min
[104/192] R13                  seed=1    7.7 min    1078 fps   ETA 183.8 min
[105/192] R13                  seed=2    7.6 min    1094 fps   ETA 182.2 min
[106/192] R13                  seed=3    7.8 min    1068 fps   ETA 180.1 min
[107/192] R13                  seed=4    7.9 min    1061 fps   ETA 178.7 min
[108/192] R13                  seed=5    7.9 min    1054 fps   ETA 175.1 min
[109/192] R14                  seed=0    8.5 min     980 fps   ETA 173.9 min
[110/192] R14                  seed=1    8.5 min     980 fps   ETA 171.8 min
[111/192] R14                  seed=2    8.5 min     983 fps   ETA 170.3 min
[112/192] R14                  seed=3    8.5 min     980 fps   ETA 166.9 min
[113/192] R14                  seed=4    8.5 min     982 fps   ETA 165.6 min
[114/192] R14                  seed=5    8.5 min     977 fps   ETA 163.5 min
[115/192] R15                  seed=0    7.8 min    1072 fps   ETA 161.5 min
[116/192] R15                  seed=1    7.7 min    1077 fps   ETA 158.1 min
[117/192] R15                  seed=2    7.6 min    1090 fps   ETA 156.7 min
[118/192] R15                  seed=3    7.7 min    1082 fps   ETA 154.7 min
[119/192] R15                  seed=4    7.8 min    1073 fps   ETA 152.7 min
[120/192] R15                  seed=5    7.8 min    1066 fps   ETA 149.5 min
[121/192] R23                  seed=0    7.6 min    1090 fps   ETA 147.9 min
[122/192] R23                  seed=1    7.7 min    1079 fps   ETA 146.0 min
[123/192] R23                  seed=2    7.7 min    1076 fps   ETA 144.0 min
[124/192] R23                  seed=3    7.7 min    1083 fps   ETA 140.9 min
[125/192] R23                  seed=4    7.6 min    1092 fps   ETA 139.2 min
[126/192] R23                  seed=5    7.8 min    1063 fps   ETA 137.4 min
[127/192] R24                  seed=0    8.5 min     976 fps   ETA 135.7 min
[128/192] R24                  seed=1    8.5 min     975 fps   ETA 132.7 min
[129/192] R24                  seed=2    8.4 min     988 fps   ETA 131.0 min
[130/192] R24                  seed=3    8.5 min     982 fps   ETA 129.1 min
[131/192] R24                  seed=4    8.5 min     982 fps   ETA 127.4 min
[132/192] R24                  seed=5    8.5 min     980 fps   ETA 124.5 min
[133/192] R25                  seed=0    7.7 min    1085 fps   ETA 122.4 min
[134/192] R25                  seed=1    7.7 min    1080 fps   ETA 120.5 min
[135/192] R25                  seed=2    7.7 min    1082 fps   ETA 118.8 min
[136/192] R25                  seed=3    7.7 min    1080 fps   ETA 116.0 min
[137/192] R25                  seed=4    7.7 min    1087 fps   ETA 113.8 min
[138/192] R25                  seed=5    7.7 min    1076 fps   ETA 112.0 min
[139/192] R34                  seed=0    8.5 min     984 fps   ETA 110.5 min
[140/192] R34                  seed=1    8.5 min     982 fps   ETA 107.8 min
[141/192] R34                  seed=2    8.3 min     998 fps   ETA 105.6 min
[142/192] R34                  seed=3    8.4 min     989 fps   ETA 103.7 min
[143/192] R34                  seed=4    8.5 min     981 fps   ETA 102.2 min
[144/192] R34                  seed=5    8.6 min     972 fps   ETA  99.6 min
[145/192] R35                  seed=0    7.8 min    1073 fps   ETA  97.1 min
[146/192] R35                  seed=1    7.8 min    1068 fps   ETA  95.3 min
[147/192] R35                  seed=2    7.9 min    1055 fps   ETA  93.8 min
[148/192] R35                  seed=3    7.9 min    1056 fps   ETA  91.1 min
[149/192] R35                  seed=4    7.8 min    1062 fps   ETA  88.7 min
[150/192] R35                  seed=5    7.9 min    1050 fps   ETA  86.9 min
[151/192] R45                  seed=0    8.6 min     971 fps   ETA  85.5 min
[152/192] R45                  seed=1    8.6 min     968 fps   ETA  82.9 min
[153/192] R45                  seed=2    8.5 min     979 fps   ETA  80.6 min
[154/192] R45                  seed=3    8.6 min     972 fps   ETA  78.7 min
[155/192] R45                  seed=4    8.6 min     967 fps   ETA  77.2 min
[156/192] R1                   seed=0    7.6 min    1096 fps   ETA  74.7 min
[157/192] R45                  seed=5    8.6 min     965 fps   ETA  72.2 min
[158/192] R1                   seed=1    7.7 min    1089 fps   ETA  70.3 min
[159/192] R1                   seed=2    7.6 min    1096 fps   ETA  68.7 min
[160/192] R1                   seed=3    7.6 min    1103 fps   ETA  66.2 min
[161/192] R1                   seed=4    7.6 min    1096 fps   ETA  63.8 min
[162/192] R1                   seed=5    7.6 min    1098 fps   ETA  61.9 min
[163/192] R2                   seed=0    7.7 min    1079 fps   ETA  60.3 min
[164/192] R2                   seed=1    7.6 min    1090 fps   ETA  57.8 min
[165/192] R2                   seed=2    7.6 min    1091 fps   ETA  55.5 min
[166/192] R2                   seed=3    7.7 min    1084 fps   ETA  53.5 min
[167/192] R2                   seed=5    7.5 min    1107 fps   ETA  51.8 min
[168/192] R2                   seed=4    7.6 min    1098 fps   ETA  49.5 min
[169/192] R3                   seed=0    7.8 min    1074 fps   ETA  47.2 min
[170/192] R3                   seed=1    7.7 min    1079 fps   ETA  45.2 min
[171/192] R3                   seed=2    7.6 min    1092 fps   ETA  43.5 min
[172/192] R3                   seed=3    7.8 min    1071 fps   ETA  41.2 min
[173/192] R3                   seed=4    7.7 min    1079 fps   ETA  38.9 min
[174/192] R3                   seed=5    7.8 min    1070 fps   ETA  37.0 min
[175/192] R4                   seed=0    8.4 min     989 fps   ETA  35.2 min
[176/192] R4                   seed=1    8.5 min     981 fps   ETA  33.0 min
[177/192] R4                   seed=2    8.5 min     983 fps   ETA  30.8 min
[178/192] R4                   seed=3    8.5 min     976 fps   ETA  28.8 min
[179/192] R5                   seed=0    7.7 min    1077 fps   ETA  26.9 min
[180/192] R4                   seed=4    8.4 min     992 fps   ETA  24.7 min
[181/192] R4                   seed=5    8.5 min     984 fps   ETA  22.6 min
[182/192] R5                   seed=1    7.7 min    1079 fps   ETA  20.5 min
[183/192] R5                   seed=2    7.7 min    1086 fps   ETA  18.6 min
[184/192] R5                   seed=3    7.6 min    1094 fps   ETA  16.5 min
[185/192] R5                   seed=4    7.7 min    1088 fps   ETA  14.3 min
[186/192] R5                   seed=5    7.7 min    1078 fps   ETA  12.3 min
[187/192] R0_none              seed=1    7.5 min    1104 fps   ETA  10.3 min
[188/192] R0_none              seed=0    7.6 min    1100 fps   ETA   8.2 min
[189/192] R0_none              seed=2    7.6 min    1101 fps   ETA   6.1 min
[190/192] R0_none              seed=3    7.5 min    1117 fps   ETA   4.1 min
[191/192] R0_none              seed=5    5.0 min    1657 fps   ETA   2.0 min
[192/192] R0_none              seed=4    5.4 min    1541 fps   ETA   0.0 min

trained 192 runs in 391.5 min on 4 workers

completed 192/192 runs in 391.5 min | aggregate 4,087 steps/s across 4 workers
  [budget] stage A training           done at  6.84 h |  1.99 h left

### 8.1 Training-health diagnostics

Run this **before** trusting any evaluation number. Final-policy metrics cannot tell three very different failures apart:

| pattern | curve shape | meaning |
|---|---|---|
| never learned | flat and low, peak ≈ final | hard exploration, or no goal signal at all |
| **collapsed** | rises then falls, peak ≫ final | PPO instability — corrupted value target or too-large updates |
| **runaway exploration** | policy $\sigma$ climbing monotonically | nothing in the reward opposes the entropy/variance pressure |

The middle row is what an uncorrected PBRS term produces; the bottom row is what `ent_coef > 0` produces in the no-jerk arms. Both are detected automatically here. A non-empty list means the corresponding evaluation rows must not be reported without comment.

In [15]:
import matplotlib.pyplot as plt
health = rl_utils.training_health(os.path.join(OUT, "runs"), LATTICE_ARMS, SEEDS,
                                  metric="success")
N_TRAINED = len(health)
if N_TRAINED == 0:
    raise RuntimeError(
        "No stage-A run produced a training log.  Every training run failed, so there "
        "is nothing to analyse.  Scroll up to the stage-A cell: train_many prints the "
        "exception for each failed run rather than aborting the sweep, so the cause is "
        "in that output.  Fix it and re-run the training cell -- finished runs are "
        "skipped automatically.")
health["alias"] = health["config"].map(lambda c: ALIASES.get(c, ""))
health.to_csv(f"{OUT}/tables/training_health.csv", index=False)

_summary = (health.groupby("config")
            .agg(seeds=("seed", "count"),
                 peak=("success_peak", "mean"),
                 final=("success_final", "mean"),
                 drop=("drop", "mean"),
                 std_end=("policy_std_end", "mean"),
                 collapsed=("collapsed", "sum"),
                 runaway=("runaway_exploration", "sum"))
            .reindex(LATTICE_ARMS).round(3))
display(_summary)

_bad = health[health.collapsed | health.runaway_exploration]
if len(_bad):
    print("\n!! UNHEALTHY RUNS -- do not report these evaluation rows without comment:")
    for _, r in _bad.iterrows():
        why = []
        if r.collapsed: why.append(f"collapse {r.success_peak:.2f}->{r.success_final:.2f}")
        if r.runaway_exploration: why.append(f"sigma {r.policy_std_start:.2f}->{r.policy_std_end:.2f}")
        print(f"   {display_name(r.config):28s} seed{r.seed}  " + " | ".join(why))
else:
    print("\nAll runs healthy: no late-training collapse, no exploration runaway.")

_TRACE = [a for a in ["R12345", "R2345", "R1345", "R1245", "R1235", "R1234",
                      "R125", "R12", "R1", "R2", "R5", "R0_none"] if a in LATTICE_ARMS]
fig = viz.plot_seed_traces(os.path.join(OUT, "runs"), _TRACE, SEEDS, metric="success")
fig.suptitle("Per-seed training success (solid, left axis) and policy std (dotted, right axis)",
             y=1.005, fontsize=10)
fig.savefig(f"{OUT}/figures/fig0_training_health.png", bbox_inches="tight")
plt.show()

narrate("READING THE TRAINING-HEALTH PANEL", [
    "Each panel is one reward configuration; each solid line is one training seed; the dotted",
    "line is the policy's standard deviation on the right-hand axis.",
    "",
    "A flat line at zero with a FALLING sigma means the policy converged confidently to doing",
    "nothing useful -- the reward gave it no gradient toward the goal.  A flat line at zero with",
    "a RISING or high sigma means the policy never stopped flailing: it is still emitting",
    "near-random actions, which in a goal-aligned velocity frame cancel out to no motion.",
    "Those two failures look identical in a results table and are completely different",
    "phenomena; section 13 is built to separate them.",
])
BUDGET.mark("stage A health")

         seeds   peak  final   drop  std_end  collapsed  runaway
config
R12345       6  0.980  0.964  0.016    0.324          0        0
R1234        6  0.000  0.000  0.000    0.446          0        0
R1235        6  0.967  0.956  0.011    0.330          0        0
R1245        6  0.806  0.791  0.015    0.328          0        0
R1345        6  0.168  0.162  0.007    0.302          0        0
R2345        6  0.982  0.963  0.019    0.323          0        0
R123         6  0.000  0.000  0.000    0.459          0        0
R124         6  0.117  0.080  0.037    0.437          1        0
R125         6  0.964  0.946  0.018    0.333          0        0
R134         6  0.000  0.000  0.000    0.406          0        0
R135         6  0.490  0.481  0.009    0.311          0        0
R145         6  0.324  0.317  0.007    0.312          0        0
R234         6  0.000  0.000  0.000    0.446          0        0
R235         6  0.974  0.959  0.015    0.317          0        0
R245         6  0.808  0.795  0.012    0.313          0        0
R345         6  0.166  0.159  0.007    0.303          0        0
R12          6  0.216  0.170  0.046    0.460          1        0
R13          6  0.000  0.000  0.000    0.423          0        0
R14          6  0.000  0.000  0.000    0.409          0        0
R15          6  0.484  0.471  0.013    0.314          0        0
R23          6  0.000  0.000  0.000    0.459          0        0
R24          6  0.047  0.030  0.017    0.438          1        0
R25          6  0.968  0.950  0.018    0.327          0        0
R34          6  0.000  0.000  0.000    0.406          0        0
R35          6  0.490  0.482  0.008    0.303          0        0
R45          6  0.325  0.320  0.005    0.307          0        0
R1           6  0.000  0.000  0.000    0.422          0        0
R2           6  0.199  0.164  0.035    0.463          0        0
R3           6  0.000  0.000  0.000    0.423          0        0
R4           6  0.000  0.000  0.000    0.409          0        0
R5           6  0.487  0.476  0.010    0.308          0        0
R0_none      6  0.000  0.000  0.000    0.422          0        0

!! UNHEALTHY RUNS -- do not report these evaluation rows without comment:
   B5_goal+dist+ttc [R124]      seed5  collapse 0.70->0.48
   B2_goal+dist [R12]           seed5  collapse 0.34->0.11
   R24                          seed5  collapse 0.28->0.18

====================================================================================================
|| READING THE TRAINING-HEALTH PANEL
----------------------------------------------------------------------------------------------------
   Each panel is one reward configuration; each solid line is one training seed; the dotted
   line is the policy's standard deviation on the right-hand axis.

   A flat line at zero with a FALLING sigma means the policy converged confidently to doing
   nothing useful -- the reward gave it no gradient toward the goal.  A flat line at zero with
   a RISING or high sigma means the policy never stopped flailing: it is still emitting
   near-random actions, which in a goal-aligned velocity frame cancel out to no motion.
   Those two failures look identical in a results table and are completely different
   phenomena; section 13 is built to separate them.
====================================================================================================
  [budget] stage A health             done at  6.84 h |  1.99 h left

## 9 · Evaluation on a fixed, shared test set

Every policy is evaluated **deterministically** on exactly the same 500 scenarios (seeds `10,000,000 … 10,000,499`), disjoint from anything seen in training. Fixing the scenarios removes sampling noise from the between-arm comparison and lets us pair episodes by scenario.

`nav_time`, `path_length_ratio` and `mean_sq_accel` are additionally reported conditioned on **successful** episodes, since they are ill-defined for a run that ended in a collision after two seconds — reporting the unconditional mean would make reckless policies look fast.

In [16]:
per_run_A, per_ep_A = evaluate_stage(LATTICE_ARMS, SEEDS, OUT, TEST_SEEDS, TEST_ENV,
                                     n_workers=10, label="(stage A)")
if len(per_run_A) == 0:
    raise RuntimeError("No stage-A policy could be evaluated -- see the training cell output.")
per_run_A.to_csv(f"{OUT}/tables/per_run_summary_A.csv", index=False)
per_ep_A.to_csv(f"{OUT}/tables/per_episode_eval_A.csv.gz", index=False, compression="gzip")

HEADLINE = ["success", "collision", "timeout", "intrusion_count",
            "path_length_ratio_succ", "nav_time_succ", "mean_sq_accel",
            "min_separation", "action_autocorr", "displacement_efficiency"]

agg_A = aggregate_robust(per_run_A, HEADLINE)
_missing = [a for a in LATTICE_ARMS if a not in set(agg_A["config"])]
if _missing:
    print(f"!! {len(_missing)} arm(s) produced no evaluable policy and are absent from the "
          f"tables below: {_missing}")
    print("   Shapley attribution needs the COMPLETE lattice, so it will be skipped for any")
    print("   seed with a hole.  Re-run the training cell to fill them in.")
agg_A = agg_A[agg_A["config"].isin(LATTICE_ARMS)].copy()
agg_A["config"] = pd.Categorical(agg_A["config"], categories=LATTICE_ARMS, ordered=True)
agg_A = agg_A.sort_values("config").reset_index(drop=True)
agg_A["alias"] = agg_A["config"].astype(str).map(lambda c: ALIASES.get(c, ""))
agg_A.to_csv(f"{OUT}/tables/aggregated_by_config_A.csv", index=False)

print("=" * 118)
print(f"COMPLETE 2^5 LATTICE -- mean [bootstrap 95% CI] over {len(SEEDS)} training seeds "
      f"x {N_EVAL_EPISODES} shared held-out scenarios")
print("=" * 118)
_disp = pd.DataFrame({
    "arm": agg_A["config"].astype(str),
    "alias": agg_A["alias"],
    "k": [sum(ABLATION_CONFIGS[c]) for c in agg_A["config"].astype(str)],
    "solved": agg_A["seeds_solved"].map(lambda v: f"{int(round(v*len(SEEDS)))}/{len(SEEDS)}"),
})
for m in ["success", "collision", "timeout", "nav_time_succ", "min_separation",
          "intrusion_count", "mean_sq_accel", "action_autocorr"]:
    _disp[m] = [f"{a:.3f} [{lo:.2f},{hi:.2f}]" for a, lo, hi
                in zip(agg_A[f"{m}_mean"], agg_A[f"{m}_lo"], agg_A[f"{m}_hi"])]
display(_disp)

print("\nMedian [IQR] -- the honest summary when an arm is bimodal across seeds:")
_med = pd.DataFrame({"arm": agg_A["config"].astype(str), "alias": agg_A["alias"]})
for m in ("success", "collision", "timeout", "mean_sq_accel"):
    _med[m] = [f"{a:.3f} [{b:.3f}]" for a, b in zip(agg_A[f"{m}_median"], agg_A[f"{m}_iqr"])]
display(_med)

_k = _disp.copy(); _k["succ"] = agg_A["success_mean"].values
_bysize = _k.groupby("k")["succ"].agg(["mean", "min", "max", "count"]).round(3)
print("\nSuccess as a function of HOW MANY components are active:")
display(_bysize)
narrate("FIRST READING OF THE LATTICE", [
    "The table above is the complete experiment: 32 reward designs, six seeds each, all",
    "trained on an identical budget and evaluated on identical scenarios.",
    "",
    "Read the 'solved' column before the means.  A mean of 0.5 can mean 'every seed reached",
    "0.5' or 'three seeds reached 1.0 and three reached 0.0'.  Those are completely different",
    "claims about a reward design and only the fraction-of-seeds column separates them.",
    "",
    "The by-size table is the first real finding: if performance were a function of HOW MANY",
    "terms are switched on, the min and max within each row would be close together.  Where",
    "they are far apart, it is WHICH terms are on that decides the outcome -- which is exactly",
    "what an ablation is supposed to establish, and exactly what a leave-one-out design",
    "assumes rather than tests.",
])
BUDGET.mark("stage A evaluation")

  evaluated 192 runs x 500 scenarios (96,000 episodes) in 41.2 min  (stage A)
======================================================================================================================
COMPLETE 2^5 LATTICE -- mean [bootstrap 95% CI] over 6 training seeds x 500 shared held-out scenarios
======================================================================================================================

,arm,alias,k,solved,success,collision,timeout,nav_time_succ,min_separation,intrusion_count,mean_sq_accel,action_autocorr
0,R12345,R1-5_full,5,6/6,"0.983 [0.98,0.99]","0.020 [0.02,0.02]","0.000 [0.00,0.00]","13.762 [13.24,14.37]","0.619 [0.58,0.66]","1.129 [0.96,1.31]","0.501 [0.48,0.52]","0.970 [0.96,0.98]"
1,R1234,A5_no-jerk,4,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.509 [1.43,1.58]","0.165 [0.15,0.18]","0.995 [0.62,1.37]","0.845 [0.72,0.92]"
2,R1235,A4_no-ttc,4,6/6,"0.978 [0.97,0.99]","0.024 [0.02,0.03]","0.000 [0.00,0.00]","13.769 [13.23,14.47]","0.619 [0.58,0.67]","1.153 [0.96,1.38]","0.483 [0.44,0.52]","0.970 [0.96,0.98]"
3,R1245,A3_no-space,4,5/6,"0.811 [0.48,0.98]","0.027 [0.01,0.04]","0.167 [0.00,0.50]","13.720 [13.45,13.99]","0.747 [0.56,1.07]","1.127 [0.72,1.47]","0.462 [0.31,0.55]","0.972 [0.96,0.98]"
4,R1345,A2_no-distance,4,1/6,"0.165 [0.00,0.49]","0.002 [0.00,0.01]","0.833 [0.50,1.00]","12.944 [12.94,12.94]","1.388 [1.05,1.57]","0.460 [0.25,0.86]","0.201 [0.11,0.34]","0.992 [0.98,1.00]"
5,R2345,A1_no-goal,4,6/6,"0.975 [0.97,0.98]","0.032 [0.03,0.04]","0.000 [0.00,0.00]","15.869 [15.13,16.68]","0.688 [0.64,0.73]","0.901 [0.74,1.07]","0.512 [0.48,0.55]","0.981 [0.97,0.99]"
6,R123,B4_goal+dist+space,3,0/6,"0.016 [0.00,0.05]","0.000 [0.00,0.00]","0.984 [0.95,1.00]","23.672 [23.67,23.67]","1.451 [1.35,1.56]","0.183 [0.17,0.21]","0.849 [0.58,1.10]","0.858 [0.80,0.91]"
7,R124,B5_goal+dist+ttc,3,1/6,"0.157 [0.00,0.47]","0.005 [0.00,0.02]","0.837 [0.51,1.00]","19.257 [19.26,19.26]","1.429 [1.17,1.58]","0.303 [0.17,0.53]","1.085 [0.72,1.38]","0.850 [0.79,0.89]"
8,R125,B3_goal+dist+jerk,3,6/6,"0.971 [0.96,0.98]","0.031 [0.02,0.05]","0.000 [0.00,0.00]","13.778 [13.43,14.09]","0.572 [0.54,0.60]","1.327 [1.15,1.51]","0.476 [0.45,0.51]","0.978 [0.97,0.98]"
9,R134,,3,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.624 [1.59,1.65]","0.155 [0.14,0.17]","0.533 [0.24,1.05]","0.607 [0.47,0.76]"
10,R135,,3,3/6,"0.491 [0.16,0.82]","0.011 [0.00,0.02]","0.500 [0.17,0.83]","13.322 [12.95,13.75]","1.092 [0.74,1.44]","0.780 [0.37,1.28]","0.296 [0.16,0.44]","0.985 [0.97,1.00]"
11,R145,,3,2/6,"0.326 [0.00,0.65]","0.009 [0.00,0.02]","0.666 [0.33,1.00]","13.420 [12.88,13.96]","1.236 [0.92,1.54]","0.566 [0.28,0.89]","0.246 [0.10,0.40]","0.985 [0.97,1.00]"
12,R234,,3,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.509 [1.43,1.58]","0.165 [0.15,0.18]","0.995 [0.62,1.37]","0.845 [0.72,0.92]"
13,R235,,3,6/6,"0.975 [0.97,0.98]","0.032 [0.02,0.04]","0.000 [0.00,0.00]","15.213 [14.50,16.09]","0.645 [0.61,0.69]","1.053 [0.89,1.22]","0.467 [0.42,0.51]","0.980 [0.97,0.99]"
14,R245,,3,5/6,"0.795 [0.47,0.96]","0.041 [0.02,0.06]","0.168 [0.00,0.50]","15.793 [14.71,17.01]","0.783 [0.60,1.10]","0.997 [0.65,1.31]","0.406 [0.28,0.49]","0.990 [0.98,1.00]"
15,R345,,3,1/6,"0.164 [0.00,0.49]","0.004 [0.00,0.01]","0.833 [0.50,1.00]","15.916 [15.92,15.92]","1.413 [1.13,1.57]","0.353 [0.25,0.53]","0.174 [0.09,0.30]","0.998 [0.99,1.00]"
16,R12,B2_goal+dist,2,2/6,"0.281 [0.00,0.61]","0.017 [0.00,0.04]","0.703 [0.37,1.00]","18.566 [16.90,20.23]","1.242 [0.96,1.50]","0.486 [0.21,0.83]","1.174 [0.65,1.79]","0.828 [0.70,0.91]"
17,R13,,2,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.618 [1.57,1.65]","0.170 [0.15,0.19]","0.473 [0.24,0.79]","0.601 [0.46,0.76]"
18,R14,,2,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.636 [1.63,1.64]","0.173 [0.16,0.19]","0.346 [0.24,0.50]","0.582 [0.48,0.71]"
19,R15,,2,3/6,"0.494 [0.16,0.83]","0.007 [0.00,0.01]","0.500 [0.17,0.83]","13.078 [12.80,13.28]","1.062 [0.72,1.40]","0.923 [0.48,1.40]","0.308 [0.16,0.47]","0.978 [0.96,0.99]"
20,R23,,2,0/6,"0.016 [0.00,0.05]","0.000 [0.00,0.00]","0.984 [0.95,1.00]","23.672 [23.67,23.67]","1.451 [1.35,1.56]","0.183 [0.17,0.21]","0.849 [0.58,1.10]","0.858 [0.80,0.91]"
21,R24,,2,1/6,"0.110 [0.00,0.33]","0.005 [0.00,0.02]","0.885 [0.66,1.00]","21.185 [21.18,21.18]","1.446 [1.23,1.58]","0.257 [0.17,0.39]","1.109 [0.75,1.38]","0.848 [0.79,0.89]"
22,R25,B7_dist+jerk,2,6/6,"0.967 [0.96,0.97]","0.040 [0.03,0.05]","0.000 [0.00,0.00]","15.663 [15.14,16.08]","0.650 [0.61,0.68]","1.029 [0.89,1.17]","0.499 [0.48,0.52]","0.982 [0.98,0.99]"
23,R34,,2,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.624 [1.59,1.65]","0.155 [0.14,0.17]","0.533 [0.24,1.05]","0.607 [0.47,0.76]"
24,R35,,2,3/6,"0.487 [0.16,0.82]","0.017 [0.00,0.03]","0.500 [0.17,0.83]","15.598 [14.79,16.93]","1.125 [0.79,1.45]","0.622 [0.33,0.94]","0.289 [0.15,0.43]","0.991 [0.98,1.00]"
25,R45,,2,2/6,"0.321 [0.00,0.64]","0.013 [0.00,0.03]","0.666 [0.33,1.00]","15.641 [14.69,16.59]","1.253 [0.93,1.54]","0.542 [0.28,0.90]","0.220 [0.10,0.37]","0.992 [0.98,1.00]"
26,R1,B1_goal-only,1,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.619 [1.60,1.63]","0.194 [0.17,0.21]","0.524 [0.26,0.95]","0.658 [0.51,0.81]"
27,R2,B6_dist-only,1,2/6,"0.248 [0.00,0.56]","0.014 [0.00,0.03]","0.738 [0.40,1.00]","18.444 [15.96,20.93]","1.255 [1.00,1.50]","0.417 [0.21,0.67]","1.136 [0.58,1.75]","0.833 [0.71,0.92]"
28,R3,,1,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.618 [1.57,1.65]","0.170 [0.15,0.19]","0.473 [0.24,0.79]","0.601 [0.46,0.76]"
29,R4,,1,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.636 [1.63,1.64]","0.173 [0.16,0.19]","0.346 [0.24,0.50]","0.582 [0.48,0.71]"
30,R5,,1,3/6,"0.486 [0.16,0.82]","0.016 [0.00,0.03]","0.500 [0.17,0.83]","15.405 [14.43,16.80]","1.102 [0.78,1.42]","0.692 [0.41,0.99]","0.283 [0.15,0.43]","0.992 [0.99,1.00]"
31,R0_none,Z_task-only,0,0/6,"0.000 [0.00,0.00]","0.000 [0.00,0.00]","1.000 [1.00,1.00]","nan [nan,nan]","1.619 [1.60,1.63]","0.194 [0.17,0.21]","0.524 [0.26,0.95]","0.658 [0.51,0.81]"

Median [IQR] -- the honest summary when an arm is bimodal across seeds:

,arm,alias,success,collision,timeout,mean_sq_accel
0,R12345,R1-5_full,0.983 [0.005],0.020 [0.005],0.000 [0.000],0.498 [0.026]
1,R1234,A5_no-jerk,0.000 [0.000],0.000 [0.000],1.000 [0.000],1.037 [0.775]
2,R1235,A4_no-ttc,0.984 [0.015],0.018 [0.019],0.000 [0.000],0.500 [0.046]
3,R1245,A3_no-space,0.972 [0.012],0.033 [0.015],0.000 [0.000],0.543 [0.045]
4,R1345,A2_no-distance,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.147 [0.099]
5,R2345,A1_no-goal,0.976 [0.002],0.031 [0.006],0.000 [0.000],0.500 [0.069]
6,R123,B4_goal+dist+space,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.868 [0.505]
7,R124,B5_goal+dist+ttc,0.000 [0.000],0.000 [0.002],1.000 [0.002],1.214 [0.392]
8,R125,B3_goal+dist+jerk,0.973 [0.011],0.029 [0.013],0.000 [0.000],0.474 [0.068]
9,R134,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.305 [0.135]
10,R135,,0.485 [0.979],0.004 [0.021],0.500 [1.000],0.278 [0.374]
11,R145,,0.000 [0.728],0.002 [0.013],0.998 [0.751],0.100 [0.332]
12,R234,,0.000 [0.000],0.000 [0.000],1.000 [0.000],1.037 [0.775]
13,R235,,0.974 [0.020],0.034 [0.017],0.000 [0.000],0.484 [0.070]
14,R245,,0.951 [0.019],0.046 [0.022],0.000 [0.005],0.445 [0.046]
15,R345,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.099 [0.080]
16,R12,B2_goal+dist,0.000 [0.532],0.003 [0.021],0.997 [0.583],0.860 [0.982]
17,R13,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.298 [0.362]
18,R14,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.280 [0.094]
19,R15,,0.491 [0.990],0.005 [0.011],0.500 [1.000],0.289 [0.427]
20,R23,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.868 [0.505]
21,R24,,0.000 [0.000],0.000 [0.002],1.000 [0.002],1.214 [0.283]
22,R25,B7_dist+jerk,0.965 [0.007],0.039 [0.005],0.000 [0.000],0.507 [0.035]
23,R34,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.305 [0.135]
24,R35,,0.479 [0.974],0.012 [0.027],0.500 [1.000],0.259 [0.348]
25,R45,,0.000 [0.720],0.002 [0.027],0.998 [0.751],0.100 [0.210]
26,R1,B1_goal-only,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.377 [0.192]
27,R2,B6_dist-only,0.000 [0.404],0.003 [0.023],0.997 [0.425],0.792 [1.085]
28,R3,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.298 [0.362]
29,R4,,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.280 [0.094]
30,R5,,0.477 [0.969],0.009 [0.027],0.500 [1.000],0.269 [0.351]
31,R0_none,Z_task-only,0.000 [0.000],0.000 [0.000],1.000 [0.000],0.377 [0.192]

Success as a function of HOW MANY components are active:

    mean    min    max  count
k
0  0.000  0.000  0.000      1
1  0.147  0.000  0.486      5
2  0.268  0.000  0.967     10
3  0.390  0.000  0.975     10
4  0.586  0.000  0.978      5
5  0.983  0.983  0.983      1

====================================================================================================
|| FIRST READING OF THE LATTICE
----------------------------------------------------------------------------------------------------
   The table above is the complete experiment: 32 reward designs, six seeds each, all
   trained on an identical budget and evaluated on identical scenarios.

   Read the 'solved' column before the means.  A mean of 0.5 can mean 'every seed reached
   0.5' or 'three seeds reached 1.0 and three reached 0.0'.  Those are completely different
   claims about a reward design and only the fraction-of-seeds column separates them.

   The by-size table is the first real finding: if performance were a function of HOW MANY
   terms are switched on, the min and max within each row would be close together.  Where
   they are far apart, it is WHICH terms are on that decides the outcome -- which is exactly
   what an ablation is supposed to establish, and exactly what a leave-one-out design
   assumes rather than tests.
====================================================================================================
  [budget] stage A evaluation         done at  7.53 h |  1.30 h left

## 10 · The conventional view: leave-one-out

This is the table the literature reports, and the one earlier versions of this study reported. It is presented first so the rest of the notebook can be read as a critique of it.

Each arm drops exactly one component from the full reward and is compared to the reference on the same scenarios. Two levels of inference:

- **Seed-level (primary).** The seed is the unit of randomisation, so it is the unit of analysis. We use an **exact sign-flip permutation test**: with six seeds all $2^6=64$ sign assignments are enumerated, so the $p$-value is exact rather than asymptotic, and the smallest attainable two-sided value is $2/64=0.031$.
- **Scenario-paired (secondary).** Episodes paired by scenario seed, Wilcoxon signed-rank, Holm–Bonferroni corrected. This has far more power but treats the particular mixture of trained seeds as fixed, so it answers "on these crowds, with these policies, is behaviour different?" rather than "would this reward design work if I retrained it?".

Reporting only the second is how deep-RL papers manufacture $p \approx 10^{-45}$ from five training runs.

In [17]:
from scipy.stats import wilcoxon

LOO_PRESENT = [a for a in LOO_ARMS if a in LATTICE_ARMS]
loo_rows = []
ref_run = per_run_A[per_run_A.config == REFERENCE].set_index("seed")
for arm in LOO_PRESENT:
    if arm == REFERENCE:
        continue
    cur = per_run_A[per_run_A.config == arm].set_index("seed")
    common = sorted(set(ref_run.index) & set(cur.index))
    if len(common) < 2:
        continue
    dropped = [c for c, on in zip(COMPONENT_IDS, ABLATION_CONFIGS[REFERENCE]) if on and
               not ABLATION_CONFIGS[arm][COMPONENT_IDS.index(c)]]
    for m in HEADLINE:
        a = cur.loc[common, m].to_numpy(float)
        r = ref_run.loc[common, m].to_numpy(float)
        d = a - r
        loo_rows.append({
            "arm": arm, "alias": ALIASES.get(arm, ""),
            "dropped": dropped[0] if dropped else "-",
            "metric": m, "n_seeds": len(common),
            "reference": float(np.nanmean(r)), "arm_mean": float(np.nanmean(a)),
            "delta": float(np.nanmean(d)),
            "p_signflip": AS.sign_flip_test(d),
            "cliffs_delta": AS.cliffs_delta(a, r),
        })
loo_tbl = pd.DataFrame(loo_rows)
if len(loo_tbl) == 0:
    print("!! No leave-one-out arm shares at least two seeds with the reference, so the")
    print("   seed-level tests below are skipped.  This happens only when training runs")
    print("   are missing -- check the stage-A output above.")
    _succ = pd.DataFrame(columns=["arm", "alias", "dropped", "reference", "arm_mean",
                                  "delta", "cliffs_delta", "p_signflip", "p_holm"])
    eq_tbl = pd.DataFrame(columns=["arm", "alias", "dropped", "delta_success", "tost_p",
                                   "ci90_lo", "ci90_hi", "equivalent_to_reference"])
else:
    for m, g in loo_tbl.groupby("metric"):
        loo_tbl.loc[g.index, "p_holm"] = AS.holm_bonferroni(g["p_signflip"].fillna(1.0).values)
    loo_tbl.to_csv(f"{OUT}/tables/leave_one_out_tests.csv", index=False)

    _succ = loo_tbl[loo_tbl.metric == "success"].copy()
    print("LEAVE-ONE-OUT vs the full reward, SUCCESS RATE  (seed-level, exact sign-flip test)")
    display(_succ[["arm", "alias", "dropped", "reference", "arm_mean", "delta",
                   "cliffs_delta", "p_signflip", "p_holm"]].round(4))

# ---- equivalence testing: null results must be CLAIMED, not inferred -------
eq_rows = []
for _, r in (_succ.iterrows() if len(_succ) else []):
    cur = per_run_A[per_run_A.config == r["arm"]].set_index("seed")
    common = sorted(set(ref_run.index) & set(cur.index))
    d = cur.loc[common, "success"].to_numpy(float) - ref_run.loc[common, "success"].to_numpy(float)
    p_eq, lo, hi = AS.tost_equivalence(d, EQUIV_MARGIN)
    eq_rows.append({"arm": r["arm"], "alias": r["alias"], "dropped": r["dropped"],
                    "delta_success": float(np.mean(d)),
                    "tost_p": p_eq, "ci90_lo": lo, "ci90_hi": hi,
                    "equivalent_to_reference": bool(p_eq < 0.05)})
if eq_rows:
    eq_tbl = pd.DataFrame(eq_rows)
    eq_tbl.to_csv(f"{OUT}/tables/equivalence_tests.csv", index=False)
    print(f"\nEQUIVALENCE (TOST) against a PRE-DECLARED margin of +/-{EQUIV_MARGIN} success.")
    print("'equivalent' means we can positively claim the component does not matter for")
    print("success, not merely that we failed to find that it does.")
    display(eq_tbl.round(4))

_dead = _succ[_succ.arm_mean < 0.1]["dropped"].tolist() if len(_succ) else []
_equiv = (eq_tbl[eq_tbl.equivalent_to_reference]["dropped"].tolist()
          if len(eq_tbl) else [])
narrate("WHAT LEAVE-ONE-OUT SAYS -- AND WHAT IT CANNOT SAY", [
    f"Dropping {', '.join(_dead) if _dead else '(no single component)'} from the full reward "
    f"collapses the policy to near-zero success.",
    f"Dropping {', '.join(_equiv) if _equiv else '(none)'} is statistically EQUIVALENT to the "
    f"full reward within +/-{EQUIV_MARGIN} success -- a positive claim of no effect, not an "
    f"absence of evidence.",
    "",
    "This is where most reward-ablation papers stop, and it is where the interpretation goes",
    "wrong.  A leave-one-out number answers 'what does this component add on top of the other",
    "four?'.  It is one number from one context, and it is STRUCTURALLY BLIND to substitutes:",
    "if two components encode overlapping information, dropping either alone costs nothing",
    "because the other covers for it, and leave-one-out reports 0.00 for both.  The unit test",
    "in section 4 demonstrates that failure on a game whose true answer is known analytically.",
    "",
    "Sections 11 and 12 replace this single-context number with an average over all 16",
    "contexts, and then decompose what is left into explicit interaction terms.",
])

LEAVE-ONE-OUT vs the full reward, SUCCESS RATE  (seed-level, exact sign-flip test)

,arm,alias,dropped,reference,arm_mean,delta,cliffs_delta,p_signflip,p_holm
0,R2345,A1_no-goal,R1,0.9827,0.9747,-0.0080,-0.7222,0.0625,0.2500
10,R1345,A2_no-distance,R2,0.9827,0.1650,-0.8177,-0.6667,0.0625,0.2500
20,R1245,A3_no-space,R3,0.9827,0.8110,-0.1717,-0.6944,0.1250,0.2500
30,R1235,A4_no-ttc,R4,0.9827,0.9783,-0.0043,-0.1111,0.3125,0.3125
40,R1234,A5_no-jerk,R5,0.9827,0.0000,-0.9827,-1.0000,0.0312,0.1562

EQUIVALENCE (TOST) against a PRE-DECLARED margin of +/-0.02 success.
'equivalent' means we can positively claim the component does not matter for
success, not merely that we failed to find that it does.

,arm,alias,dropped,delta_success,tost_p,ci90_lo,ci90_hi,equivalent_to_reference
0,R2345,A1_no-goal,R1,-0.0080,0.0028,-0.0132,-0.0028,True
1,R1345,A2_no-distance,R2,-0.8177,0.9976,-1.1504,-0.4849,False
2,R1245,A3_no-space,R3,-0.1717,0.8043,-0.4976,0.1542,False
3,R1235,A4_no-ttc,R4,-0.0043,0.0017,-0.0103,0.0017,True
4,R1234,A5_no-jerk,R5,-0.9827,1.0000,-0.9862,-0.9791,False

====================================================================================================
|| WHAT LEAVE-ONE-OUT SAYS -- AND WHAT IT CANNOT SAY
----------------------------------------------------------------------------------------------------
   Dropping R5 from the full reward collapses the policy to near-zero success.
   Dropping R1, R4 is statistically EQUIVALENT to the full reward within +/-0.02 success -- a
   positive claim of no effect, not an absence of evidence.

   This is where most reward-ablation papers stop, and it is where the interpretation goes
   wrong.  A leave-one-out number answers 'what does this component add on top of the other
   four?'.  It is one number from one context, and it is STRUCTURALLY BLIND to substitutes:
   if two components encode overlapping information, dropping either alone costs nothing
   because the other covers for it, and leave-one-out reports 0.00 for both.  The unit test
   in section 4 demonstrates that failure on a game whose true answer is known analytically.

   Sections 11 and 12 replace this single-context number with an average over all 16
   contexts, and then decompose what is left into explicit interaction terms.
====================================================================================================

## 11 · Exact component attribution over the whole lattice

With all 32 cells measured we no longer have to choose a context. For a value function $v(S)$ — the mean success rate of a policy trained with component subset $S$ — define

$$\phi_i \;=\; \sum_{S\subseteq N\setminus\{i\}} \frac{|S|!\,(n-|S|-1)!}{n!}\Big[v(S\cup\{i\})-v(S)\Big].$$

This is the **Shapley value**: component $i$'s marginal contribution averaged over every possible context, with the unique weighting that satisfies

- **efficiency** — $\sum_i\phi_i = v(N)-v(\varnothing)$, so the credits add up to exactly what the full reward achieves over the bare task reward, with nothing unattributed;
- **symmetry** — two components that contribute identically in every context get identical credit;
- **null player** — a component that adds nothing anywhere gets exactly zero;
- **linearity** — attribution on a sum of metrics is the sum of the attributions.

We compute it **exactly** (no sampling approximation) and **independently within each training seed**, then treat the six seeds as the sample. Inference is by exact sign-flip permutation test and percentile bootstrap.

Three numbers are reported per component so the reader can see the disagreement for themselves:

| quantity | question it answers |
|---|---|
| $\mathrm{AOI}(i)=v(\{i\})-v(\varnothing)$ | what does this component achieve **alone**? |
| $\phi_i$ | what does it contribute **on average over all contexts**? |
| $\mathrm{LOO}(i)=v(N)-v(N\setminus\{i\})$ | what does it add **on top of all the others**? |

Where the three agree, the component's effect is context-free and the conventional ablation was telling the truth. Where they diverge, the conventional ablation was reporting a property of its context.

In [18]:
from itertools import combinations

def _arm_from_indices(S):
    return lattice_name(tuple(i in S for i in range(5)))

SHAPLEY_METRICS = ["success", "collision", "min_separation", "intrusion_count",
                   "nav_time_succ", "mean_sq_accel", "action_autocorr"]
COMP_LABELS = [f"{cid}\n{nm}" for cid, nm in zip(COMPONENT_IDS, COMPONENT_NAMES)]

analyses, attrib_rows = {}, []
LATTICE_COMPLETE = (len(LATTICE_ARMS) == 32 and
                    set(LATTICE_ARMS).issubset(set(per_run_A["config"].unique())))
if not LATTICE_COMPLETE:
    print("The lattice is incomplete (QUICK_TEST, or some arms have no trained policy),")
    print("so exact Shapley attribution is skipped -- it requires all 32 cells.")
    print("Everything downstream that does not need the full lattice still runs.")
else:
    for metric in SHAPLEY_METRICS:
        pr = per_run_A.copy()
        # nav_time is undefined for an arm that never succeeds; carrying NaN into
        # the lattice would silently drop whole seeds.  Impute the time limit,
        # which is the honest value: the policy used the entire horizon.
        if metric == "nav_time_succ":
            pr[metric] = pr[metric].fillna(_probe.time_limit)
        tables, dropped = AS.lattice_table(pr, metric, _arm_from_indices, n=5)
        if not tables:
            print(f"  {metric}: no seed has a complete lattice -- skipped"); continue
        if dropped:
            print(f"  {metric}: seeds dropped for an incomplete lattice: {dropped}")
        A = AS.component_analysis(tables, n=5, n_boot=N_BOOT)
        A["tables"] = tables
        analyses[metric] = A
        for i, cid in enumerate(COMPONENT_IDS):
            attrib_rows.append({
                "metric": metric, "component": cid, "name": COMPONENT_NAMES[i],
                "shapley": A["shapley"][i]["mean"],
                "shapley_lo": A["shapley"][i]["lo"], "shapley_hi": A["shapley"][i]["hi"],
                "shapley_p": A["shapley"][i]["p"],
                "loo": A["loo"][i]["mean"], "loo_p": A["loo"][i]["p"],
                "aoi": A["aoi"][i]["mean"], "aoi_p": A["aoi"][i]["p"],
                "n_seeds": A["n_seeds"],
            })

attrib = pd.DataFrame(attrib_rows)
if len(attrib):
    for m, g in attrib.groupby("metric"):
        attrib.loc[g.index, "shapley_p_holm"] = AS.holm_bonferroni(g["shapley_p"].values)
    attrib.to_csv(f"{OUT}/tables/component_attribution.csv", index=False)

    A = analyses["success"]
    print("=" * 112)
    print(f"COMPONENT ATTRIBUTION ON SUCCESS RATE   (exact, over all 32 cells, "
          f"{A['n_seeds']} seeds)")
    print("=" * 112)
    hdr = (f"{'':4s} {'component':20s} {'Shapley phi_i':>26s} {'p':>7s} "
           f"{'leave-one-out':>15s} {'add-one-in':>13s}")
    print(hdr); print("-" * 112)
    for i, cid in enumerate(COMPONENT_IDS):
        s, l, a = A["shapley"][i], A["loo"][i], A["aoi"][i]
        print(f"{cid:4s} {COMPONENT_NAMES[i]:20s} "
              f"{s['mean']:+8.4f} [{s['lo']:+.4f},{s['hi']:+.4f}] {s['p']:7.4f} "
              f"{l['mean']:+15.4f} {a['mean']:+13.4f}")
    print("-" * 112)
    print(f"{'':4s} {'SUM':20s} {sum(r['mean'] for r in A['shapley']):+8.4f}"
          f"{'':20s}   (efficiency: must equal v(full) - v(task-only) = "
          f"{A['total_mean']:+.4f})")
    print(f"     efficiency residual {A['efficiency_residual']:.2e}   "
          f"(exact arithmetic; not a fit)")

    _order = np.argsort([-A["shapley"][i]["mean"] for i in range(5)])
    _rank = ", ".join(f"{COMPONENT_IDS[i]} ({A['shapley'][i]['mean']:+.3f})" for i in _order)
    _sig = [COMPONENT_IDS[i] for i in range(5) if A["shapley"][i]["p"] < 0.05]
    _flip = [(COMPONENT_IDS[i], A["loo"][i]["mean"], A["shapley"][i]["mean"])
             for i in range(5)
             if abs(A["loo"][i]["mean"] - A["shapley"][i]["mean"]) > 0.10]
    narrate("COMPONENT ATTRIBUTION -- THE HEADLINE RESULT", [
        f"Ranked by Shapley value on success rate:  {_rank}",
        f"Distinguishable from zero at the 5% level (exact sign-flip, {A['n_seeds']} seeds): "
        f"{', '.join(_sig) if _sig else 'none'}.",
        "",
        "The three columns are three different questions and they do not have to agree.",
        ("Components where leave-one-out and the Shapley value disagree by more than 0.10 "
         "success: " + (", ".join(f"{c} (LOO {l:+.3f} vs phi {p:+.3f})" for c, l, p in _flip)
                        if _flip else "none -- attribution is context-free here.")),
        "",
        "Where LOO is much LARGER than phi, the component is load-bearing only once everything",
        "else is present: it is a keystone, not a workhorse, and a paper that reports LOO alone",
        "will overstate how much of the result it carries.",
        "Where LOO is much SMALLER than phi, the component does real work but something else in",
        "the full set is covering for it -- the signature of substitutes, which section 12",
        "measures directly.",
        "",
        "Efficiency is worth emphasising for the write-up: these five numbers SUM EXACTLY to the",
        "difference between the full reward and the bare task reward.  Nothing is left",
        "unattributed and nothing is double-counted.  That is a property of the Shapley value,",
        "not of our implementation, and it is why the credits can be quoted as shares.",
    ])

================================================================================================================
COMPONENT ATTRIBUTION ON SUCCESS RATE   (exact, over all 32 cells, 6 seeds)
================================================================================================================
     component                         Shapley phi_i       p   leave-one-out    add-one-in
----------------------------------------------------------------------------------------------------------------
R1   goal reaching         +0.0066 [+0.0017,+0.0129]  0.0625         +0.0080       +0.0000
R2   distance shaping      +0.4004 [+0.2090,+0.5716]  0.0625         +0.8177       +0.2480
R3   personal space        -0.0014 [-0.0787,+0.1044]  1.0000         +0.1717       +0.0000
R4   time-to-collision     -0.0662 [-0.1507,-0.0062]  0.1875         +0.0043       +0.0000
R5   jerk / smoothness     +0.6431 [+0.4626,+0.8370]  0.0312         +0.9827       +0.4863
----------------------------------------------------------------------------------------------------------------
     SUM                   +0.9827                       (efficiency: must equal v(full) - v(task-only) = +0.9827)
     efficiency residual 1.11e-16   (exact arithmetic; not a fit)

====================================================================================================
|| COMPONENT ATTRIBUTION -- THE HEADLINE RESULT
----------------------------------------------------------------------------------------------------
   Ranked by Shapley value on success rate:  R5 (+0.643), R2 (+0.400), R1 (+0.007), R3 (-0.001),
   R4 (-0.066)
   Distinguishable from zero at the 5% level (exact sign-flip, 6 seeds): R5.

   The three columns are three different questions and they do not have to agree.
   Components where leave-one-out and the Shapley value disagree by more than 0.10 success: R2
   (LOO +0.818 vs phi +0.400), R3 (LOO +0.172 vs phi -0.001), R5 (LOO +0.983 vs phi +0.643)

   Where LOO is much LARGER than phi, the component is load-bearing only once everything
   else is present: it is a keystone, not a workhorse, and a paper that reports LOO alone
   will overstate how much of the result it carries.
   Where LOO is much SMALLER than phi, the component does real work but something else in
   the full set is covering for it -- the signature of substitutes, which section 12
   measures directly.

   Efficiency is worth emphasising for the write-up: these five numbers SUM EXACTLY to the
   difference between the full reward and the bare task reward.  Nothing is left
   unattributed and nothing is double-counted.  That is a property of the Shapley value,
   not of our implementation, and it is why the credits can be quoted as shares.
====================================================================================================

In [19]:
if LATTICE_COMPLETE and analyses:
    print("ATTRIBUTION ACROSS ALL REPORTED METRICS (Shapley value, seed-mean)")
    piv = attrib.pivot_table(index="component", columns="metric", values="shapley")
    piv = piv.reindex(list(COMPONENT_IDS))[SHAPLEY_METRICS]
    display(piv.round(4))
    print("\nSame table, p-values (exact sign-flip, Holm-corrected within each metric):")
    pivp = attrib.pivot_table(index="component", columns="metric", values="shapley_p_holm")
    display(pivp.reindex(list(COMPONENT_IDS))[SHAPLEY_METRICS].round(4))

    _safety = [c for c in COMPONENT_IDS
               if (attrib[(attrib.component == c) & (attrib.metric == "min_separation")]
                   ["shapley"].iloc[0] > 0.01)]
    narrate("WHY ONE METRIC IS NOT ENOUGH", [
        "A component can be worth nothing for SUCCESS and still be the reason the robot keeps",
        "its distance.  Success rate is a safety-critical binary; social compliance is not",
        "binary and does not show up in it at all.",
        "",
        f"Components with a positive Shapley value on MINIMUM SEPARATION: "
        f"{', '.join(_safety) if _safety else 'none'}.",
        "",
        "If a component earns ~0 on success but a clear positive on separation and a clear",
        "negative on intrusion count, the correct sentence for the paper is not 'it does not",
        "matter'.  It is: this term buys proxemic comfort at no measurable cost in task",
        "performance -- which, for a SOCIALLY AWARE navigation policy, is the point of having",
        "it.  A success-only ablation table cannot make that statement and would delete the",
        "term.",
    ])

ATTRIBUTION ACROSS ALL REPORTED METRICS (Shapley value, seed-mean)

metric,success,collision,min_separation,intrusion_count,nav_time_succ,mean_sq_accel,action_autocorr
component,,,,,,,
R1,0.0066,-0.0045,-0.0256,0.0948,-0.7971,0.0053,-0.0053
R2,0.4004,0.0142,-0.4404,0.3372,-4.1232,0.4132,0.0993
R3,-0.0014,-0.0045,0.0085,-0.0716,-0.0696,-0.0223,-0.0109
R4,-0.0662,-0.0027,0.0786,-0.0898,0.7651,-0.0435,-0.0175
R5,0.6431,0.0178,-0.6210,0.6640,-7.0131,-0.3762,0.2459

Same table, p-values (exact sign-flip, Holm-corrected within each metric):

metric,success,collision,min_separation,intrusion_count,nav_time_succ,mean_sq_accel,action_autocorr
component,,,,,,,
R1,0.2500,0.2812,0.1562,0.2500,0.1562,1.0000,0.1875
R2,0.2500,0.1562,0.1562,0.2500,0.1875,0.1562,0.1562
R3,1.0000,0.3125,0.8750,0.3750,0.9062,1.0000,0.7812
R4,0.3750,0.3125,0.1562,0.2500,0.3750,1.0000,0.7500
R5,0.1562,0.1562,0.1562,0.1562,0.1562,0.1562,0.1562

====================================================================================================
|| WHY ONE METRIC IS NOT ENOUGH
----------------------------------------------------------------------------------------------------
   A component can be worth nothing for SUCCESS and still be the reason the robot keeps
   its distance.  Success rate is a safety-critical binary; social compliance is not
   binary and does not show up in it at all.

   Components with a positive Shapley value on MINIMUM SEPARATION: R4.

   If a component earns ~0 on success but a clear positive on separation and a clear
   negative on intrusion count, the correct sentence for the paper is not 'it does not
   matter'.  It is: this term buys proxemic comfort at no measurable cost in task
   performance -- which, for a SOCIALLY AWARE navigation policy, is the point of having
   it.  A success-only ablation table cannot make that statement and would delete the
   term.
====================================================================================================

## 12 · Interaction structure — substitutes, complements, and why LOO lied

The Möbius (Harsanyi) transform of the same value function,

$$m(S)=\sum_{T\subseteq S}(-1)^{|S\setminus T|}v(T),$$

decomposes the lattice into a dividend for every coalition: singletons are pure main effects, pairs are two-way interactions, and so on. The **Shapley interaction index** aggregates these into one number per pair:

$$I(i,j)=\sum_{T\supseteq\{i,j\}} \frac{m(T)}{|T|-1}.$$

The sign is the whole story:

- $I(i,j) < 0$ — **substitutes**. The pair covers the same ground. Having both is worth less than the sum of having each. *This is the configuration in which leave-one-out reports a false null for both components*, because dropping either one alone leaves the other to cover.
- $I(i,j) > 0$ — **complements**. The pair is worth more together than apart; each is a precondition for the other to pay off.

**A note on the $p$-values in this table.** There are ten pairs, and with six seeds the smallest attainable exact two-sided $p$ is $2/64=0.031$. Holm–Bonferroni over ten simultaneous comparisons therefore *cannot* return a significant adjusted value no matter how large the effect — $10\times0.031=0.31$ is the floor. The corrected column is reported for completeness and should not be read as the test. **The primary criterion for classifying a pair is whether its bootstrap interval excludes zero**, which is what the `kind` column uses; the raw $p$ is reported alongside it. This is a real limit of a six-seed design, not a property of the data, and the write-up should say so rather than quietly dropping the correction.

This section is what converts "three of the five matter" into an explanation of *why* the other two appear not to.

In [20]:
if LATTICE_COMPLETE and analyses:
    A = analyses["success"]
    inter_rows = []
    for (i, j), row in zip(A["interaction_pairs"], A["interaction"]):
        inter_rows.append({
            "pair": f"{COMPONENT_IDS[i]}x{COMPONENT_IDS[j]}",
            "i": COMPONENT_IDS[i], "j": COMPONENT_IDS[j],
            "interaction": row["mean"], "lo": row["lo"], "hi": row["hi"],
            "p": row["p"],
            "kind": ("substitutes" if row["hi"] < 0 else
                     "complements" if row["lo"] > 0 else "indistinguishable"),
        })
    inter = pd.DataFrame(inter_rows).sort_values("interaction")
    inter["p_holm"] = AS.holm_bonferroni(inter["p"].values)
    inter.to_csv(f"{OUT}/tables/interactions.csv", index=False)
    print("PAIRWISE SHAPLEY INTERACTION INDEX on success rate "
          "(negative = substitutes, positive = complements)")
    display(inter[["pair", "interaction", "lo", "hi", "p", "p_holm", "kind"]].round(4))

    # higher-order dividends worth reporting
    mob = pd.DataFrame({
        "set": ["{" + ",".join(COMPONENT_IDS[i] for i in S) + "}" if S else "{}"
                for S in A["mobius_sets"]],
        "order": [len(S) for S in A["mobius_sets"]],
        "dividend": [r["mean"] for r in A["mobius"]],
        "p": [r["p"] for r in A["mobius"]],
    })
    mob.to_csv(f"{OUT}/tables/mobius_dividends.csv", index=False)
    print("\nLargest Moebius dividends of order >= 2 (the irreducible interaction content):")
    display(mob[mob.order >= 2].reindex(
        mob[mob.order >= 2]["dividend"].abs().sort_values(ascending=False).index)
        .head(10).round(4))

    _sub = inter[inter.kind == "substitutes"]
    _cmp = inter[inter.kind == "complements"]
    _biggest = inter.iloc[0] if len(inter) else None
    narrate("INTERACTION STRUCTURE -- THE EXPLANATION FOR THE NULLS", [
        f"Substitute pairs (negative, CI excludes zero): "
        f"{', '.join(_sub['pair']) if len(_sub) else 'none'}.",
        f"Complementary pairs (positive, CI excludes zero): "
        f"{', '.join(_cmp['pair']) if len(_cmp) else 'none'}.",
        "",
        ("Strongest interaction: " +
         (f"{_biggest['pair']} at {_biggest['interaction']:+.4f} ({_biggest['kind']})."
          if _biggest is not None else "n/a")),
        "",
        "How to state this in the paper.  For every substitute pair, the leave-one-out result",
        "for BOTH members is uninformative by construction: each hides behind the other, so the",
        "single-drop experiment cannot see either.  The correct experiment for a substitute pair",
        "is the JOINT drop, which the lattice contains, and the correct summary statistic is the",
        "Shapley value, which averages over contexts in which the partner is absent.",
        "",
        "For every complementary pair, the opposite warning applies: the components are not",
        "independently tunable.  Removing one does not just cost its own contribution, it also",
        "destroys the partner's.  Reporting a per-component weight sweep for such a pair is",
        "misleading; they have to be swept jointly.",
    ])

PAIRWISE SHAPLEY INTERACTION INDEX on success rate (negative = substitutes, positive = complements)

    pair  interaction      lo      hi       p  p_holm               kind
9  R4xR5      -0.1088 -0.2049 -0.0315  0.0312  0.3125        substitutes
1  R1xR3      -0.0093 -0.0199 -0.0032  0.0312  0.3125        substitutes
3  R1xR5       0.0000 -0.0150  0.0103  1.0000  1.0000  indistinguishable
2  R1xR4       0.0029 -0.0019  0.0078  0.4375  1.0000  indistinguishable
4  R2xR3       0.0105 -0.1964  0.2181  0.6562  1.0000  indistinguishable
0  R1xR2       0.0144 -0.0001  0.0377  0.1875  1.0000  indistinguishable
7  R3xR4       0.0482 -0.0659  0.1864  0.6562  1.0000  indistinguishable
5  R2xR4       0.0620 -0.0542  0.1911  0.5000  1.0000  indistinguishable
8  R3xR5       0.1223 -0.0242  0.2813  0.2500  1.0000  indistinguishable
6  R2xR5       0.4828  0.2048  0.7601  0.0625  0.5000        complements

Largest Moebius dividends of order >= 2 (the irreducible interaction content):

              set  order  dividend       p
23     {R2,R3,R5}      3    0.2403  0.0625
12        {R2,R5}      2    0.2323  0.4688
10        {R2,R3}      2   -0.2320  0.5000
30  {R2,R3,R4,R5}      4    0.2063  0.2812
15        {R4,R5}      2   -0.1650  0.7500
25     {R3,R4,R5}      3   -0.1580  1.0000
11        {R2,R4}      2   -0.1383  1.0000
24     {R2,R4,R5}      3    0.1320  1.0000
22     {R2,R3,R4}      3    0.1223  1.0000
18     {R1,R2,R5}      3   -0.0363  0.3750

====================================================================================================
|| INTERACTION STRUCTURE -- THE EXPLANATION FOR THE NULLS
----------------------------------------------------------------------------------------------------
   Substitute pairs (negative, CI excludes zero): R4xR5, R1xR3.
   Complementary pairs (positive, CI excludes zero): R2xR5.

   Strongest interaction: R4xR5 at -0.1088 (substitutes).

   How to state this in the paper.  For every substitute pair, the leave-one-out result
   for BOTH members is uninformative by construction: each hides behind the other, so the
   single-drop experiment cannot see either.  The correct experiment for a substitute pair
   is the JOINT drop, which the lattice contains, and the correct summary statistic is the
   Shapley value, which averages over contexts in which the partner is absent.

   For every complementary pair, the opposite warning applies: the components are not
   independently tunable.  Removing one does not just cost its own contribution, it also
   destroys the partner's.  Reporting a per-component weight sweep for such a pair is
   misleading; they have to be swept jointly.
====================================================================================================

## 13 · Stage D — is it the *component*, or the *form* of the shaping?

R2 is implemented as **potential-based reward shaping** (PBRS). Ng, Harada & Russell (1999) prove that PBRS leaves the optimal policy unchanged: it can accelerate learning but it *cannot* create goal-directedness that the base reward does not already contain. Most crowd-navigation papers instead use the naive **progress** form $w_{dist}(d_t-d_{t+1})$, which is PBRS with a shaping discount of $1.0$ rather than $\gamma$ — and is therefore **not** policy-invariant: it really does change what the optimal policy is.

That distinction is usually cited, not measured. Here we measure it, holding the component set fixed and changing only the form:

| arm | components | form of R2 |
|---|---|---|
| `R12345` | all five | PBRS (invariant) |
| `P12345_progress` | all five | progress (not invariant) |
| `R2345` | no R1 | PBRS (invariant) |
| `P2345_progress` | no R1 | progress (not invariant) |

The decisive pair is the second one. With no terminal goal bonus at all, a policy-invariant shaping term provably cannot supply goal-directedness, whereas a non-invariant progress term can. §4 check 6 already verified the telescoping identity numerically for both forms; this stage shows what the difference is worth in success rate.

In [21]:
per_run_D = pd.DataFrame(); agg_D = pd.DataFrame()
plan_D = [(c, s) for c in PROGRESS_ARMS for s in SEEDS]
if BUDGET.stage("D  shaping form", len(plan_D), STEPS_PER_RUN, AGG_FPS):
    meta_D = train_many(plan_D, STEPS_PER_RUN, N_ENVS, OUT, device=DEVICE,
                        env_overrides=TRAIN_ENV, n_parallel=N_PARALLEL,
                        verbose=True, net_width=NET_WIDTH)
    pd.DataFrame(meta_D).to_csv(f"{OUT}/tables/training_meta_D.csv", index=False)
    per_run_D, per_ep_D = evaluate_stage(PROGRESS_ARMS, SEEDS, OUT, TEST_SEEDS, TEST_ENV,
                                         n_workers=10, label="(stage D)")
    per_run_D.to_csv(f"{OUT}/tables/per_run_summary_D.csv", index=False)

    CONTRAST = [("R12345", "P12345_progress", "all five components"),
                ("R2345",  "P2345_progress",  "no terminal goal bonus (R1 off)")]
    both = pd.concat([per_run_A, per_run_D], ignore_index=True)
    rows = []
    for pb, pg, label in CONTRAST:
        gb = both[both.config == pb].set_index("seed")
        gg = both[both.config == pg].set_index("seed")
        common = sorted(set(gb.index) & set(gg.index))
        if not common:
            continue
        for m in ["success", "collision", "nav_time_succ", "path_length_ratio_succ"]:
            b = gb.loc[common, m].to_numpy(float); g = gg.loc[common, m].to_numpy(float)
            rows.append({"contrast": label, "metric": m,
                         "pbrs": float(np.nanmean(b)), "progress": float(np.nanmean(g)),
                         "delta_progress_minus_pbrs": float(np.nanmean(g - b)),
                         "p_signflip": AS.sign_flip_test(g - b)})
    form_tbl = pd.DataFrame(rows)
    form_tbl.to_csv(f"{OUT}/tables/shaping_form_contrast.csv", index=False)
    display(form_tbl.round(4))

    _s = form_tbl[(form_tbl.metric == "success")]
    _l1 = _s[_s.contrast.str.startswith("all five")]
    _l2 = _s[_s.contrast.str.startswith("no terminal")]
    narrate("PBRS VS PROGRESS SHAPING", [
        (f"With all five components present: PBRS {_l1.pbrs.iloc[0]:.3f} vs progress "
         f"{_l1.progress.iloc[0]:.3f} success (delta {_l1.delta_progress_minus_pbrs.iloc[0]:+.3f}, "
         f"p={_l1.p_signflip.iloc[0]:.4f})." if len(_l1) else ""),
        (f"With NO terminal goal bonus: PBRS {_l2.pbrs.iloc[0]:.3f} vs progress "
         f"{_l2.progress.iloc[0]:.3f} success (delta {_l2.delta_progress_minus_pbrs.iloc[0]:+.3f}, "
         f"p={_l2.p_signflip.iloc[0]:.4f})." if len(_l2) else ""),
        "",
        "The second row is the theorem made visible rather than cited.  Policy invariance is",
        "usually presented as a guarantee you want; here it is also a LIMITATION you pay for.",
        "A practitioner who needs goal-directedness from their dense term must use the",
        "non-invariant form, and should then say so and report that the optimum has moved,",
        "rather than citing Ng et al. for a term that does not satisfy their conditions.",
        "",
        "Note also the efficiency columns: if the progress arm reaches the goal faster and with",
        "a shorter path at comparable safety, the honest recommendation for a deployed system",
        "is the non-invariant form -- PBRS buys a theorem you may not need.",
    ])
    BUDGET.mark("stage D")
else:
    print("stage D skipped by the budget guard")

  [budget] D  shaping form              12 runs x  500,000 steps ->  0.36 h   left  1.30 h   GO

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

[ 1/12] P12345_progress      seed=3    8.6 min     969 fps   ETA  96.9 min
[ 2/12] P12345_progress      seed=0    8.6 min     966 fps   ETA  44.2 min
[ 3/12] P12345_progress      seed=2    8.6 min     964 fps   ETA  26.6 min
[ 4/12] P12345_progress      seed=1    8.7 min     956 fps   ETA  17.9 min
[ 5/12] P12345_progress      seed=4    8.7 min     954 fps   ETA  24.6 min
[ 6/12] P2345_progress       seed=0    8.8 min     952 fps   ETA  17.6 min
[ 7/12] P12345_progress      seed=5    8.8 min     942 fps   ETA  12.6 min
[ 8/12] P2345_progress       seed=1    8.9 min     941 fps   ETA   8.9 min
[ 9/12] P2345_progress       seed=2    8.7 min     958 fps   ETA   8.7 min
[10/12] P2345_progress       seed=3    8.7 min     956 fps   ETA   5.3 min
[11/12] P2345_progress       seed=4    8.7 min     957 fps   ETA   2.4 min
[12/12] P2345_progress       seed=5    8.7 min     961 fps   ETA   0.0 min

trained 12 runs in 26.5 min on 4 workers
  evaluated 12 runs x 500 scenarios (6,000 episodes) in 1.9 min  (stage D)

,contrast,metric,pbrs,progress,delta_progress_minus_pbrs,p_signflip
0,all five components,success,0.9827,0.9763,-0.0063,0.4375
1,all five components,collision,0.0203,0.0267,0.0063,0.8750
2,all five components,nav_time_succ,13.7622,13.4088,-0.3534,0.4688
3,all five components,path_length_ratio_succ,1.7139,1.6671,-0.0467,0.4688
4,no terminal goal bonus (R1 off),success,0.9747,0.9813,0.0067,0.3750
5,no terminal goal bonus (R1 off),collision,0.0317,0.0213,-0.0103,0.2500
6,no terminal goal bonus (R1 off),nav_time_succ,15.8694,13.8313,-2.0381,0.0312
7,no terminal goal bonus (R1 off),path_length_ratio_succ,1.9761,1.7215,-0.2546,0.0312

====================================================================================================
|| PBRS VS PROGRESS SHAPING
----------------------------------------------------------------------------------------------------
   With all five components present: PBRS 0.983 vs progress 0.976 success (delta -0.006, p=0.4375).
   With NO terminal goal bonus: PBRS 0.975 vs progress 0.981 success (delta +0.007, p=0.3750).

   The second row is the theorem made visible rather than cited.  Policy invariance is
   usually presented as a guarantee you want; here it is also a LIMITATION you pay for.
   A practitioner who needs goal-directedness from their dense term must use the
   non-invariant form, and should then say so and report that the optimum has moved,
   rather than citing Ng et al. for a term that does not satisfy their conditions.

   Note also the efficiency columns: if the progress arm reaches the goal faster and with
   a shorter path at comparable safety, the honest recommendation for a deployed system
   is the non-invariant form -- PBRS buys a theorem you may not need.
====================================================================================================
  [budget] stage D                    done at  8.00 h |  0.83 h left

## 14 · Stage C — *why* is a $0.02$-weighted smoothness term decisive?

This is the study's most surprising claim, and the one a reviewer will attack first. Our hypothesis is that R5 is **not functioning as a comfort term at all**:

> **The temporal-coherence hypothesis.** The action is a velocity in a *goal-aligned* frame. Temporally uncorrelated actions therefore cancel: an untrained policy random-walks on the spot and covers ~2 m of an 8 m journey (measured in §4, check 8), so the terminal goal reward is effectively unreachable by exploration. Among the five components, only R5 rewards temporal coherence. It is therefore acting as an **exploration regulariser** — it buys the agent a policy whose actions persist long enough to go somewhere — and its effect should scale with *action autocorrelation*, not with comfort.

Two experiments test it.

**C1 — dose–response.** If R5 works through a smoothness *preference*, success should rise monotonically with $w_{jerk}$ and then saturate. If it works through exploration, we expect a **non-monotone** curve: too little and the policy never coheres, too much and it is over-damped and cannot manoeuvre around pedestrians. Sweeping three orders of magnitude turns a binary into a curve and distinguishes the two.

**C2 — the causal mechanism control.** We take the failing no-jerk arm and change **nothing about its reward**. Instead the *environment* applies a low-pass filter to the action,

$$a^{\text{eff}}_t=(1-\alpha)\,a_t+\alpha\,a^{\text{eff}}_{t-1},$$

which supplies temporal coherence from the **dynamics**. §4 check 9 already verified that $\alpha=0$ is a bit-exact no-op and that $\alpha>0$ genuinely raises action autocorrelation.

> **Pre-registered prediction:** if the temporal-coherence hypothesis is right, filtering rescues the no-jerk arm — high success with a jerk weight of exactly zero. If R5 is really a comfort preference, filtering changes the *smoothness* of the trajectory but leaves the arm at zero success.

A rescue turns a correlation into a mechanism, and it licenses the word *because* in the paper.

In [22]:
# ---------------- C1: w_jerk dose-response ---------------------------------
jerk_df = pd.DataFrame()
JERK_STEPS = max(MIN_STEPS // 2, STEPS_PER_RUN // 2)
if BUDGET.stage("C1 jerk dose-response", len(JERK_WEIGHTS) * len(JERK_SEEDS),
                JERK_STEPS, AGG_FPS):
    jrows = []
    for w in JERK_WEIGHTS:
        tag = f"JK{w:g}".replace(".", "p")
        jroot = os.path.join(OUT, "stages", "jerk_sweep", tag)
        os.makedirs(os.path.join(jroot, "runs"), exist_ok=True)
        ov = {**TRAIN_ENV, "w_jerk": w, "use_jerk": w > 0}
        jmeta = train_many([(REFERENCE, s) for s in JERK_SEEDS], JERK_STEPS, N_ENVS,
                           jroot, device=DEVICE, env_overrides=ov,
                           n_parallel=N_PARALLEL, verbose=False, net_width=NET_WIDTH)
        pr, _ = evaluate_stage([REFERENCE], JERK_SEEDS, jroot,
                               TEST_SEEDS[:min(250, N_EVAL_EPISODES)],
                               {**TEST_ENV, "w_jerk": w, "use_jerk": w > 0},
                               n_workers=10, verbose=False)
        for _, r in pr.iterrows():
            jrows.append({"w_jerk": w, **r.to_dict()})
        _m = pr["success"].mean() if len(pr) else float("nan")
        print(f"  w_jerk={w:<7g} success={_m:.3f}  "
              f"msa={pr['mean_sq_accel'].mean():.2f}  "
              f"autocorr={pr['action_autocorr'].mean():+.3f}")
    jerk_df = pd.DataFrame(jrows)
    jerk_df.to_csv(f"{OUT}/tables/jerk_dose_response.csv", index=False)
    display(jerk_df.groupby("w_jerk")[["success", "collision", "timeout",
                                       "mean_sq_accel", "action_autocorr",
                                       "displacement_efficiency"]]
            .agg(["mean", "std"]).round(3))
    _g = jerk_df.groupby("w_jerk")["success"].mean()
    _best_w = float(_g.idxmax()); _peak = float(_g.max())
    _monotone = bool(np.all(np.diff(_g.values) >= -0.02))
    narrate("JERK DOSE-RESPONSE", [
        f"Success peaks at w_jerk = {_best_w:g} ({_peak:.3f}) and the curve is "
        f"{'MONOTONE' if _monotone else 'NON-MONOTONE'} in the swept range "
        f"[{min(JERK_WEIGHTS):g}, {max(JERK_WEIGHTS):g}].",
        "",
        "A non-monotone curve is the prediction of the temporal-coherence account and is",
        "inconsistent with a pure smoothness preference: under a preference story more",
        "smoothness can only make the policy's own reward easier to collect, so performance",
        "should saturate rather than decline.  Under the coherence account the term is an",
        "exploration regulariser with an optimum -- too little and actions never persist long",
        "enough to cover ground, too much and the policy is over-damped and cannot manoeuvre",
        "around a pedestrian in the 0.25 s it has.",
        "",
        "Report the whole curve in the paper, not the on/off pair.  It also answers the",
        "practical question a reader will have -- how carefully does this weight have to be",
        "tuned? -- which an on/off ablation cannot.",
    ])
    BUDGET.mark("stage C1")
else:
    print("stage C1 skipped by the budget guard")

  [budget] C1 jerk dose-response        24 runs x  250,000 steps ->  0.36 h   left  0.83 h   GO

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0       success=0.000  msa=0.82  autocorr=+0.796

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.002   success=0.000  msa=0.30  autocorr=+0.994

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.005   success=0.000  msa=0.26  autocorr=+0.995

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.01    success=0.329  msa=0.26  autocorr=+0.995

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.02    success=0.965  msa=0.43  autocorr=+0.986

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.05    success=0.873  msa=0.49  autocorr=+0.988

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.1     success=0.508  msa=0.79  autocorr=+0.969

Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.
Gym has been unmaintained since 2022 and does not support NumPy 2.0 amongst other critical functionality.
Please upgrade to Gymnasium, the maintained drop-in replacement of Gym, or contact the authors of your software and request that they upgrade.
Users of this version of Gym should be able to simply replace 'import gym' with 'import gymnasium as gym' in the vast majority of cases.
See the migration guide at https://gymnasium.farama.org/introduction/migration_guide/ for additional information.

  w_jerk=0.2     success=0.708  msa=0.55  autocorr=+0.981

       success        collision        timeout        mean_sq_accel         \
          mean    std      mean    std    mean    std          mean    std
w_jerk
0.000    0.000  0.000     0.000  0.000   1.000  0.000         0.816  0.557
0.002    0.000  0.000     0.000  0.000   1.000  0.000         0.296  0.167
0.005    0.000  0.000     0.000  0.000   1.000  0.000         0.263  0.135
0.010    0.329  0.570     0.007  0.012   0.667  0.577         0.258  0.117
0.020    0.965  0.028     0.043  0.030   0.000  0.000         0.431  0.104
0.050    0.873  0.027     0.135  0.027   0.000  0.000         0.488  0.013
0.100    0.508  0.447     0.496  0.442   0.000  0.000         0.794  0.578
0.200    0.708  0.059     0.293  0.057   0.000  0.000         0.546  0.046

       action_autocorr        displacement_efficiency
                  mean    std                    mean    std
w_jerk
0.000            0.796  0.131                   0.508  0.426
0.002            0.994  0.005                   0.626  0.260
0.005            0.995  0.004                   0.593  0.282
0.010            0.995  0.005                   0.600  0.160
0.020            0.986  0.010                   0.534  0.014
0.050            0.988  0.008                   0.577  0.038
0.100            0.969  0.032                   0.734  0.199
0.200            0.981  0.008                   0.675  0.037

====================================================================================================
|| JERK DOSE-RESPONSE
----------------------------------------------------------------------------------------------------
   Success peaks at w_jerk = 0.02 (0.965) and the curve is NON-MONOTONE in the swept range [0,
   0.2].

   A non-monotone curve is the prediction of the temporal-coherence account and is
   inconsistent with a pure smoothness preference: under a preference story more
   smoothness can only make the policy's own reward easier to collect, so performance
   should saturate rather than decline.  Under the coherence account the term is an
   exploration regulariser with an optimum -- too little and actions never persist long
   enough to cover ground, too much and the policy is over-damped and cannot manoeuvre
   around a pedestrian in the 0.25 s it has.

   Report the whole curve in the paper, not the on/off pair.  It also answers the
   practical question a reader will have -- how carefully does this weight have to be
   tuned? -- which an on/off ablation cannot.
====================================================================================================
  [budget] stage C1                   done at  8.57 h |  0.26 h left

In [23]:
# ---------------- C2: the causal mechanism control -------------------------
mech_df = pd.DataFrame()
if BUDGET.stage("C2 mechanism control", len(MECHANISM_SPECS) * len(MECHANISM_SEEDS),
                STEPS_PER_RUN, AGG_FPS):
    mrows = []
    for label, arm, extra in MECHANISM_SPECS:
        mroot = os.path.join(OUT, "stages", "mechanism", label.replace(".", "p"))
        os.makedirs(os.path.join(mroot, "runs"), exist_ok=True)
        train_many([(arm, s) for s in MECHANISM_SEEDS], STEPS_PER_RUN, N_ENVS, mroot,
                   device=DEVICE, env_overrides={**TRAIN_ENV, **extra},
                   n_parallel=N_PARALLEL, verbose=False, net_width=NET_WIDTH)
        pr, _ = evaluate_stage([arm], MECHANISM_SEEDS, mroot, TEST_SEEDS,
                               {**TEST_ENV, **extra}, n_workers=10, verbose=False)
        for _, r in pr.iterrows():
            mrows.append({"group": label, "arm": arm,
                          "alpha": extra.get("action_filter_alpha", 0.0),
                          "uses_jerk_reward": bool(ABLATION_CONFIGS[arm][4]),
                          **r.to_dict()})
        print(f"  {label:18s} arm={display_name(arm):24s} "
              f"success={pr['success'].mean():.3f}  "
              f"autocorr={pr['action_autocorr'].mean():+.3f}  "
              f"msa={pr['mean_sq_accel'].mean():.2f}")
    mech_df = pd.DataFrame(mrows)
    # the untouched reference and the plain no-jerk arm from stage A, for context
    _ctx = per_run_A[per_run_A.config.isin([REFERENCE, "R1234"])].copy()
    _ctx["group"] = _ctx["config"].map({REFERENCE: "full reward (stage A)",
                                        "R1234": "no-jerk, no filter (stage A)"})
    _ctx["alpha"] = 0.0
    _ctx["uses_jerk_reward"] = _ctx["config"] == REFERENCE
    _ctx["arm"] = _ctx["config"]
    mech_df = pd.concat([mech_df, _ctx], ignore_index=True)
    mech_df.to_csv(f"{OUT}/tables/mechanism_control.csv", index=False)

    _sum = (mech_df.groupby("group")[["success", "collision", "timeout",
                                      "action_autocorr", "mean_sq_accel",
                                      "displacement_efficiency"]]
            .agg(["mean", "std"]).round(3))
    display(_sum)

    def _mean(g, col="success"):
        v = mech_df[mech_df.group == g][col]
        return float(v.mean()) if len(v) else float("nan")
    _base = _mean("no-jerk, no filter (stage A)")
    _f5, _f8 = _mean("nojerk+filter.5"), _mean("nojerk+filter.8")
    _full = _mean("full reward (stage A)")
    _rescued = max(_f5, _f8) > max(0.25, 0.5 * _full)
    narrate("MECHANISM CONTROL -- THE DECISIVE EXPERIMENT", [
        f"No-jerk arm, no intervention          : success {_base:.3f}",
        f"No-jerk arm + action filter alpha=0.5 : success {_f5:.3f}",
        f"No-jerk arm + action filter alpha=0.8 : success {_f8:.3f}",
        f"Full reward (R5 present, no filter)   : success {_full:.3f}",
        "",
        ("VERDICT: the filter RESCUES the no-jerk arm.  Temporal action coherence was supplied "
         "by the DYNAMICS while the jerk weight stayed at exactly zero, and performance "
         "recovered.  R5's contribution in this task therefore runs through action coherence, "
         "not through a smoothness preference the agent has to be paid to hold -- it is "
         "functioning as an EXPLORATION REGULARISER that happens to be written as a reward."
         if _rescued else
         "VERDICT: the filter does NOT rescue the no-jerk arm.  Temporal coherence alone is "
         "therefore not sufficient, and R5 is contributing something beyond it.  Report this "
         "as a falsified prediction -- it is a stronger result than never having tested it, "
         "and it redirects the explanation toward the reward's effect on the value function "
         "rather than on exploration."),
        "",
        "Either way this is the experiment that licenses a causal claim.  The reward function of",
        "the no-jerk arm is byte-identical to the stage-A no-jerk arm; the only change is a",
        "first-order filter on the action inside the environment, which section 4 check 9",
        "verified is a bit-exact no-op at alpha=0.",
        "",
        "The 'full + filter' row is the control for the control: if coherence is the active",
        "ingredient, adding the filter on top of an arm that already has R5 should be roughly",
        "neutral or mildly harmful (over-damping), not helpful.",
    ])
    BUDGET.mark("stage C2")
else:
    print("stage C2 skipped by the budget guard")

  [budget] C2 mechanism control         12 runs x  500,000 steps ->  0.36 h   left  0.26 h   SKIP (would overrun)
stage C2 skipped by the budget guard

## 15 · Stage B — do the social terms only bind when the crowd binds?

The most likely objection to a null result on R3 (personal space) and R4 (time-to-collision) is that the scenario was too sparse for them to matter: with five pedestrians on an 8 m crossing, a policy can often simply out-run the problem, and a proxemic penalty never activates.

So we re-run the $\{R3,R4\}$ sub-factorial — all four combinations, with R1, R2 and R5 held on — at **double pedestrian density**. Four arms:

| arm | R3 space | R4 ttc |
|---|---|---|
| `R12345` | ✓ | ✓ |
| `R1245` | — | ✓ |
| `R1235` | ✓ | — |
| `R125` | — | — |

This is the smallest design that can separate "the terms are useless" from "the terms are redundant *with each other*" from "the terms only bind at density". Note that it needs its own crowd pool and its own observation dimension ($5+7\times10=75$), so these policies are not comparable to the stage-A ones on any absolute scale — only the *contrasts within* each density are.

In [24]:
density_df = pd.DataFrame()
if BUDGET.stage(f"B  density n={DENSITY_N_HUMANS}", len(DENSITY_ARMS) * len(DENSITY_SEEDS),
                STEPS_PER_RUN, AGG_FPS):
    DENSE_EXP = {**EXPERIMENT, "n_humans": DENSITY_N_HUMANS}
    if not os.path.isdir(DENSITY_POOL_PATH):
        build_crowd_pool(make_cfg(REFERENCE, **DENSE_EXP),
                         range(DENSITY_POOL_BASE, DENSITY_POOL_BASE + DENSITY_POOL_SIZE),
                         DENSITY_POOL_PATH, n_workers=N_PARALLEL)
    if not os.path.isdir(DENSITY_TEST_PATH):
        build_crowd_pool(make_cfg(REFERENCE, **DENSE_EXP), TEST_SEEDS,
                         DENSITY_TEST_PATH, n_workers=N_PARALLEL)
    DTRAIN = {**DENSE_EXP, "crowd_pool_path": DENSITY_POOL_PATH}
    DTEST  = {**DENSE_EXP, "crowd_pool_path": DENSITY_TEST_PATH}

    droot = os.path.join(OUT, "stages", f"density{DENSITY_N_HUMANS}")
    os.makedirs(os.path.join(droot, "runs"), exist_ok=True)
    train_many([(a, s) for a in DENSITY_ARMS for s in DENSITY_SEEDS],
               STEPS_PER_RUN, N_ENVS, droot, device=DEVICE, env_overrides=DTRAIN,
               n_parallel=N_PARALLEL, verbose=True, net_width=NET_WIDTH)
    pr_d, _ = evaluate_stage(DENSITY_ARMS, DENSITY_SEEDS, droot, TEST_SEEDS, DTEST,
                             n_workers=10, label=f"(stage B, n={DENSITY_N_HUMANS})")
    pr_d["n_humans"] = DENSITY_N_HUMANS
    _sparse = per_run_A[per_run_A.config.isin(DENSITY_ARMS) &
                        per_run_A.seed.isin(DENSITY_SEEDS)].copy()
    _sparse["n_humans"] = EXPERIMENT["n_humans"]
    density_df = pd.concat([_sparse, pr_d], ignore_index=True)
    density_df.to_csv(f"{OUT}/tables/density_sweep.csv", index=False)

    _piv = density_df.pivot_table(index="config", columns="n_humans",
                                  values=["success", "collision", "intrusion_count",
                                          "min_separation"], aggfunc="mean")
    display(_piv.reindex(DENSITY_ARMS).round(3))

    def _d(arm, col, n):
        v = density_df[(density_df.config == arm) & (density_df.n_humans == n)][col]
        return float(v.mean()) if len(v) else float("nan")
    nd, ns = DENSITY_N_HUMANS, EXPERIMENT["n_humans"]
    _gap_sparse = _d("R12345", "success", ns) - _d("R125", "success", ns)
    _gap_dense  = _d("R12345", "success", nd) - _d("R125", "success", nd)
    _sep_sparse = _d("R12345", "min_separation", ns) - _d("R125", "min_separation", ns)
    _sep_dense  = _d("R12345", "min_separation", nd) - _d("R125", "min_separation", nd)
    narrate("DENSITY GENERALISATION", [
        f"Joint effect of the two social terms (R3+R4 present minus both absent), on SUCCESS:",
        f"   at {ns} pedestrians : {_gap_sparse:+.3f}",
        f"   at {nd} pedestrians : {_gap_dense:+.3f}",
        f"Same contrast on MINIMUM SEPARATION:",
        f"   at {ns} pedestrians : {_sep_sparse:+.3f} m",
        f"   at {nd} pedestrians : {_sep_dense:+.3f} m",
        "",
        "If the joint effect grows with density, the correct claim is not 'these terms do not",
        "matter' but 'these terms are insurance that this scenario was not crowded enough to",
        "collect on'.  That is a materially different recommendation for anyone deploying in a",
        "real corridor or station concourse, and it is the sort of scope condition a reward",
        "ablation should be expected to state.",
        "",
        "If the joint effect does NOT grow with density, the null is robust across a doubling of",
        "the crowd, which is a much stronger negative result than a single-density null and is",
        "worth reporting as such.",
        "",
        "Caveat to keep in the paper: the observation dimension changes with the number of",
        "pedestrians, so absolute numbers are not comparable across densities.  Only the",
        "WITHIN-density contrasts above are.",
    ])
    BUDGET.mark("stage B")
else:
    print("stage B skipped by the budget guard")

  [budget] B  density n=10              12 runs x  500,000 steps ->  0.36 h   left  0.26 h   SKIP (would overrun)
stage B skipped by the budget guard

## 16 · Stage E — the best recipe, and the deployment artefact

Everything above is an *ablation*: every arm gets an identical budget so that no configuration can win by having been trained longer. That control is what makes the comparison valid, and it also means none of those arms is the best policy this reward design can produce.

Stage E deliberately breaks the equal-budget rule and says so. We take the configuration with the strongest evidence — ranked by the **lower** bound of its bootstrap interval on success, so an arm does not win by being lucky on one seed — and retrain it at an extended budget across all seeds. This is the number the paper should quote as "our method achieves …", clearly separated from the ablation table.

The resulting policy is exported to **ONNX** and *numerically verified* against SB3's own `predict(deterministic=True)` on 512 random observations. An export nobody checked is a deployment bug waiting to happen. Note the correct extraction path for PPO — `extract_features → mlp_extractor.forward_actor → action_net`, then clamp — since `model.policy.actor` does **not** exist on `ActorCriticPolicy`; that attribute belongs to `SAC`/`TD3`. Because observation normalisation lives *inside* the environment as fixed constants (no `VecNormalize`), the exported graph is self-contained: a ROS 2 node only has to build the observation vector described in `deployment_spec.json` and call `Run()`.

In [25]:
from stable_baselines3 import PPO

_score = agg_A.set_index(agg_A["config"].astype(str))
BEST_ARM = (_score["success_lo"]).idxmax() if len(_score) else REFERENCE
print(f"best arm by the LOWER bootstrap bound on success: {display_name(BEST_ARM)} "
      f"(mean {_score.loc[BEST_ARM,'success_mean']:.3f}, "
      f"95% CI [{_score.loc[BEST_ARM,'success_lo']:.3f}, {_score.loc[BEST_ARM,'success_hi']:.3f}])")

per_run_E = pd.DataFrame()
eroot = os.path.join(OUT, "stages", "best_recipe")
os.makedirs(os.path.join(eroot, "runs"), exist_ok=True)
if BUDGET.stage("E  best recipe", len(SEEDS), STAGE_E_STEPS, AGG_FPS):
    train_many([(BEST_ARM, s) for s in SEEDS], STAGE_E_STEPS, N_ENVS, eroot,
               device=DEVICE, env_overrides=TRAIN_ENV, n_parallel=N_PARALLEL,
               verbose=True, net_width=NET_WIDTH)
    per_run_E, per_ep_E = evaluate_stage([BEST_ARM], SEEDS, eroot, TEST_SEEDS, TEST_ENV,
                                         n_workers=10, label="(stage E)")
    per_run_E.to_csv(f"{OUT}/tables/per_run_summary_E.csv", index=False)
    _pt, _lo, _hi = AS.bootstrap_ci(per_run_E["success"].values, n_boot=N_BOOT)
    _hpt, _hlo, _hhi = AS.hierarchical_bootstrap_ci(per_ep_E, "success", n_boot=2000)
    display(per_run_E[["config", "seed", "success", "collision", "timeout",
                       "nav_time_succ", "path_length_ratio_succ", "intrusion_count",
                       "min_separation", "mean_sq_accel"]].round(3))
    _abl = float(_score.loc[BEST_ARM, "success_mean"])
    narrate("HEADLINE POLICY", [
        f"Configuration {display_name(BEST_ARM)} retrained at {STAGE_E_STEPS:,} steps per seed "
        f"(vs {STEPS_PER_RUN:,} in the ablation), {len(SEEDS)} seeds, evaluated on the same "
        f"{N_EVAL_EPISODES} held-out scenarios.",
        "",
        f"   success  {_pt:.3f}  [95% CI {_lo:.3f}, {_hi:.3f}]  (bootstrap over seeds)",
        f"            {_hpt:.3f}  [95% CI {_hlo:.3f}, {_hhi:.3f}]  (hierarchical bootstrap: "
        f"seeds resampled, then episodes within seed)",
        f"   collision {per_run_E['collision'].mean():.3f}   "
        f"timeout {per_run_E['timeout'].mean():.3f}   "
        f"nav time {per_run_E['nav_time_succ'].mean():.2f} s   "
        f"path ratio {per_run_E['path_length_ratio_succ'].mean():.3f}",
        "",
        f"For comparison the same configuration at the ablation budget scored {_abl:.3f}, and the "
        f"best non-learning planner on these scenarios scored "
        f"{baseline_runs[baseline_runs.config.str.startswith('ORCA')]['success'].max():.3f}.",
        "",
        "Quote this row as the method's performance and the stage-A table as the ablation.",
        "Mixing them -- reporting the longest-trained arm inside an ablation table -- is how",
        "equal-budget control quietly gets lost.",
    ])
    BUDGET.mark("stage E")
else:
    print("stage E skipped by the budget guard -- the ONNX export will use the best stage-A run")

# ---------------- ONNX export ---------------------------------------------
_src_root = eroot if len(per_run_E) else OUT
_src_runs = per_run_E if len(per_run_E) else per_run_A[per_run_A.config == BEST_ARM]
_best_seed = int(_src_runs.sort_values("success").iloc[-1]["seed"])
_mp = os.path.join(_src_root, "runs", f"{BEST_ARM}__seed{_best_seed}", "model.zip")
print(f"\nexporting {display_name(BEST_ARM)} seed {_best_seed} from {_src_root}")
model = PPO.load(_mp, device="cpu")
onnx_path = f"{OUT}/onnx/crowd_nav_policy.onnx"
# The export is a deliverable, not a dependency: if the onnx toolchain is
# missing (notebook internet off, for instance) we say so and carry on rather
# than losing the figures, the synthesis and the results package that follow.
ONNX_OK = False
if HAS_ONNX:
    try:
        export_onnx(model, onnx_path, OBS_DIM, opset=17)
        print(f"wrote {onnx_path}  ({os.path.getsize(onnx_path)/1024:.0f} KB)")
        err, ok = verify_onnx(model, onnx_path, OBS_DIM, n=512)
        print(f"ONNX vs SB3 max abs action error: {err:.3e}  -> "
              f"{'MATCH' if ok else 'MISMATCH'}")
        assert ok, "ONNX graph does not reproduce the SB3 policy"
        ONNX_OK = True
    except Exception as _e:
        print(f"!! ONNX export failed ({type(_e).__name__}: {_e})")
        print("   The trained policy is still available as model.zip in the run directory;")
        print("   re-run this cell with internet enabled to produce the ONNX graph.")
else:
    print("!! onnx / onnxruntime are not installed -- export skipped.")
    print("   The trained policy is still available as model.zip in the run directory.")

spec = {
    "model": "crowd_nav_policy.onnx" if ONNX_OK else "(export skipped -- see notes)",
    "onnx_exported": ONNX_OK,
    "source_run": f"{BEST_ARM}__seed{_best_seed}",
    "source_stage": "E (extended budget)" if len(per_run_E) else "A (ablation budget)",
    "components_active": {cid: bool(b) for cid, b in
                          zip(COMPONENT_IDS, ABLATION_CONFIGS[BEST_ARM])},
    "input":  {"name": "obs", "shape": [1, OBS_DIM], "dtype": "float32"},
    "output": {"name": "action", "shape": [1, 2], "dtype": "float32",
               "meaning": "(v_toward_goal, v_lateral) / v_pref, clipped to [-1, 1]"},
    "observation_layout": {
        "robot[0:5]": ["dist_to_goal/pos_scale", "v_pref/vel_scale", "robot_radius",
                       "vx_goalframe/vel_scale", "vy_goalframe/vel_scale"],
        "human_i[5+7i : 12+7i]": ["px/pos_scale", "py/pos_scale", "vx/vel_scale",
                                  "vy/vel_scale", "radius", "dist/pos_scale",
                                  "surface_dist/pos_scale"],
        "human_order": "nearest first",
        "n_humans": _probe.n_humans,
    },
    "frame": "translate to robot, then rotate by -atan2(goal - robot) so the goal is on +x",
    "normalisation": {"pos_scale": _probe.pos_scale, "vel_scale": _probe.vel_scale},
    "control": {"time_step_s": _probe.time_step, "v_pref_mps": _probe.v_pref,
                "kinematics": _probe.kinematics},
    "note": ("Observation normalisation is INSIDE the environment (fixed constants, no "
             "VecNormalize), so this graph is self-contained: build the vector above and "
             "call Run()."),
}
json.dump(spec, open(f"{OUT}/onnx/deployment_spec.json", "w"), indent=2)
print(json.dumps(spec, indent=2)[:900] + "\n...")
del model

best arm by the LOWER bootstrap bound on success: R1-5_full [R12345] (mean 0.983, 95% CI [0.979, 0.986])
  [budget] E  best recipe                6 runs x  750,000 steps ->  0.27 h   left  0.26 h   SKIP (would overrun)
stage E skipped by the budget guard -- the ONNX export will use the best stage-A run

exporting R1-5_full [R12345] seed 5 from /kaggle/working/results
wrote /kaggle/working/results/onnx/crowd_nav_policy.onnx  (88 KB)
ONNX vs SB3 max abs action error: 0.000e+00  -> MATCH
{
  "model": "crowd_nav_policy.onnx",
  "onnx_exported": true,
  "source_run": "R12345__seed5",
  "source_stage": "A (ablation budget)",
  "components_active": {
    "R1": true,
    "R2": true,
    "R3": true,
    "R4": true,
    "R5": true
  },
  "input": {
    "name": "obs",
    "shape": [
      1,
      40
    ],
    "dtype": "float32"
  },
  "output": {
    "name": "action",
    "shape": [
      1,
      2
    ],
    "dtype": "float32",
    "meaning": "(v_toward_goal, v_lateral) / v_pref, clipped to [-1, 1]"
  },
  "observation_layout": {
    "robot[0:5]": [
      "dist_to_goal/pos_scale",
      "v_pref/vel_scale",
      "robot_radius",
      "vx_goalframe/vel_scale",
      "vy_goalframe/vel_scale"
    ],
    "human_i[5+7i : 12+7i]": [
      "px/pos_scale",
      "py/pos_scale",
      "vx/vel_scale",
      "vy/vel_scale",
      "radius",
      "dist/pos_scale",
      "surface_dist/po
...

## 17 · Figures

Ten publication-ready figures at 300 dpi, written to `results/figures/`. The two that carry the paper's contribution are **fig3 (attribution)** and **fig4 (interaction heatmap)**: the first shows where the conventional leave-one-out number disagrees with the context-averaged one, the second explains why.

In [26]:
import matplotlib.pyplot as plt

FIGS = {}

# --- fig1: learning curves for the arms worth plotting ----------------------
_CURVE = [a for a in ["R12345", "R2345", "R1345", "R1245", "R1235", "R1234",
                      "R125", "R12", "R1", "R0_none"] if a in LATTICE_ARMS]
fig, axes = plt.subplots(2, 2, figsize=(11.5, 6.6))
for ax, m, t in zip(axes.ravel(),
                    ["success", "collision", "intrusion_rate", "action_autocorr"],
                    ["Success rate", "Collision rate",
                     "Personal-space intrusion rate", "Lag-1 action autocorrelation"]):
    viz.plot_learning_curves(os.path.join(OUT, "runs"), _CURVE, metric=m, ax=ax, title=t)
fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig1_learning_curves.png", bbox_inches="tight")
FIGS["fig1_learning_curves"] = "training curves, mean +/- s.e.m. across seeds"
plt.show()

# --- fig2: leave-one-out bars (the conventional view) -----------------------
_loo_agg = agg_A[agg_A["config"].astype(str).isin(LOO_ARMS)].copy()
_loo_agg["config"] = _loo_agg["config"].astype(str).map(lambda c: ALIASES.get(c, c))
fig = viz.plot_ablation_bars(
    _loo_agg, ["success", "collision", "timeout", "intrusion_count",
               "path_length_ratio_succ", "nav_time_succ", "mean_sq_accel",
               "min_separation"],
    reference=ALIASES.get(REFERENCE, REFERENCE), ncols=4,
    titles={"success": "Success rate ↑", "collision": "Collision rate ↓",
            "timeout": "Timeout rate ↓", "intrusion_count": "Space intrusions / ep ↓",
            "path_length_ratio_succ": "Path-length ratio ↓",
            "nav_time_succ": "Navigation time [s] ↓",
            "mean_sq_accel": "Mean sq. acceleration ↓",
            "min_separation": "Min. separation [m] ↑"})
fig.suptitle("Leave-one-out ablation — the conventional view", y=1.01, fontsize=11)
fig.savefig(f"{OUT}/figures/fig2_leave_one_out.png", bbox_inches="tight")
FIGS["fig2_leave_one_out"] = "conventional leave-one-out bars with bootstrap CIs"
plt.show()

In [27]:
# --- fig3 + fig4: attribution and interactions (the contribution) ----------
if LATTICE_COMPLETE and "success" in analyses:
    A = analyses["success"]
    fig, axes = plt.subplots(1, 2, figsize=(13.2, 4.2),
                             gridspec_kw={"width_ratios": [1.65, 1.0]})
    viz.plot_attribution(A, COMP_LABELS, metric_label="success rate", ax=axes[0])
    viz.plot_interaction_heatmap(A, list(COMPONENT_IDS), ax=axes[1])
    fig.tight_layout()
    fig.savefig(f"{OUT}/figures/fig3_attribution_and_interactions.png", bbox_inches="tight")
    FIGS["fig3_attribution_and_interactions"] = \
        "Shapley vs leave-one-out vs add-one-in, and the pairwise interaction matrix"
    plt.show()

    fig, ax = plt.subplots(figsize=(8.6, 4.2))
    viz.plot_lattice_landscape(A["tables"], _arm_from_indices,
                               metric_label="success rate", ax=ax)
    fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig4_lattice_landscape.png",
                                    bbox_inches="tight")
    FIGS["fig4_lattice_landscape"] = "all 32 cells by number of active components"
    plt.show()

    # attribution on every metric, one panel each
    _ms = [m for m in SHAPLEY_METRICS if m in analyses]
    fig, axes = plt.subplots(2, int(np.ceil(len(_ms) / 2)),
                             figsize=(4.6 * int(np.ceil(len(_ms) / 2)), 7.2))
    for ax, m in zip(np.atleast_1d(axes).ravel(), _ms):
        viz.plot_attribution(analyses[m], list(COMPONENT_IDS), metric_label=m,
                             ax=ax, title=m.replace("_", " "))
        ax.legend().set_visible(False)
    for ax in np.atleast_1d(axes).ravel()[len(_ms):]:
        ax.axis("off")
    np.atleast_1d(axes).ravel()[0].legend(fontsize=7, ncol=3)
    fig.suptitle("Component attribution across every reported metric", y=1.005, fontsize=11)
    fig.tight_layout()
    fig.savefig(f"{OUT}/figures/fig5_attribution_all_metrics.png", bbox_inches="tight")
    FIGS["fig5_attribution_all_metrics"] = "Shapley/LOO/AOI on every metric"
    plt.show()

In [28]:
# --- fig6: safety/efficiency frontier --------------------------------------
fig, ax = plt.subplots(figsize=(7.0, 5.0))
_front = agg_A[agg_A["success_mean"] > 0.05].reset_index(drop=True)
viz.plot_pareto(_front, x="nav_time_succ", y="collision", ax=ax)
for _, r in baseline_runs.iterrows():
    if not np.isfinite(r["nav_time_succ"]):
        continue
    ax.scatter(r["nav_time_succ"], r["collision"], marker="^", s=80,
               facecolor="none", edgecolor="0.25", linewidth=1.2, zorder=5)
    ax.annotate(r["config"], (r["nav_time_succ"], r["collision"]),
                textcoords="offset points", xytext=(6, -9), fontsize=6.5, color="0.3")
ax.set_title("Safety / efficiency frontier — ● reward configurations, △ classical planners")
fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig6_pareto.png", bbox_inches="tight")
FIGS["fig6_pareto"] = "collision vs navigation time, learned arms and classical planners"
plt.show()

# --- fig7: behavioural profile heatmap -------------------------------------
_prof_arms = [a for a in LOO_ARMS + ["R125", "R12", "R1", "R0_none"] if a in LATTICE_ARMS]
fig, ax = plt.subplots(figsize=(10.5, 0.42 * len(_prof_arms) + 2.4))
viz.plot_metric_profile(agg_A, _prof_arms,
                        ["success", "collision", "timeout", "min_separation",
                         "intrusion_count", "nav_time_succ", "path_length_ratio_succ",
                         "mean_sq_accel", "action_autocorr", "displacement_efficiency"],
                        ax=ax, reference=REFERENCE)
fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig7_behaviour_profile.png", bbox_inches="tight")
FIGS["fig7_behaviour_profile"] = "arm x metric heatmap in s.d. units vs the reference"
plt.show()

In [29]:
# --- fig8: jerk dose-response and mechanism control ------------------------
_panels = int(len(jerk_df) > 0) * 2 + int(len(mech_df) > 0)
if _panels:
    fig, axes = plt.subplots(1, _panels, figsize=(5.2 * _panels, 3.9))
    axes = np.atleast_1d(axes); k = 0
    if len(jerk_df):
        viz.plot_dose_response(jerk_df, "w_jerk", "success", ax=axes[k],
                               title="Dose–response: success vs $w_{jerk}$",
                               ylabel="success rate"); k += 1
        viz.plot_dose_response(jerk_df, "w_jerk", "action_autocorr", ax=axes[k],
                               title="Dose–response: action coherence vs $w_{jerk}$",
                               ylabel="lag-1 action autocorrelation"); k += 1
    if len(mech_df):
        viz.plot_mechanism(mech_df, ax=axes[k])
    fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig8_jerk_mechanism.png",
                                    bbox_inches="tight")
    FIGS["fig8_jerk_mechanism"] = "w_jerk dose-response and the action-filter mechanism control"
    plt.show()

# --- fig9: density generalisation ------------------------------------------
if len(density_df):
    fig, axes = plt.subplots(1, 3, figsize=(15.0, 3.9))
    for ax, m, t in zip(axes, ["success", "min_separation", "intrusion_count"],
                        ["Success rate", "Minimum separation [m]",
                         "Personal-space intrusions / episode"]):
        viz.plot_density_effects(density_df, DENSITY_ARMS, metric=m, ax=ax, title=t)
    fig.suptitle("Do R3 and R4 only bind when the crowd binds?", y=1.03, fontsize=11)
    fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig9_density.png", bbox_inches="tight")
    FIGS["fig9_density"] = "the {R3,R4} sub-factorial at two pedestrian densities"
    plt.show()

# --- fig10: qualitative trajectories on one shared scenario ----------------
SHOW = [a for a in [REFERENCE, "R2345", "R1345", "R1234", "R125", "R0_none"]
        if a in LATTICE_ARMS]
SCENARIO = TEST_SEEDS[7]
fig, axes = plt.subplots(1, len(SHOW), figsize=(3.4 * len(SHOW), 3.9))
axes = np.atleast_1d(axes)
for ax, cfg_name in zip(axes, SHOW):
    mp = os.path.join(OUT, "runs", f"{cfg_name}__seed{SEEDS[0]}", "model.zip")
    if not os.path.exists(mp):
        ax.axis("off"); continue
    m_ = PPO.load(mp, device="cpu")
    env = CrowdNavAblationEnv(make_cfg(cfg_name, record_trajectory=True, **EXPERIMENT))
    obs, _ = env.reset(seed=SCENARIO)
    while True:
        a_, _ = m_.predict(obs, deterministic=True)
        obs, _, te, tu, info = env.step(a_)
        if te or tu: break
    mm = info["episode_metrics"]
    outcome = "success" if mm["success"] else ("COLLISION" if mm["collision"] else "timeout")
    viz.plot_trajectory(env, ax=ax,
        title=f"{display_name(cfg_name)}\n{outcome} | t={mm['nav_time']:.1f}s | "
              f"msa={mm['mean_sq_accel']:.2f} | ac={mm['action_autocorr']:+.2f}")
    del m_
fig.tight_layout(); fig.savefig(f"{OUT}/figures/fig10_trajectories.png", bbox_inches="tight")
FIGS["fig10_trajectories"] = "qualitative trajectories on one shared held-out scenario"
plt.show()
BUDGET.mark("figures")

  [budget] figures                    done at  8.58 h |  0.26 h left

## 18 · Synthesis — the findings, written out

Everything below is generated from the tables above, so it cannot drift from the numbers. This is the section to read alongside the executed notebook, and it is the skeleton of the paper's results narrative.

In [30]:
lines = []
lines.append(f"DESIGN.  {len(LATTICE_ARMS)} reward configurations x {len(SEEDS)} training seeds "
             f"x {STEPS_PER_RUN:,} steps, every policy evaluated deterministically on the same "
             f"{N_EVAL_EPISODES} held-out circle-crossing scenarios with "
             f"{EXPERIMENT['n_humans']} ORCA pedestrians and an invisible robot.")
lines.append("")

if LATTICE_COMPLETE and "success" in analyses:
    A = analyses["success"]
    ranked = sorted(range(5), key=lambda i: -A["shapley"][i]["mean"])
    lines.append("FINDING 1 -- how much each component is worth, averaged over all 16 contexts.")
    for r, i in enumerate(ranked, 1):
        s, l, a = A["shapley"][i], A["loo"][i], A["aoi"][i]
        share = 100 * s["mean"] / A["total_mean"] if abs(A["total_mean"]) > 1e-9 else float("nan")
        lines.append(f"  {r}. {COMPONENT_IDS[i]} {COMPONENT_NAMES[i]:22s} "
                     f"phi={s['mean']:+.3f} [{s['lo']:+.3f},{s['hi']:+.3f}] p={s['p']:.4f}  "
                     f"({share:5.1f}% of the total effect)   LOO={l['mean']:+.3f}  "
                     f"AOI={a['mean']:+.3f}")
    _big = [COMPONENT_IDS[i] for i in ranked
            if A["shapley"][i]["p"] < 0.05 and abs(A["shapley"][i]["mean"]) > 0.05]
    _small = [COMPONENT_IDS[i] for i in range(5) if COMPONENT_IDS[i] not in _big]
    lines.append(f"  => {len(_big)} of 5 components carry a materially non-zero share of the "
                 f"result on success rate: {', '.join(_big) if _big else 'none'}.")
    lines.append(f"     The remaining {len(_small)} ({', '.join(_small)}) do not, ON SUCCESS.")
    lines.append("")

    lines.append("FINDING 2 -- where the conventional leave-one-out number misleads.")
    any_flip = False
    for i in range(5):
        l, s, a = A["loo"][i]["mean"], A["shapley"][i]["mean"], A["aoi"][i]["mean"]
        if abs(l - s) > 0.08:
            any_flip = True
            kind = ("OVERSTATES" if abs(l) > abs(s) else "UNDERSTATES")
            lines.append(f"  {COMPONENT_IDS[i]}: leave-one-out {l:+.3f} vs Shapley {s:+.3f} "
                         f"-- the single-context number {kind} this component's contribution "
                         f"by {abs(l-s):.3f} success.")
    if not any_flip:
        lines.append("  No component's leave-one-out number differs materially from its Shapley "
                     "value: attribution is context-free in this task.")
    lines.append("")

    inter_l = sorted(zip(A["interaction_pairs"], A["interaction"]),
                     key=lambda t: t[1]["mean"])
    lines.append("FINDING 3 -- why: the interaction structure.")
    for (i, j), row in inter_l:
        if row["hi"] < 0:
            lines.append(f"  {COMPONENT_IDS[i]} x {COMPONENT_IDS[j]}: {row['mean']:+.3f} "
                         f"[{row['lo']:+.3f},{row['hi']:+.3f}] SUBSTITUTES -- each covers for the "
                         f"other, so dropping either ALONE costs little and leave-one-out cannot "
                         f"see either of them.")
        elif row["lo"] > 0:
            lines.append(f"  {COMPONENT_IDS[i]} x {COMPONENT_IDS[j]}: {row['mean']:+.3f} "
                         f"[{row['lo']:+.3f},{row['hi']:+.3f}] COMPLEMENTS -- neither pays off "
                         f"without the other, so they must be tuned jointly.")
    if not any(r["hi"] < 0 or r["lo"] > 0 for _, r in inter_l):
        lines.append("  No pairwise interaction is distinguishable from zero: the components are "
                     "approximately additive, and a leave-one-out design would have been "
                     "adequate here.")
    lines.append("")

    lines.append("FINDING 4 -- the same five components, judged on SOCIAL rather than task metrics.")
    for i in range(5):
        row_sep = attrib[(attrib.component == COMPONENT_IDS[i]) &
                         (attrib.metric == "min_separation")]
        row_int = attrib[(attrib.component == COMPONENT_IDS[i]) &
                         (attrib.metric == "intrusion_count")]
        if len(row_sep) and len(row_int):
            lines.append(f"  {COMPONENT_IDS[i]}: min-separation phi={row_sep['shapley'].iloc[0]:+.4f} m, "
                         f"intrusions/episode phi={row_int['shapley'].iloc[0]:+.4f}")
    lines.append("  => A component with phi ~ 0 on success but a positive phi on separation and a "
                 "negative phi on intrusions is buying social compliance at no task cost. For a "
                 "SOCIALLY AWARE navigator that is a reason to keep it, not to delete it.")
    lines.append("")

if len(mech_df):
    def _mn(g, col="success"):
        v = mech_df[mech_df.group == g][col]
        return float(v.mean()) if len(v) else float("nan")
    lines.append("FINDING 5 -- the mechanism behind the smoothness term.")
    lines.append(f"  no-jerk arm, untouched            success {_mn('no-jerk, no filter (stage A)'):.3f}  "
                 f"autocorr {_mn('no-jerk, no filter (stage A)','action_autocorr'):+.3f}")
    for lbl in ["nojerk+filter.5", "nojerk+filter.8", "full+filter.5"]:
        if (mech_df.group == lbl).any():
            lines.append(f"  {lbl:32s} success {_mn(lbl):.3f}  "
                         f"autocorr {_mn(lbl,'action_autocorr'):+.3f}")
    lines.append(f"  full reward (R5 on, no filter)    success {_mn('full reward (stage A)'):.3f}  "
                 f"autocorr {_mn('full reward (stage A)','action_autocorr'):+.3f}")
    _resc = max(_mn("nojerk+filter.5"), _mn("nojerk+filter.8"))
    lines.append(f"  => Supplying temporal action coherence from the DYNAMICS, with the jerk "
                 f"weight held at exactly zero, "
                 f"{'recovers' if _resc > 0.25 else 'does NOT recover'} the arm "
                 f"({_resc:.3f} success).")
    lines.append("")

if len(jerk_df):
    _g = jerk_df.groupby("w_jerk")["success"].mean()
    lines.append("FINDING 6 -- how sharply the smoothness weight has to be tuned.")
    lines.append("  " + "  ".join(f"w={w:g}:{v:.2f}" for w, v in _g.items()))
    lines.append(f"  => optimum near w_jerk = {float(_g.idxmax()):g}; the curve is "
                 f"{'monotone' if np.all(np.diff(_g.values) >= -0.02) else 'non-monotone'}, "
                 f"which is diagnostic of an exploration effect rather than a preference.")
    lines.append("")

if len(density_df):
    def _dd(arm, col, n):
        v = density_df[(density_df.config == arm) & (density_df.n_humans == n)][col]
        return float(v.mean()) if len(v) else float("nan")
    ns, nd = EXPERIMENT["n_humans"], DENSITY_N_HUMANS
    lines.append("FINDING 7 -- scope conditions on the social terms.")
    lines.append(f"  joint R3+R4 effect on success:        {ns}p {_dd('R12345','success',ns)-_dd('R125','success',ns):+.3f}"
                 f"   {nd}p {_dd('R12345','success',nd)-_dd('R125','success',nd):+.3f}")
    lines.append(f"  joint R3+R4 effect on min separation: {ns}p {_dd('R12345','min_separation',ns)-_dd('R125','min_separation',ns):+.3f}"
                 f"   {nd}p {_dd('R12345','min_separation',nd)-_dd('R125','min_separation',nd):+.3f}")
    lines.append("")

if len(per_run_E):
    lines.append("HEADLINE POLICY.")
    lines.append(f"  {display_name(BEST_ARM)} at {STAGE_E_STEPS:,} steps x {len(SEEDS)} seeds: "
                 f"success {per_run_E['success'].mean():.3f}, "
                 f"collision {per_run_E['collision'].mean():.3f}, "
                 f"timeout {per_run_E['timeout'].mean():.3f}, "
                 f"nav time {per_run_E['nav_time_succ'].mean():.2f} s.")
    lines.append(f"  Best classical planner on the same scenarios: "
                 f"{baseline_runs[baseline_runs.config.str.startswith('ORCA')]['success'].max():.3f} success.")
    lines.append("")

narrate("SYNTHESIS -- WHAT THIS STUDY FOUND", lines, width=118)

with open(f"{OUT}/tables/synthesis.txt", "w") as f:
    f.write("\n".join(lines))

======================================================================================================================
|| SYNTHESIS -- WHAT THIS STUDY FOUND
----------------------------------------------------------------------------------------------------------------------
   DESIGN.  32 reward configurations x 6 training seeds x 500,000 steps, every policy evaluated deterministically on
   the same 500 held-out circle-crossing scenarios with 5 ORCA pedestrians and an invisible robot.

   FINDING 1 -- how much each component is worth, averaged over all 16 contexts.
     1. R5 jerk / smoothness      phi=+0.643 [+0.463,+0.837] p=0.0312  ( 65.4% of the total effect)   LOO=+0.983
   AOI=+0.486
     2. R2 distance shaping       phi=+0.400 [+0.209,+0.572] p=0.0625  ( 40.7% of the total effect)   LOO=+0.818
   AOI=+0.248
     3. R1 goal reaching          phi=+0.007 [+0.002,+0.013] p=0.0625  (  0.7% of the total effect)   LOO=+0.008
   AOI=+0.000
     4. R3 personal space         phi=-0.001 [-0.079,+0.104] p=1.0000  ( -0.1% of the total effect)   LOO=+0.172
   AOI=+0.000
     5. R4 time-to-collision      phi=-0.066 [-0.151,-0.006] p=0.1875  ( -6.7% of the total effect)   LOO=+0.004
   AOI=+0.000
     => 1 of 5 components carry a materially non-zero share of the result on success rate: R5.
        The remaining 4 (R1, R2, R3, R4) do not, ON SUCCESS.

   FINDING 2 -- where the conventional leave-one-out number misleads.
     R2: leave-one-out +0.818 vs Shapley +0.400 -- the single-context number OVERSTATES this component's
   contribution by 0.417 success.
     R3: leave-one-out +0.172 vs Shapley -0.001 -- the single-context number OVERSTATES this component's
   contribution by 0.173 success.
     R5: leave-one-out +0.983 vs Shapley +0.643 -- the single-context number OVERSTATES this component's
   contribution by 0.340 success.

   FINDING 3 -- why: the interaction structure.
     R4 x R5: -0.109 [-0.205,-0.031] SUBSTITUTES -- each covers for the other, so dropping either ALONE costs little
   and leave-one-out cannot see either of them.
     R1 x R3: -0.009 [-0.020,-0.003] SUBSTITUTES -- each covers for the other, so dropping either ALONE costs little
   and leave-one-out cannot see either of them.
     R2 x R5: +0.483 [+0.205,+0.760] COMPLEMENTS -- neither pays off without the other, so they must be tuned
   jointly.

   FINDING 4 -- the same five components, judged on SOCIAL rather than task metrics.
     R1: min-separation phi=-0.0256 m, intrusions/episode phi=+0.0948
     R2: min-separation phi=-0.4404 m, intrusions/episode phi=+0.3372
     R3: min-separation phi=+0.0085 m, intrusions/episode phi=-0.0716
     R4: min-separation phi=+0.0786 m, intrusions/episode phi=-0.0898
     R5: min-separation phi=-0.6210 m, intrusions/episode phi=+0.6640
     => A component with phi ~ 0 on success but a positive phi on separation and a negative phi on intrusions is
   buying social compliance at no task cost. For a SOCIALLY AWARE navigator that is a reason to keep it, not to
   delete it.

   FINDING 6 -- how sharply the smoothness weight has to be tuned.
     w=0:0.00  w=0.002:0.00  w=0.005:0.00  w=0.01:0.33  w=0.02:0.97  w=0.05:0.87  w=0.1:0.51  w=0.2:0.71
     => optimum near w_jerk = 0.02; the curve is non-monotone, which is diagnostic of an exploration effect rather
   than a preference.

======================================================================================================================

### 18.1 · Camera-ready LaTeX tables

Two tables are written to `results/tables/`: the conventional leave-one-out ablation (for the section a reviewer expects) and the attribution table (for the section that is the contribution).

In [31]:
_tex_loo = agg_A[agg_A["config"].astype(str).isin(LOO_ARMS)].copy()
_tex_loo["config"] = _tex_loo["config"].astype(str).map(lambda c: ALIASES.get(c, c))
tex1 = viz.to_latex(
    _tex_loo, ["success", "collision", "timeout", "intrusion_count",
               "nav_time_succ", "mean_sq_accel", "min_separation"],
    caption=(f"Leave-one-out ablation of the five reward components. Mean $\\pm$ half the "
             f"95\\% bootstrap interval over {len(SEEDS)} training seeds, each evaluated on the "
             f"same {N_EVAL_EPISODES} held-out circle-crossing scenarios with "
             f"{EXPERIMENT['n_humans']} ORCA pedestrians and an invisible robot."),
    label="tab:leave-one-out")
open(f"{OUT}/tables/table1_leave_one_out.tex", "w").write(tex1)

if LATTICE_COMPLETE and "success" in analyses:
    A = analyses["success"]
    rows = [r"\begin{table}[t]", r"\centering", r"\small",
            r"\begin{tabular}{llcccc}", r"\toprule",
            r"ID & Component & Shapley $\phi_i$ & \%\,share & Leave-one-out & Add-one-in \\",
            r"\midrule"]
    for i, cid in enumerate(COMPONENT_IDS):
        s, l, a = A["shapley"][i], A["loo"][i], A["aoi"][i]
        share = 100 * s["mean"] / A["total_mean"] if abs(A["total_mean"]) > 1e-9 else float("nan")
        star = ("$^{*}$" if s["p"] < 0.05 else "")
        rows.append(f"{cid} & {COMPONENT_NAMES[i]} & "
                    f"${s['mean']:+.3f}${star} \\tiny{{[{s['lo']:+.3f},{s['hi']:+.3f}]}} & "
                    f"{share:.1f} & ${l['mean']:+.3f}$ & ${a['mean']:+.3f}$ \\\\")
    rows += [r"\midrule",
             f"& Sum (efficiency) & ${sum(r['mean'] for r in A['shapley']):+.3f}$ & 100.0 & & \\\\",
             r"\bottomrule", r"\end{tabular}",
             (r"\caption{Exact component attribution over the complete $2^5$ factorial "
              f"({len(LATTICE_ARMS)} reward configurations $\\times$ {A['n_seeds']} seeds). "
              r"The Shapley value averages each component's marginal contribution over all "
              r"$2^4$ contexts and is computed exactly, independently within each seed; "
              r"brackets give the percentile bootstrap 95\% interval across seeds and "
              r"$^{*}$ marks $p<0.05$ under an exact sign-flip permutation test. "
              r"Leave-one-out and add-one-in are the two single-context special cases. "
              r"By efficiency the Shapley values sum exactly to "
              f"$v(\\text{{full}})-v(\\text{{task-only}})={A['total_mean']:+.3f}$.}}"),
             r"\label{tab:attribution}", r"\end{table}"]
    open(f"{OUT}/tables/table2_attribution.tex", "w").write("\n".join(rows))
    print("\n".join(rows))
print("\nLaTeX tables written to results/tables/table1_leave_one_out.tex and table2_attribution.tex")

\begin{table}[t]
\centering
\small
\begin{tabular}{llcccc}
\toprule
ID & Component & Shapley $\phi_i$ & \%\,share & Leave-one-out & Add-one-in \\
\midrule
R1 & goal reaching & $+0.007$ \tiny{[+0.002,+0.013]} & 0.7 & $+0.008$ & $+0.000$ \\
R2 & distance shaping & $+0.400$ \tiny{[+0.209,+0.572]} & 40.7 & $+0.818$ & $+0.248$ \\
R3 & personal space & $-0.001$ \tiny{[-0.079,+0.104]} & -0.1 & $+0.172$ & $+0.000$ \\
R4 & time-to-collision & $-0.066$ \tiny{[-0.151,-0.006]} & -6.7 & $+0.004$ & $+0.000$ \\
R5 & jerk / smoothness & $+0.643$$^{*}$ \tiny{[+0.463,+0.837]} & 65.4 & $+0.983$ & $+0.486$ \\
\midrule
& Sum (efficiency) & $+0.983$ & 100.0 & & \\
\bottomrule
\end{tabular}
\caption{Exact component attribution over the complete $2^5$ factorial (32 reward configurations $\times$ 6 seeds). The Shapley value averages each component's marginal contribution over all $2^4$ contexts and is computed exactly, independently within each seed; brackets give the percentile bootstrap 95\% interval across seeds and $^{*}$ marks $p<0.05$ under an exact sign-flip permutation test. Leave-one-out and add-one-in are the two single-context special cases. By efficiency the Shapley values sum exactly to $v(\text{full})-v(\text{task-only})=+0.983$.}
\label{tab:attribution}
\end{table}

LaTeX tables written to results/tables/table1_leave_one_out.tex and table2_attribution.tex

## 19 · Results package

In [32]:
manifest = {
    "experiment": "RL-CrowdNav V5 -- reward-shaping ablation via the complete 2^5 factorial",
    "version": "5.0",
    "generated_utc": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
    "software": {"python": platform.python_version(), "numpy": np.__version__,
                 "pandas": pd.__version__, "torch": th.__version__,
                 "gymnasium": gym.__version__, "stable_baselines3": SB3_VERSION},
    "hardware": {"cpu_count": os.cpu_count(),
                 "gpus": [th.cuda.get_device_name(i) for i in range(th.cuda.device_count())]},
    "design": {
        "lattice_arms": LATTICE_ARMS,
        "aliases": ALIASES,
        "components": {cid: nm for cid, nm in zip(COMPONENT_IDS, COMPONENT_NAMES)},
        "reference": REFERENCE,
        "seeds": SEEDS,
        "steps_per_run": STEPS_PER_RUN,
        "stage_E_steps": STAGE_E_STEPS,
        "net_width": NET_WIDTH,
        "n_envs": N_ENVS,
        "n_parallel_runs": N_PARALLEL,
        "eval_episodes": N_EVAL_EPISODES,
        "test_seed_range": [TEST_SEEDS[0], TEST_SEEDS[-1]],
        "equivalence_margin_success": EQUIV_MARGIN,
        "crowd_pool": (None if not USE_CROWD_POOL else
                       {"train_size": TRAIN_POOL_SIZE, "train_seed_base": TRAIN_POOL_BASE}),
        "stages": {
            "A": "complete 2^5 lattice",
            "B": f"density n={DENSITY_N_HUMANS}, {{R3,R4}} sub-factorial",
            "C1": f"w_jerk dose-response over {JERK_WEIGHTS}",
            "C2": "action low-pass filter mechanism control",
            "D": "PBRS vs progress shaping form",
            "E": "best configuration at extended budget + ONNX",
        },
    },
    "scenario": EXPERIMENT,
    "env_config": {k: v for k, v in vars(_probe).items()
                   if not k.startswith("_") and isinstance(v, (int, float, str, bool, tuple))},
    "orca_crossvalidation": (None if RVO2_XVAL is None else
                             {"max_abs_velocity_error": RVO2_XVAL[0],
                              "n_agent_steps": RVO2_XVAL[1]}),
    "budget_log": BUDGET.frame().to_dict("records"),
    "figures": FIGS,
    "artifacts": {
        "per_episode_eval_A.csv.gz":   "every stage-A evaluation episode",
        "per_run_summary_A.csv":       "one row per (arm, seed)",
        "aggregated_by_config_A.csv":  "bootstrap mean / CI / median / IQR per arm",
        "component_attribution.csv":   "PRIMARY: Shapley, leave-one-out and add-one-in per component per metric",
        "interactions.csv":            "PRIMARY: pairwise Shapley interaction indices",
        "mobius_dividends.csv":        "full Moebius/Harsanyi decomposition",
        "leave_one_out_tests.csv":     "seed-level exact sign-flip tests vs the reference",
        "equivalence_tests.csv":       "TOST equivalence tests for the null components",
        "shaping_form_contrast.csv":   "PBRS vs progress shaping",
        "jerk_dose_response.csv":      "w_jerk sweep",
        "mechanism_control.csv":       "action-filter causal control",
        "density_sweep.csv":           "the {R3,R4} sub-factorial at two densities",
        "reward_landscape_audit.csv":  "competent / freeze / dash returns per arm, pre-training",
        "arch_preflight.csv":          "equal-wall-clock network-width selection",
        "preflight.csv":               "short-budget learning check + measured throughput",
        "training_health.csv":         "per-seed collapse and exploration-runaway detection",
        "baselines_summary.csv":       "freeze, straight-line and ORCA(sigma) planners",
        "synthesis.txt":               "the generated findings narrative",
        "table1_leave_one_out.tex":    "camera-ready conventional ablation table",
        "table2_attribution.tex":      "camera-ready attribution table",
        "figures/":                    "300 dpi publication figures",
        "onnx/":                       "exported policy + deployment_spec.json",
        "runs/<arm>__seed<k>/":        "model.zip, per-episode training logs, monitor, meta.json",
    },
}
json.dump(manifest, open(f"{OUT}/MANIFEST.json", "w"), indent=2, default=str)

shutil.make_archive(os.path.join(WORK, "crowdnav_v5_results"), "zip", OUT)
_sz = os.path.getsize(os.path.join(WORK, "crowdnav_v5_results.zip")) / 1e6
print(f"packaged results/  ->  crowdnav_v5_results.zip  ({_sz:.1f} MB)\n")
for root, _, files in os.walk(OUT):
    if "/runs/" in root + "/":
        continue
    for f in sorted(files):
        p = os.path.join(root, f)
        print(f"  {os.path.relpath(p, WORK):62s} {os.path.getsize(p)/1024:9.1f} KB")
print(f"\n  results/runs/  ->  {len(glob.glob(OUT + '/runs/*'))} stage-A run directories")
print(f"  results/stages/ -> {len(glob.glob(OUT + '/stages/*'))} auxiliary stage directories")
print(f"\ntotal session wall clock: {BUDGET.elapsed/3600:.2f} h of a "
      f"{WALL_BUDGET_HOURS:.1f} h budget")
display(BUDGET.frame())

packaged results/  ->  crowdnav_v5_results.zip  (316.2 MB)

  results/MANIFEST.json                                                7.0 KB
  results/stages/jerk_sweep/JK0p002/tb/R12345__seed1_1/events.out.tfevents.1789818351.c7380bbadcf9.600.0     100.6 KB
  results/stages/jerk_sweep/JK0p002/tb/R12345__seed0_1/events.out.tfevents.1789818347.c7380bbadcf9.604.0     100.6 KB
  results/stages/jerk_sweep/JK0p002/tb/R12345__seed2_1/events.out.tfevents.1789818351.c7380bbadcf9.603.0     100.6 KB
  results/stages/jerk_sweep/JK0p05/tb/R12345__seed1_1/events.out.tfevents.1789819366.c7380bbadcf9.716.0     100.6 KB
  results/stages/jerk_sweep/JK0p05/tb/R12345__seed0_1/events.out.tfevents.1789819370.c7380bbadcf9.719.0     100.6 KB
  results/stages/jerk_sweep/JK0p05/tb/R12345__seed2_1/events.out.tfevents.1789819370.c7380bbadcf9.720.0     100.6 KB
  results/stages/jerk_sweep/JK0p005/tb/R12345__seed1_1/events.out.tfevents.1789818606.c7380bbadcf9.629.0     100.6 KB
  results/stages/jerk_sweep/JK0p005/tb/R12345__seed0_1/events.out.tfevents.1789818603.c7380bbadcf9.632.0     100.6 KB
  results/stages/jerk_sweep/JK0p005/tb/R12345__seed2_1/events.out.tfevents.1789818603.c7380bbadcf9.633.0     100.6 KB
  results/stages/jerk_sweep/JK0/tb/R12345__seed1_1/events.out.tfevents.1789818098.c7380bbadcf9.575.0     100.6 KB
  results/stages/jerk_sweep/JK0/tb/R12345__seed0_1/events.out.tfevents.1789818095.c7380bbadcf9.571.0     100.6 KB
  results/stages/jerk_sweep/JK0/tb/R12345__seed2_1/events.out.tfevents.1789818099.c7380bbadcf9.574.0     100.6 KB
  results/stages/jerk_sweep/JK0p2/tb/R12345__seed1_1/events.out.tfevents.1789819889.c7380bbadcf9.774.0     100.6 KB
  results/stages/jerk_sweep/JK0p2/tb/R12345__seed0_1/events.out.tfevents.1789819887.c7380bbadcf9.778.0     100.6 KB
  results/stages/jerk_sweep/JK0p2/tb/R12345__seed2_1/events.out.tfevents.1789819886.c7380bbadcf9.777.0     100.6 KB
  results/stages/jerk_sweep/JK0p02/tb/R12345__seed1_1/events.out.tfevents.1789819119.c7380bbadcf9.690.0     100.6 KB
  results/stages/jerk_sweep/JK0p02/tb/R12345__seed0_1/events.out.tfevents.1789819122.c7380bbadcf9.687.0     100.6 KB
  results/stages/jerk_sweep/JK0p02/tb/R12345__seed2_1/events.out.tfevents.1789819121.c7380bbadcf9.691.0     100.6 KB
  results/stages/jerk_sweep/JK0p1/tb/R12345__seed1_1/events.out.tfevents.1789819632.c7380bbadcf9.745.0     100.6 KB
  results/stages/jerk_sweep/JK0p1/tb/R12345__seed0_1/events.out.tfevents.1789819631.c7380bbadcf9.748.0     100.6 KB
  results/stages/jerk_sweep/JK0p1/tb/R12345__seed2_1/events.out.tfevents.1789819630.c7380bbadcf9.749.0     100.6 KB
  results/stages/jerk_sweep/JK0p01/tb/R12345__seed1_1/events.out.tfevents.1789818864.c7380bbadcf9.658.0     100.6 KB
  results/stages/jerk_sweep/JK0p01/tb/R12345__seed0_1/events.out.tfevents.1789818860.c7380bbadcf9.662.0     100.6 KB
  results/stages/jerk_sweep/JK0p01/tb/R12345__seed2_1/events.out.tfevents.1789818863.c7380bbadcf9.661.0     100.6 KB
  results/tables/aggregated_by_config_A.csv                           29.4 KB
  results/tables/arch_preflight.csv                                    0.2 KB
  results/tables/baselines_summary.csv                                 1.7 KB
  results/tables/component_attribution.csv                             5.5 KB
  results/tables/equivalence_tests.csv                                 0.6 KB
  results/tables/interactions.csv                                      1.0 KB
  results/tables/jerk_dose_response.csv                                6.1 KB
  results/tables/leave_one_out_tests.csv                               5.8 KB
  results/tables/mobius_dividends.csv                                  1.0 KB
  results/tables/orca_crossvalidation.json                             0.1 KB
  results/tables/per_episode_eval_A.csv.gz                          8569.0 KB
  results/tables/per_run_summary_A.csv                                44.0 KB
  results/tables/per_run_summary_D.csv                                 3.6 KB
  results/tables/preflight.csv                                         0.3 KB
  results/tables/reward_landscape_audit.csv                            4.3 KB
  results/tables/shaping_form_contrast.csv                             0.9 KB
  results/tables/synthesis.txt                                         2.9 KB
  results/tables/table1_leave_one_out.tex                              1.3 KB
  results/tables/table2_attribution.tex                                1.2 KB
  results/tables/training_health.csv                                  20.3 KB
  results/tables/training_meta_A.csv                                  95.9 KB
  results/tables/training_meta_D.csv                                   6.3 KB
  results/onnx/crowd_nav_policy.onnx                                  87.7 KB
  results/onnx/deployment_spec.json                                    1.4 KB
  results/preflight/R12345/train_episodes.csv                        902.9 KB
  results/preflight/R12345/train_rollouts.csv                          6.8 KB
  results/preflight/R2345/train_episodes.csv                         905.8 KB
  results/preflight/R2345/train_rollouts.csv                           6.8 KB
  results/preflight/R125/train_episodes.csv                          916.1 KB
  results/preflight/R125/train_rollouts.csv                            6.8 KB
  results/preflight/arch256/train_episodes.csv                      1736.0 KB
  results/preflight/arch256/train_rollouts.csv                        15.7 KB
  results/preflight/R1234/train_episodes.csv                         341.1 KB
  results/preflight/R1234/train_rollouts.csv                           6.8 KB
  results/preflight/arch128/train_episodes.csv                      1814.3 KB
  results/preflight/arch128/train_rollouts.csv                        18.1 KB
  results/tb/R2345__seed5_1/events.out.tfevents.1789794505.c7380bbadcf9.299.8     200.2 KB
  results/tb/R4__seed0_1/events.out.tfevents.1789811652.c7380bbadcf9.303.44     200.2 KB
  results/tb/R12__seed1_1/events.out.tfevents.1789802353.c7380bbadcf9.302.24     200.2 KB
  results/tb/P12345_progress__seed5_1/events.out.tfevents.1789816915.c7380bbadcf9.525.1     200.2 KB
  results/tb/R12__seed0_1/events.out.tfevents.1789802246.c7380bbadcf9.303.24     200.2 KB
  results/tb/R34__seed3_1/events.out.tfevents.1789807585.c7380bbadcf9.302.35     200.2 KB
  results/tb/R1234__seed0_1/events.out.tfevents.1789790947.c7380bbadcf9.302.1     200.2 KB
  results/tb/R2__seed1_1/events.out.tfevents.1789810284.c7380bbadcf9.303.41     200.2 KB
  results/tb/R123__seed5_1/events.out.tfevents.1789795434.c7380bbadcf9.302.10     200.2 KB
  results/tb/R25__seed5_1/events.out.tfevents.1789807120.c7380bbadcf9.302.34     200.2 KB
  results/tb/R13__seed1_1/events.out.tfevents.1789802980.c7380bbadcf9.304.25     200.2 KB
  results/tb/R25__seed3_1/events.out.tfevents.1789806847.c7380bbadcf9.304.33     200.2 KB
  results/tb/R134__seed4_1/events.out.tfevents.1789797476.c7380bbadcf9.299.14     200.2 KB
  results/tb/R125__seed0_1/events.out.tfevents.1789796351.c7380bbadcf9.303.12     200.2 KB
  results/tb/R3__seed4_1/events.out.tfevents.1789811222.c7380bbadcf9.304.42     200.2 KB
  results/tb/R145__seed1_1/events.out.tfevents.1789798478.c7380bbadcf9.304.16     200.2 KB
  results/tb/R234__seed2_1/events.out.tfevents.1789799490.c7380bbadcf9.299.18     200.2 KB
  results/tb/R124__seed5_1/events.out.tfevents.1789795995.c7380bbadcf9.304.11     200.2 KB
  results/tb/R134__seed0_1/events.out.tfevents.1789796961.c7380bbadcf9.299.13     200.2 KB
  results/tb/R145__seed0_1/events.out.tfevents.1789798465.c7380bbadcf9.299.16     200.2 KB
  results/tb/R23__seed2_1/events.out.tfevents.1789805349.c7380bbadcf9.299.30     200.2 KB
  results/tb/R234__seed5_1/events.out.tfevents.1789799811.c7380bbadcf9.302.19     200.2 KB
  results/tb/R15__seed4_1/events.out.tfevents.1789804883.c7380bbadcf9.299.29     200.2 KB
  results/tb/R13__seed0_1/events.out.tfevents.1789802973.c7380bbadcf9.299.25     200.2 KB
  results/tb/R35__seed0_1/events.out.tfevents.1789807927.c7380bbadcf9.303.36     200.2 KB
  results/tb/R12345__seed3_1/events.out.tfevents.1789790426.c7380bbadcf9.304.0     200.2 KB
  results/tb/R235__seed2_1/events.out.tfevents.1789800236.c7380bbadcf9.303.20     200.2 KB
  results/tb/R1345__seed2_1/events.out.tfevents.1789793470.c7380bbadcf9.304.6     200.2 KB
  results/tb/R124__seed2_1/events.out.tfevents.1789795852.c7380bbadcf9.303.11     200.2 KB
  results/tb/R345__seed0_1/events.out.tfevents.1789801479.c7380bbadcf9.299.22     200.2 KB
  results/tb/R134__seed2_1/events.out.tfevents.1789797270.c7380bbadcf9.303.14     200.2 KB
  results/tb/R5__seed5_1/events.out.tfevents.1789812831.c7380bbadcf9.302.46     200.2 KB
  results/tb/R123__seed0_1/events.out.tfevents.1789794936.c7380bbadcf9.303.9     200.2 KB
  results/tb/R15__seed2_1/events.out.tfevents.1789804624.c7380bbadcf9.303.29     200.2 KB
  results/tb/R2345__seed4_1/events.out.tfevents.1789794503.c7380bbadcf9.304.8     200.2 KB
  results/tb/R1__seed5_1/events.out.tfevents.1789810008.c7380bbadcf9.302.40     200.2 KB
  results/tb/R1__seed1_1/events.out.tfevents.1789809549.c7380bbadcf9.302.39     200.2 KB
  results/tb/R1245__seed2_1/events.out.tfevents.1789792898.c7380bbadcf9.303.5     200.2 KB
  results/tb/R135__seed1_1/events.out.tfevents.1789797847.c7380bbadcf9.302.15     200.2 KB
  results/tb/R4__seed4_1/events.out.tfevents.1789812158.c7380bbadcf9.303.45     200.2 KB
  results/tb/R234__seed4_1/events.out.tfevents.1789799725.c7380bbadcf9.303.19     200.2 KB
  results/tb/R35__seed3_1/events.out.tfevents.1789808333.c7380bbadcf9.304.36     200.2 KB
  results/tb/R1345__seed4_1/events.out.tfevents.1789793911.c7380bbadcf9.303.7     200.2 KB
  results/tb/R125__seed5_1/events.out.tfevents.1789796867.c7380bbadcf9.302.13     200.2 KB
  results/tb/R123__seed3_1/events.out.tfevents.1789795024.c7380bbadcf9.299.9     200.2 KB
  results/tb/R2345__seed2_1/events.out.tfevents.1789794421.c7380bbadcf9.303.8     200.2 KB
  results/tb/R12__seed3_1/events.out.tfevents.1789802526.c7380bbadcf9.304.24     200.2 KB
  results/tb/R23__seed3_1/events.out.tfevents.1789805362.c7380bbadcf9.304.30     200.2 KB
  results/tb/R45__seed1_1/events.out.tfevents.1789808807.c7380bbadcf9.304.37     200.2 KB
  results/tb/R4__seed1_1/events.out.tfevents.1789811663.c7380bbadcf9.299.43     200.2 KB
  results/tb/R12345__seed1_1/events.out.tfevents.1789790426.c7380bbadcf9.299.0     200.2 KB
  results/tb/R24__seed0_1/events.out.tfevents.1789805814.c7380bbadcf9.299.31     200.2 KB
  results/tb/R25__seed4_1/events.out.tfevents.1789806966.c7380bbadcf9.303.34     200.2 KB
  results/tb/R2345__seed0_1/events.out.tfevents.1789793985.c7380bbadcf9.304.7     200.2 KB
  results/tb/R1235__seed2_1/events.out.tfevents.1789791977.c7380bbadcf9.299.3     200.2 KB
  results/tb/R1245__seed3_1/events.out.tfevents.1789792911.c7380bbadcf9.302.5     200.2 KB
  results/tb/P2345_progress__seed3_1/events.out.tfevents.1789817442.c7380bbadcf9.529.2     200.2 KB
  results/tb/R124__seed1_1/events.out.tfevents.1789795488.c7380bbadcf9.299.10     200.2 KB
  results/tb/R0_none__seed1_1/events.out.tfevents.1789813119.c7380bbadcf9.303.47     200.2 KB
  results/tb/P12345_progress__seed2_1/events.out.tfevents.1789816398.c7380bbadcf9.529.0     200.2 KB
  results/tb/R135__seed4_1/events.out.tfevents.1789798249.c7380bbadcf9.303.16     200.2 KB
  results/tb/R123__seed2_1/events.out.tfevents.1789795023.c7380bbadcf9.304.9     200.2 KB
  results/tb/R13__seed5_1/events.out.tfevents.1789803444.c7380bbadcf9.304.26     200.2 KB
  results/tb/R245__seed5_1/events.out.tfevents.1789801318.c7380bbadcf9.302.22     200.2 KB
  results/tb/R12__seed4_1/events.out.tfevents.1789802698.c7380bbadcf9.303.25     200.2 KB
  results/tb/R3__seed1_1/events.out.tfevents.1789810925.c7380bbadcf9.302.42     200.2 KB
  results/tb/R34__seed5_1/events.out.tfevents.1789807819.c7380bbadcf9.304.35     200.2 KB
  results/tb/R24__seed3_1/events.out.tfevents.1789806148.c7380bbadcf9.302.32     200.2 KB
  results/tb/R0_none__seed0_1/events.out.tfevents.1789813119.c7380bbadcf9.304.46     200.2 KB
  results/tb/R1234__seed2_1/events.out.tfevents.1789791458.c7380bbadcf9.302.2     200.2 KB
  results/tb/R5__seed0_1/events.out.tfevents.1789812194.c7380bbadcf9.304.44     200.2 KB
  results/tb/R1234__seed3_1/events.out.tfevents.1789791458.c7380bbadcf9.303.2     200.2 KB
  results/tb/R12345__seed0_1/events.out.tfevents.1789790426.c7380bbadcf9.302.0     200.2 KB
  results/tb/R45__seed3_1/events.out.tfevents.1789809035.c7380bbadcf9.302.38     200.2 KB
  results/tb/R145__seed2_1/events.out.tfevents.1789798713.c7380bbadcf9.303.17     200.2 KB
  results/tb/R14__seed5_1/events.out.tfevents.1789804240.c7380bbadcf9.302.28     200.2 KB
  results/tb/R345__seed5_1/events.out.tfevents.1789802002.c7380bbadcf9.304.23     200.2 KB
  results/tb/R2__seed2_1/events.out.tfevents.1789810298.c7380bbadcf9.304.40     200.2 KB
  results/tb/R23__seed1_1/events.out.tfevents.1789805214.c7380bbadcf9.302.30     200.2 KB
  results/tb/R13__seed2_1/events.out.tfevents.1789803148.c7380bbadcf9.303.26     200.2 KB
  results/tb/R123__seed1_1/events.out.tfevents.1789794967.c7380bbadcf9.302.9     200.2 KB
  results/tb/P2345_progress__seed4_1/events.out.tfevents.1789817446.c7380bbadcf9.525.2     200.2 KB
  results/tb/R125__seed1_1/events.out.tfevents.1789796404.c7380bbadcf9.302.12     200.2 KB
  results/tb/R235__seed4_1/events.out.tfevents.1789800480.c7380bbadcf9.299.20     200.2 KB
  results/tb/R1235__seed0_1/events.out.tfevents.1789791966.c7380bbadcf9.303.3     200.2 KB
  results/tb/R45__seed2_1/events.out.tfevents.1789808864.c7380bbadcf9.303.38     200.2 KB
  results/tb/R3__seed0_1/events.out.tfevents.1789810756.c7380bbadcf9.304.41     200.2 KB
  results/tb/R134__seed1_1/events.out.tfevents.1789796970.c7380bbadcf9.304.13     200.2 KB
  results/tb/R14__seed1_1/events.out.tfevents.1789803730.c7380bbadcf9.302.27     200.2 KB
  results/tb/R23__seed5_1/events.out.tfevents.1789805677.c7380bbadcf9.302.31     200.2 KB
  results/tb/R1245__seed1_1/events.out.tfevents.1789792449.c7380bbadcf9.304.4     200.2 KB
  results/tb/R234__seed0_1/events.out.tfevents.1789799220.c7380bbadcf9.303.18     200.2 KB
  results/tb/R125__seed3_1/events.out.tfevents.1789796503.c7380bbadcf9.304.12     200.2 KB
  results/tb/R13__seed4_1/events.out.tfevents.1789803436.c7380bbadcf9.299.26     200.2 KB
  results/tb/R235__seed3_1/events.out.tfevents.1789800329.c7380bbadcf9.302.20     200.2 KB
  results/tb/R235__seed0_1/events.out.tfevents.1789800006.c7380bbadcf9.299.19     200.2 KB
  results/tb/R135__seed3_1/events.out.tfevents.1789798006.c7380bbadcf9.304.15     200.2 KB
  results/tb/R35__seed5_1/events.out.tfevents.1789808558.c7380bbadcf9.302.37     200.2 KB
  results/tb/R4__seed3_1/events.out.tfevents.1789811856.c7380bbadcf9.302.44     200.2 KB
  results/tb/R245__seed0_1/events.out.tfevents.1789800707.c7380bbadcf9.303.21     200.2 KB
  results/tb/R1235__seed5_1/events.out.tfevents.1789792441.c7380bbadcf9.302.4     200.2 KB
  results/tb/R0_none__seed5_1/events.out.tfevents.1789813573.c7380bbadcf9.304.47     200.2 KB
  results/tb/R2__seed0_1/events.out.tfevents.1789810278.c7380bbadcf9.299.40     200.2 KB
  results/tb/R35__seed4_1/events.out.tfevents.1789808393.c7380bbadcf9.303.37     200.2 KB
  results/tb/P12345_progress__seed1_1/events.out.tfevents.1789816398.c7380bbadcf9.528.0     200.2 KB
  results/tb/R45__seed0_1/events.out.tfevents.1789808789.c7380bbadcf9.299.37     200.2 KB
  results/tb/P12345_progress__seed3_1/events.out.tfevents.1789816398.c7380bbadcf9.530.0     200.2 KB
  results/tb/R345__seed1_1/events.out.tfevents.1789801483.c7380bbadcf9.304.22     200.2 KB
  results/tb/R245__seed4_1/events.out.tfevents.1789801221.c7380bbadcf9.303.22     200.2 KB
  results/tb/R1234__seed4_1/events.out.tfevents.1789791464.c7380bbadcf9.299.2     200.2 KB
  results/tb/R145__seed3_1/events.out.tfevents.1789798794.c7380bbadcf9.302.17     200.2 KB
  results/tb/R134__seed5_1/events.out.tfevents.1789797486.c7380bbadcf9.304.14     200.2 KB
  results/tb/R35__seed1_1/events.out.tfevents.1789808090.c7380bbadcf9.302.36     200.2 KB
  results/tb/R15__seed0_1/events.out.tfevents.1789804416.c7380bbadcf9.299.28     200.2 KB
  results/tb/R1234__seed1_1/events.out.tfevents.1789790950.c7380bbadcf9.304.1     200.2 KB
  results/tb/R234__seed1_1/events.out.tfevents.1789799303.c7380bbadcf9.302.18     200.2 KB
  results/tb/R1235__seed3_1/events.out.tfevents.1789791980.c7380bbadcf9.304.3     200.2 KB
  results/tb/R0_none__seed4_1/events.out.tfevents.1789813572.c7380bbadcf9.303.48     200.2 KB
  results/tb/R125__seed4_1/events.out.tfevents.1789796809.c7380bbadcf9.303.13     200.2 KB
  results/tb/R1345__seed1_1/events.out.tfevents.1789793420.c7380bbadcf9.302.6     200.2 KB
  results/tb/R2345__seed3_1/events.out.tfevents.1789794450.c7380bbadcf9.302.8     200.2 KB
  results/tb/R12__seed5_1/events.out.tfevents.1789802807.c7380bbadcf9.302.25     200.2 KB
  results/tb/R124__seed0_1/events.out.tfevents.1789795487.c7380bbadcf9.304.10     200.2 KB
  results/tb/R3__seed3_1/events.out.tfevents.1789811197.c7380bbadcf9.299.42     200.2 KB
  results/tb/P12345_progress__seed0_1/events.out.tfevents.1789816398.c7380bbadcf9.525.0     200.2 KB
  results/tb/R5__seed2_1/events.out.tfevents.1789812658.c7380bbadcf9.304.45     200.2 KB
  results/tb/R5__seed1_1/events.out.tfevents.1789812368.c7380bbadcf9.302.45     200.2 KB
  results/tb/R2__seed4_1/events.out.tfevents.1789810741.c7380bbadcf9.299.41     200.2 KB
  results/tb/R14__seed4_1/events.out.tfevents.1789804115.c7380bbadcf9.303.28     200.2 KB
  results/tb/R15__seed1_1/events.out.tfevents.1789804429.c7380bbadcf9.304.28     200.2 KB
  results/tb/R14__seed2_1/events.out.tfevents.1789803907.c7380bbadcf9.299.27     200.2 KB
  results/tb/R245__seed2_1/events.out.tfevents.1789800959.c7380bbadcf9.299.21     200.2 KB
  results/tb/R14__seed3_1/events.out.tfevents.1789803919.c7380bbadcf9.304.27     200.2 KB
  results/tb/R235__seed1_1/events.out.tfevents.1789800016.c7380bbadcf9.304.19     200.2 KB
  results/tb/R135__seed5_1/events.out.tfevents.1789798320.c7380bbadcf9.302.16     200.2 KB
  results/tb/R25__seed1_1/events.out.tfevents.1789806657.c7380bbadcf9.302.33     200.2 KB
  results/tb/R234__seed3_1/events.out.tfevents.1789799499.c7380bbadcf9.304.18     200.2 KB
  results/tb/R12345__seed2_1/events.out.tfevents.1789790426.c7380bbadcf9.303.0     200.2 KB
  results/tb/P2345_progress__seed1_1/events.out.tfevents.1789816921.c7380bbadcf9.528.1     200.2 KB
  results/tb/P12345_progress__seed4_1/events.out.tfevents.1789816914.c7380bbadcf9.530.1     200.2 KB
  results/tb/R5__seed4_1/events.out.tfevents.1789812681.c7380bbadcf9.299.45     200.2 KB
  results/tb/R13__seed3_1/events.out.tfevents.1789803261.c7380bbadcf9.302.26     200.2 KB
  results/tb/R1245__seed0_1/events.out.tfevents.1789792448.c7380bbadcf9.299.4     200.2 KB
  results/tb/R34__seed2_1/events.out.tfevents.1789807426.c7380bbadcf9.303.35     200.2 KB
  results/tb/R3__seed2_1/events.out.tfevents.1789811194.c7380bbadcf9.303.43     200.2 KB
  results/tb/R5__seed3_1/events.out.tfevents.1789812662.c7380bbadcf9.303.46     200.2 KB
  results/tb/R124__seed4_1/events.out.tfevents.1789795994.c7380bbadcf9.299.11     200.2 KB
  results/tb/R15__seed3_1/events.out.tfevents.1789804752.c7380bbadcf9.302.29     200.2 KB
  results/tb/R1345__seed3_1/events.out.tfevents.1789793474.c7380bbadcf9.299.6     200.2 KB
  results/tb/R2345__seed1_1/events.out.tfevents.1789793989.c7380bbadcf9.299.7     200.2 KB
  results/tb/R23__seed0_1/events.out.tfevents.1789805082.c7380bbadcf9.303.30     200.2 KB
  results/tb/R145__seed5_1/events.out.tfevents.1789798994.c7380bbadcf9.304.17     200.2 KB
  results/tb/P2345_progress__seed0_1/events.out.tfevents.1789816916.c7380bbadcf9.529.1     200.2 KB
  results/tb/P2345_progress__seed2_1/events.out.tfevents.1789817438.c7380bbadcf9.530.2     200.2 KB
  results/tb/R0_none__seed3_1/events.out.tfevents.1789813295.c7380bbadcf9.302.47     200.2 KB
  results/tb/R12345__seed5_1/events.out.tfevents.1789790946.c7380bbadcf9.299.1     200.2 KB

                stage  elapsed_h  remaining_h
0          crowd pool      0.065        9.235
1        reward audit      0.114        9.186
2           baselines      0.124        9.176
3    stage A training      6.840        1.992
4      stage A health      6.841        1.991
5  stage A evaluation      7.529        1.302
6             stage D      8.002        0.829
7            stage C1      8.571        0.261
8             figures      8.576        0.256

## 20 · Reproducibility statement, limitations and references

### Reproducibility

**Determinism.** Python, NumPy, PyTorch and CUDA RNGs are seeded per run; `cudnn.deterministic=True`, `cudnn.benchmark=False`. The environment's stochasticity is confined to a single `numpy.random.Generator` seeded at `reset`, and §4 asserts that a given `(seed, action sequence)` reproduces a bit-identical trajectory. Standard caveat: PPO is not bit-reproducible across different `n_envs`, because the rollout-to-update boundary changes. `n_envs`, `net_width` and `steps_per_run` are recorded per run in `meta.json` and in `MANIFEST.json`.

**Controls.** Environment, observation space, action space, network architecture, algorithm, every hyper-parameter, the training budget and the evaluation scenarios are identical across all arms of stages A–D. §4 check 4 asserts that each of the 34 configurations emits *exactly* the reward terms it declares and no others. The collision penalty and the per-step time cost are deliberately *not* ablated: removing either changes the task rather than the shaping. Stage E intentionally uses a longer budget and is reported separately from the ablation for that reason.

**Statistics.** Six independent training seeds per arm; 500 shared held-out scenarios per policy. The seed is the unit of analysis. Interval estimates are percentile bootstraps over seeds (and, for the headline policy, a hierarchical bootstrap that resamples seeds and then episodes within seed). Significance is by **exact** sign-flip permutation test — with six seeds all 64 sign assignments are enumerated, so the smallest attainable two-sided $p$ is $0.031$ and no asymptotic approximation is used. Families of comparisons are Holm–Bonferroni corrected. Null results are supported by **TOST equivalence tests** against a margin of $\pm0.02$ success declared before the results were seen.

**Attribution.** Shapley values, the Möbius decomposition and interaction indices are computed exactly by enumeration over the complete 32-cell lattice, separately within each seed — no model is fitted and no sampling approximation is used. The implementation is verified in §4 check 10 against closed-form games (additive, pure-substitute and pure-complement) whose values are known analytically, and against the efficiency identity $\sum_i\phi_i=v(N)-v(\varnothing)$, which holds to floating-point precision on the real data.

### Limitations to state in the write-up

- **Simulation only.** 2-D holonomic kinematics with perfect state observation: no sensor noise, no occlusion, no detection dropout, no localisation error. Sim-to-real transfer is not demonstrated here; the ONNX export is the bridge, not evidence.
- **ORCA pedestrians are not humans.** They are reciprocal, deterministic, and lack intent, groups, and social convention. Conclusions about "social compliance" are therefore conclusions about **proxemic geometry**, not about human comfort. That distinction needs a user study, and the paper should say so plainly.
- **Fixed weights.** Components are switched on and off at hand-chosen weights, not tuned per arm. A component could underperform because its weight is mis-scaled rather than because it is unhelpful. The `w_jerk` dose–response addresses this for the one component where it matters most; a full joint weight sweep is the natural follow-up, and the interaction table says which components would have to be swept *jointly* rather than independently.
- **One scenario family.** Circle crossing at two densities. Corridors, doorways and intersections impose different geometry and may redistribute the attribution — in particular, terms that are substitutes here need not be substitutes in a bottleneck.
- **The Shapley value is an average, not a recommendation.** It answers "how much credit does this component deserve across all designs?", not "should I include it in mine?". For a specific target configuration the relevant numbers are the conditional ones — which is exactly why the leave-one-out and add-one-in columns are reported alongside it rather than replaced by it.
- **The action-filter control changes the dynamics, not only the exploration.** A filtered environment is a (mildly) different control problem, so the rescue demonstrates that temporal coherence is *sufficient* to recover performance without the reward term; it does not prove that coherence is the *only* channel through which R5 acts.
- **Equal budget is a choice.** Every arm gets the same number of steps, so an arm that is merely slower to converge is scored as worse. The learning curves in fig1 and the peak-vs-final diagnostics in §8.1 are included so a reader can separate "never learns" from "would have, given more".
- **Six seeds is the floor, not a luxury.** It is the smallest sample for which an exact two-sided permutation test can return $p<0.05$ at all. Effects smaller than roughly the seed-to-seed standard deviation cannot be resolved by this design, which is precisely why equivalence testing rather than non-significance is used to support the null claims.

### References

1. Chen, Liu, Kreiss & Alahi. *Crowd-Robot Interaction: Crowd-aware Robot Navigation with Attention-based Deep Reinforcement Learning.* ICRA 2019.
2. van den Berg, Guy, Lin & Manocha. *Reciprocal n-body Collision Avoidance.* ISRR 2011.
3. Ng, Harada & Russell. *Policy Invariance Under Reward Transformations: Theory and Application to Reward Shaping.* ICML 1999.
4. Shapley. *A Value for n-Person Games.* Contributions to the Theory of Games II, 1953.
5. Grabisch & Roubens. *An Axiomatic Approach to the Concept of Interaction Among Players in Cooperative Games.* International Journal of Game Theory, 1999.
6. Schulman, Wolski, Dhariwal, Radford & Klimov. *Proximal Policy Optimization Algorithms.* arXiv:1707.06347.
7. Raffin, Hill, Gleave, Kanervisto, Ernestus & Dormann. *Stable-Baselines3: Reliable Reinforcement Learning Implementations.* JMLR 2021.
8. Lakens. *Equivalence Tests: A Practical Primer for t Tests, Correlations, and Meta-Analyses.* Social Psychological and Personality Science, 2017.
9. Agarwal, Schwarzer, Castro, Courville & Bellemare. *Deep Reinforcement Learning at the Edge of the Statistical Precipice.* NeurIPS 2021.
10. Pardo, Tavakoli, Levdik & Kormushev. *Time Limits in Reinforcement Learning.* ICML 2018.